version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - python3-pip

  commands:
    # 1) Upgrade pip itself
    - pip3 install --upgrade pip
    # 2) Install your package + Sphinx in one go
    - pip3 install . sphinx sphinx_rtd_theme
    # 3) Build the docs
    - sphinx-build -b html docs/source docs/build/html
