version: 2

build:
  os: ubuntu-22.04
  commands:
    # 1) Install your package
    - python3 -m pip install .
    # 2) Install Sphinx & the RTD theme
    - python3 -m pip install sphinx sphinx_rtd_theme
    # 3) Build the docs
    - python3 -m sphinx -b html docs/source docs/build/html
