version: 2

build:
  os: ubuntu-22.04
  commands:
    # 0) Bootstrap pip
    - python3 -m ensurepip --upgrade
    # 1) Upgrade pip itself
    - python3 -m pip install --upgrade pip
    # 2) Install your package
    - python3 -m pip install .
    # 3) Install Sphinx & RTD theme
    - python3 -m pip install sphinx sphinx_rtd_theme
    # 4) Build the docs
    - python3 -m sphinx -b html docs/source docs/build/html
