version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - libhdf5-dev
    - libhdf5-serial-dev

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
