version: 2

build:
  os: ubuntu-22.04
  commands:
    # 1) Install your package
    - pip install .
    # 2) Install Sphinx & theme
    - pip install sphinx sphinx_rtd_theme
    # 3) Build the docs
    - sphinx-build -b html docs/source docs/build/html
