"""Bio-Rad Image Lab ``.scn`` reading and its integration points."""
from __future__ import annotations

import glob
import os
from pathlib import Path

import numpy as np
import pytest

from spacr.convert import read_scn, scn_to_rgb8

REAL_SCN_GLOB = ("/mnt/wd4tb/af3/projects/automated_plaque_assay/new_data/"
                 "*/*.scn")


def _image_header(width, height, *, endian="little", zero_is="white",
                  ceiling=4095, size_mm=(130.777, 97.7071), known="true",
                  height_first=False):
    if height_first:
        pix = f'<size_pix height="{height}" width="{width}"/>'
        scanner = f'<scanner max_value="{ceiling}" data_ceiling="{ceiling}"/>'
        mm = (f'<size_mm height="{size_mm[1]}" width="{size_mm[0]}" '
              f'known="{known}"/>' if size_mm else "")
        imager = '<imager name="Imager" type="0" value="Gel Doc™ XR+"/>'
    else:
        pix = f'<size_pix width="{width}" height="{height}"/>'
        scanner = f'<scanner data_ceiling="{ceiling}" max_value="{ceiling}"/>'
        mm = (f'<size_mm known="{known}" width="{size_mm[0]}" '
              f'height="{size_mm[1]}"/>' if size_mm else "")
        imager = '<imager type="0" name="Imager" value="Gel Doc™ XR+"/>'
    return (
        "<!DOCTYPE XML>\n<root>\n <name></name>\n"
        f" <endian>{endian}</endian>\n {pix}\n {mm}\n {scanner}\n"
        f' <image zero_is="{zero_is}"/>\n <scan_attributes>\n  {imager}\n'
        '  <image_date type="3" name="Image Date" value="2026-10-05T12:58:31"/>\n'
        '  <exposure_time type="1" name="Exposure Time (sec)" value="0.168"/>\n'
        '  <application type="0" name="Application" value="Coomassie Blue"/>\n'
        '  <excitation_source type="0" name="Excitation Source" '
        'value="White Trans Illumination"/>\n'
        " </scan_attributes>\n</root>\n").encode("utf-8")


def _part(headers, body):
    lines = "".join(f"{k}: {v}\r\n" for k, v in headers)
    return lines.encode("latin-1") + b"\r\n" + body + b"\r\n"


def write_scn(path, images, **header_kwargs):
    """Write a synthetic Image Lab file holding ``images`` (uint16 arrays)."""
    outer = b"20261005-125845-085B2488"
    blocks = [b"MIME-Version: 1.0 (Generated by Image Lab 6.0.1)\r\n"
              b'Content-Type: multipart/mixed; boundary="' + outer + b'"\r\n'
              b"Content-Description: Image Lab Image File\r\n\r\n"]
    item = b'<!DOCTYPE XML>\n<root version="2"><name>synthetic</name></root>\n'
    blocks.append(b"--" + outer + b"\r\n" + _part(
        [("Content-Type", 'text/xml; charset="utf8"'),
         ("Content-Length", len(item)),
         ("Content-Description", "ItemHeaderTag")], item))
    for index, image in enumerate(images):
        endian = header_kwargs.get("endian", "little")
        raw = np.asarray(image).astype(">u2" if endian == "big" else "<u2")
        data = raw.tobytes()
        header = _image_header(raw.shape[1], raw.shape[0], **header_kwargs)
        inner = f"20261005-125845-INNER{index:04d}".encode()
        nested = (b"--" + inner + b"\r\n" + _part(
            [("Content-Type", "application/octet-stream"),
             ("Content-Length", len(data)),
             ("Content-Description", "ImageData")], data)
            + b"--" + inner + b"\r\n" + _part(
            [("Content-Type", 'text/xml; charset="utf8"'),
             ("Content-Length", len(header)),
             ("Content-Description", "ImageHeader")], header)
            + b"--" + inner + b"--\r\n")
        blocks.append(b"--" + outer + b"\r\n" + _part(
            [("Content-Type", f'multipart/mixed; boundary="{inner.decode()}"'),
             ("Content-Description", f"ScanImageTag{index}")], nested))
    proto = b"<!DOCTYPE XML>\n<root/>\n"
    blocks.append(b"--" + outer + b"\r\n" + _part(
        [("Content-Type", 'text/xml; charset="utf8"'),
         ("Content-Length", len(proto)),
         ("Content-Description", "ItemProtocolSettingsTag")], proto))
    blocks.append(b"--" + outer + b"--\r\n")
    Path(path).write_bytes(b"".join(blocks))
    return Path(path)


def _ramp(height=6, width=8, top=4095):
    return (np.arange(height * width, dtype=np.uint32).reshape(height, width)
            * top // (height * width - 1)).astype(np.uint16)


@pytest.mark.parametrize("height_first", [False, True])
def test_reads_white_zero_data_inverted_with_metadata(tmp_path, height_first):
    raw = _ramp()
    path = write_scn(tmp_path / "plate.scn", [raw], height_first=height_first)
    image, meta = read_scn(path)
    assert image.dtype == np.uint16 and image.shape == (6, 8)
    np.testing.assert_array_equal(image, 4095 - raw)
    assert meta["width"] == 8 and meta["height"] == 6
    assert meta["inverted"] is True and meta["data_ceiling"] == 4095
    assert meta["pixel_size_mm"] == pytest.approx((130.777 / 8, 97.7071 / 6))
    mean_mm = (130.777 / 8 + 97.7071 / 6) / 2
    assert meta["pixels_per_um"] == pytest.approx(1 / (1000 * mean_mm))
    assert meta["imager"] == "Gel Doc™ XR+"
    assert meta["image_date"] == "2026-10-05T12:58:31"
    assert meta["exposure_time"] == pytest.approx(0.168)
    assert meta["application"] == "Coomassie Blue"
    assert meta["excitation_source"] == "White Trans Illumination"
    assert meta["n_images"] == 1


def test_non_square_shape_is_height_by_width_in_both_orders(tmp_path):
    raw = _ramp(height=3, width=11)
    for flag in (False, True):
        path = write_scn(tmp_path / f"o{flag}.scn", [raw], height_first=flag)
        image, _ = read_scn(path)
        np.testing.assert_array_equal(image, 4095 - raw)


def test_big_endian_black_zero_and_missing_size(tmp_path):
    raw = _ramp(top=60000)
    path = write_scn(tmp_path / "big.scn", [raw], endian="big",
                     zero_is="black", ceiling=65535, size_mm=None)
    image, meta = read_scn(path)
    np.testing.assert_array_equal(image, raw)
    assert meta["endian"] == "big" and meta["inverted"] is False
    assert meta["pixel_size_mm"] is None and meta["pixels_per_um"] is None


def test_unknown_physical_size_gives_no_scale(tmp_path):
    path = write_scn(tmp_path / "u.scn", [_ramp()], known="false")
    assert read_scn(path)[1]["pixels_per_um"] is None


def test_multi_image_index_and_stack(tmp_path):
    first, second = _ramp(), _ramp()[::-1].copy()
    path = write_scn(tmp_path / "multi.scn", [first, second])
    np.testing.assert_array_equal(read_scn(path, 1)[0], 4095 - second)
    stack, meta = read_scn(path, None)
    assert stack.shape == (2, 6, 8) and meta["n_images"] == 2
    np.testing.assert_array_equal(stack[0], 4095 - first)
    with pytest.raises(IndexError):
        read_scn(path, 2)


def test_not_an_scn_file_is_refused(tmp_path):
    bogus = tmp_path / "bogus.scn"
    bogus.write_bytes(b"\x00" * 64)
    with pytest.raises(ValueError):
        read_scn(bogus)


def test_truncated_pixel_data_is_refused(tmp_path):
    path = write_scn(tmp_path / "t.scn", [_ramp()])
    data = path.read_bytes().replace(b"Content-Length: 96\r\n",
                                     b"Content-Length: 90\r\n", 1)
    path.write_bytes(data)
    with pytest.raises(ValueError):
        read_scn(path)


def test_rgb8_rendering_is_linear_to_ceiling(tmp_path):
    raw = np.array([[4095, 0], [2048, 4095]], dtype=np.uint16)
    image, meta = read_scn(write_scn(tmp_path / "r.scn", [raw]))
    rgb = scn_to_rgb8(image, meta)
    assert rgb.shape == (2, 2, 3) and rgb.dtype == np.uint8
    np.testing.assert_array_equal(rgb[..., 0], [[0, 255], [127, 0]])


def test_converter_scans_and_converts_scn(tmp_path):
    from spacr import convert as cv
    import tifffile

    src = tmp_path / "run1"
    src.mkdir()
    raw = _ramp()
    write_scn(src / "plate_A01.scn", [raw])
    assert ".scn" in cv.IMAGE_EXTENSIONS
    sources = cv.scan(str(src))
    assert len(sources) == 1 and sources[0].ext == ".scn"
    conversion = cv.plan(sources)
    result = cv.convert(conversion, str(tmp_path / "out"))
    written = sorted((tmp_path / "out").glob("*.tif"))
    assert len(written) == 1, result
    np.testing.assert_array_equal(tifffile.imread(written[0]), 4095 - raw)


def test_plaque_figure_mode_reads_scn_and_its_scale(tmp_path):
    from spacr import plaque_papers as pp

    path = write_scn(tmp_path / "plate.scn", [_ramp()])
    assert ".scn" in pp.IMAGE_SUFFIXES
    figures = pp.figures_in_folder(tmp_path)
    assert [f.path.name for f in figures] == ["plate.scn"]
    rgb = pp._load_image(path)
    assert rgb.shape == (6, 8, 3) and rgb.dtype == np.uint8
    assert pp._image_pixels_per_um(path) == pytest.approx(
        read_scn(path)[1]["pixels_per_um"])
    assert pp._image_pixels_per_um(tmp_path / "x.png") is None


def test_image_metadata_scale_sits_between_settings_and_rulers():
    from spacr import plaque_papers as pp

    region = pp.Region(x0=0, y0=0, x1=50, y1=50)
    image = np.zeros((60, 60, 3), dtype=np.uint8)
    scales = pp._scales_for_regions(image, [region], [],
                                    image_pixels_per_um=0.01)
    assert scales[0].source == "image metadata"
    assert scales[0].px_per_mm == pytest.approx(10.0)
    scales = pp._scales_for_regions(image, [region], [], pixels_per_um=0.02,
                                    image_pixels_per_um=0.01)
    assert scales[0].source == "settings"


def test_make_masks_and_curation_queue_list_and_load_scn(tmp_path):
    from spacr import curation_queue as cq
    from spacr.qt import mask_engine as me

    raw = _ramp()
    write_scn(tmp_path / "field.scn", [raw])
    assert me.IMAGE_EXTS == cq.IMAGE_EXTS and ".scn" in me.IMAGE_EXTS
    assert me.list_images(str(tmp_path)) == ["field.scn"]
    image, mask = me.load_image_and_mask(str(tmp_path), "field.scn")
    np.testing.assert_array_equal(image, 4095 - raw)
    assert mask.shape == raw.shape and not mask.any()
    assert cq._find_mask(tmp_path, "field") is None


def test_standard_plaque_mode_reads_scn(tmp_path):
    pytest.importorskip("cellpose")
    from spacr import submodules as sm

    path = write_scn(tmp_path / "plate.scn", [_ramp()])
    assert "plate.scn".endswith(sm._PLAQUE_IMAGE_SUFFIXES)
    rgb = sm._plaque_imread(str(path))
    assert rgb.shape == (6, 8, 3) and rgb.dtype == np.uint8


def test_channel_sort_rewrites_scn_as_tiff(tmp_path):
    from spacr import channel_sorting as cs

    raw = _ramp()
    path = write_scn(tmp_path / "x.scn", [raw])
    assert cs.image_shape(str(path)) == (6, 8)
    assert cs.thumbnail(str(path)) is not None
    np.testing.assert_array_equal(cs._convert_plane(raw, "scn"), raw)


def _write_scn_validation_document(path, scans, *, newline=b"\r\n",
                                   trailing=b""):
    outer = b"SCN_VALIDATION_OUTER"
    blocks = [newline.join((
        b"MIME-Version: 1.0",
        b'Content-Type: multipart/mixed; boundary="' + outer + b'"',
        b"", b""))]
    for index, (pixels, header, options) in enumerate(scans):
        inner = f"SCN_VALIDATION_INNER_{index}".encode()
        content_type = (b'multipart/mixed; boundary="' + inner + b'"'
                        if options.get("boundary", True)
                        else b"multipart/mixed")
        blocks.append(b"--" + outer + newline + newline.join((
            b"Content-Type: " + content_type,
            b"Content-Description: ScanImageTag" +
            str(options.get("suffix", index)).encode(), b"", b"")))
        parts = [(b"ImageData", pixels), (b"ImageHeader", header)]
        if options.get("extra"):
            parts.append((b"ImageDisplaySettings", b"<display/>"))
        for label, body in parts:
            if label == options.get("omit"):
                continue
            fields = [b"Content-Description: " + label]
            if options.get("lengths", True):
                fields.append(b"Content-Length: " + str(len(body)).encode())
            blocks.append(b"--" + inner + newline +
                          newline.join(fields) + newline * 2 + body + newline)
        blocks.append(b"--" + inner + b"--" + newline)
    blocks.append(trailing + b"--" + outer + b"--" + newline)
    path.write_bytes(b"".join(blocks))
    return path


@pytest.mark.parametrize("newline", [b"\r\n", b"\n"])
@pytest.mark.parametrize("lengths", [False, True])
def test_scn_mime_newlines_and_optional_lengths_preserve_pixels(
        tmp_path, newline, lengths):
    raw = np.array([[1, 200, 301], [17, 55, 12]], dtype="<u2")
    header = _image_header(3, 2, zero_is="black")
    path = _write_scn_validation_document(
        tmp_path / "mime.scn", [(raw.tobytes(), header, {"lengths": lengths})],
        newline=newline)
    original = path.read_bytes()
    image, meta = read_scn(path)
    np.testing.assert_array_equal(image, raw)
    assert meta["n_images"] == 1 and meta["endian"] == "little"
    assert path.read_bytes() == original


@pytest.mark.parametrize("endian", ["big", None])
def test_scn_malformed_xml_uses_available_attributes_without_inventing_metadata(
        tmp_path, endian):
    raw = np.array([[1, 128], [300, 11]], dtype="<u2")
    byte_order = ">u2" if endian == "big" else "<u2"
    header = (b'<root><size_pix height="2" width="2"/>'
              b'<scanner max_value="1023"/><image zero_is="white"/>')
    if endian:
        header += b"<endian>big</endian>"
    path = _write_scn_validation_document(
        tmp_path / "xml.scn", [(raw.astype(byte_order).tobytes(), header, {})])
    original = path.read_bytes()
    image, meta = read_scn(path)
    np.testing.assert_array_equal(image, 1023 - raw)
    assert meta["endian"] == (endian or "little")
    assert meta["data_ceiling"] == 1023
    assert meta["pixel_size_mm"] is None and meta["pixels_per_um"] is None
    assert "imager" not in meta and "exposure_time" not in meta
    assert path.read_bytes() == original


@pytest.mark.parametrize("scanner, ceiling", [
    (b'<scanner max_value="1000"/>', 1000),
    (b'<scanner data_ceiling="nan" max_value="1000"/>', 1000),
    (b"", 301),
    (b'<scanner data_ceiling="0" max_value="0"/>', 301),
])
def test_scn_missing_or_invalid_ceiling_uses_documented_fallback(
        tmp_path, scanner, ceiling):
    raw = np.array([[1, 200, 301], [17, 55, 12]], dtype="<u2")
    header = b'<root><size_pix width="3" height="2"/>' + scanner + b"</root>"
    path = _write_scn_validation_document(
        tmp_path / "ceiling.scn", [(raw.tobytes(), header, {})])
    image, meta = read_scn(path)
    np.testing.assert_array_equal(image, raw)
    assert meta["data_ceiling"] == ceiling
    assert meta["zero_is"] == "black" and not meta["inverted"]


@pytest.mark.parametrize("header", [
    b"<root/>",
    b'<root><size_pix height="2"/></root>',
    b'<root><size_pix width="0" height="2"/></root>',
    b'<root><size_pix width="nan" height="2"/></root>',
    b'<root><size_pix height="2"/>',
])
def test_scn_missing_or_invalid_pixel_dimensions_are_refused(tmp_path, header):
    path = _write_scn_validation_document(
        tmp_path / "size.scn", [(b"\0" * 8, header, {})])
    original = path.read_bytes()
    with pytest.raises(ValueError, match="no size_pix width/height"):
        read_scn(path)
    assert path.read_bytes() == original


@pytest.mark.parametrize("options", [
    {"boundary": False}, {"omit": b"ImageData"}, {"omit": b"ImageHeader"},
])
def test_scn_incomplete_scan_is_refused_by_reader_and_describer(tmp_path, options):
    from spacr.convert import ConfigurationError, _describe_scn

    path = _write_scn_validation_document(
        tmp_path / "missing.scn", [(b"\0" * 8, _image_header(2, 2), options)])
    with pytest.raises(ValueError, match="no ScanImageTag image"):
        read_scn(path)
    with pytest.raises(ConfigurationError, match="contains no images"):
        _describe_scn(str(path))


def test_scn_truncated_mime_header_has_no_image(tmp_path):
    path = tmp_path / "truncated.scn"
    path.write_bytes(b'MIME-Version: 1.0\r\nContent-Type: multipart/mixed; '
                     b'boundary="outer"\r\n\r\n--outer\r\n'
                     b"Content-Description: ScanImageTag0")
    with pytest.raises(ValueError, match="no ScanImageTag image"):
        read_scn(path)


def test_scn_declared_multipart_without_parts_has_no_image(tmp_path):
    path = tmp_path / "no-parts.scn"
    path.write_bytes(b'MIME-Version: 1.0\nContent-Type: multipart/mixed; '
                     b'boundary="outer"\n\n')
    with pytest.raises(ValueError, match="no ScanImageTag image"):
        read_scn(path)


def test_scn_unknown_image_part_does_not_change_pixel_data(tmp_path):
    raw = np.array([[23, 44], [200, 30]], dtype="<u2")
    path = _write_scn_validation_document(
        tmp_path / "display.scn",
        [(raw.tobytes(), _image_header(2, 2), {"extra": True})])
    image, meta = read_scn(path)
    np.testing.assert_array_equal(image, 4095 - raw)
    assert meta["n_images"] == 1


def test_scn_unequal_scans_remain_individually_readable(tmp_path):
    first, second = _ramp(2, 3), _ramp(4, 5)
    path = write_scn(tmp_path / "sizes.scn", [first, second])
    original = path.read_bytes()
    with pytest.raises(ValueError, match="different sizes.*cannot be stacked"):
        read_scn(path, None)
    np.testing.assert_array_equal(read_scn(path, 0)[0], 4095 - first)
    np.testing.assert_array_equal(read_scn(path, -1)[0], 4095 - second)
    assert path.read_bytes() == original


@pytest.mark.skipif(not glob.glob(REAL_SCN_GLOB),
                    reason="real Gel Doc .scn files are not on this machine")
def test_real_gel_doc_file_reads():
    path = sorted(glob.glob(REAL_SCN_GLOB))[0]
    size = os.path.getsize(path)
    image, meta = read_scn(path)
    assert image.shape == (1040, 1392) and image.dtype == np.uint16
    assert size > image.nbytes
    assert meta["inverted"] and 0 < meta["pixels_per_um"] < 1
    assert "Gel Doc" in meta.get("imager", "")
    assert int(image.max()) <= meta["data_ceiling"]
