"""Contracts for readable, API-synchronized spaCR notebooks.

Notebook users do not have a graphical settings panel beside the analysis.
The generated Markdown therefore defines every exposed setting, while the
adjacent code cells organize editable values by scientific purpose and state
whether each value is required, conditionally required, or optional.
"""
from __future__ import annotations

import ast
import importlib.util
import json
import os
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
NOTEBOOKS = REPO / "Notebooks"
TOOL = REPO / "tools" / "build_notebook_settings.py"


def _tool():
    spec = importlib.util.spec_from_file_location("_nb_settings", TOOL)
    module = importlib.util.module_from_spec(spec)
    sys.modules["_nb_settings"] = module
    spec.loader.exec_module(module)
    return module


pytestmark = pytest.mark.skipif(
    not TOOL.exists() or not NOTEBOOKS.is_dir(),
    reason="run from a source checkout")

ALL = sorted(NOTEBOOKS.glob("*.ipynb")) if NOTEBOOKS.is_dir() else []


# ---------------------------------------------------------------------------
# The drift guard
# ---------------------------------------------------------------------------

def test_the_committed_notebooks_match_what_the_tool_generates():
    """Regenerate and compare. This is the whole instruction, enforced.

    If this fails, run::

        python tools/build_notebook_settings.py

    RUN AS A SUBPROCESS, and that is not incidental. spaCR's settings are
    assembled by IMPORT -- modules merge their keys and tooltips into the
    shared dicts from their own module bodies -- so both what a factory
    returns and which text a contested key carries depend on what the process
    has loaded. ``dst`` is registered by surrogate, hit_investigation AND
    sequencing_qc, and ``importlib.import_module`` is a no-op for a module
    already imported, so nothing can re-run a registration to make itself
    last.

    Generating INSIDE pytest therefore answered a different question from
    generating in the tool: the tool was idempotent -- a second run rewrote
    nothing -- while this test still called three notebooks stale. A guard
    that cannot be believed and cannot be silenced is worse than none.

    A subprocess asks the tool the same question a developer asks it.
    """
    import subprocess

    env = {key: value for key, value in os.environ.items()
           if not key.startswith("SPACR_")}
    env["PYTHONPATH"] = str(REPO)
    result = subprocess.run(
        [sys.executable, str(TOOL), "--check"],
        cwd=str(REPO), env=env, capture_output=True, text=True)
    assert result.returncode == 0, result.stdout + result.stderr


def test_shared_tooltips_do_not_depend_on_optional_module_imports():
    tool = _tool()
    expected = tool.CORE_TOOLTIPS["dst"]
    tool._load_registrations()
    assert tool.tooltip_for("dst", "factory", {}) == expected


def test_signature_docs_accept_scientific_python_parameter_sections():
    """Notebook comments follow the API writer's numpydoc convention."""
    tool = _tool()

    def example(first, second=True):
        """Example.

        Parameters
        ----------
        first : str
            Input table path.
        second : bool, optional
            Draw the result when true.

        Returns
        -------
        object
            The result.
        """

    assert tool.param_docs(example) == {
        "first": "Input table path.",
        "second": "Draw the result when true.",
    }


def test_every_notebook_has_a_settings_surface():
    """A notebook whose function nobody can enumerate is the defect itself."""
    tool = _tool()
    without = []
    for path in ALL:
        notebook = json.loads(path.read_text())
        declared = tool.declared_functions(notebook)
        if not declared:
            without.append(f"{path.name}: names no function")
            continue
        if not any(tool.surface(tool.resolve(d), d)[1]
                   for d in declared if tool.resolve(d)):
            without.append(f"{path.name}: {declared} declare no settings")
    assert not without, without


# ---------------------------------------------------------------------------
# What the generated cell has to contain
# ---------------------------------------------------------------------------

def _generated(path):
    notebook = json.loads(path.read_text())
    for cell in notebook["cells"]:
        source = "".join(cell["source"])
        kind = cell.get("metadata", {}).get("spacr", {}).get("generated")
        if cell["cell_type"] == "code" and (
                kind == "settings" or source.startswith(
                    "# Generated by tools/build_notebook_settings.py")):
            return source
    return ""


def _generated_settings_cells(path):
    """Return all generated settings cells in execution order."""
    notebook = json.loads(path.read_text())
    return [
        "".join(cell["source"])
        for cell in notebook["cells"]
        if cell["cell_type"] == "code"
        and cell.get("metadata", {}).get("spacr", {}).get("generated")
        in {"settings", "settings-organelle"}
    ]


def _generated_help(path):
    notebook = json.loads(path.read_text())
    for cell in notebook["cells"]:
        kind = cell.get("metadata", {}).get("spacr", {}).get("generated")
        if cell["cell_type"] == "markdown" and kind == "settings-help":
            return "".join(cell["source"])
    return ""


@pytest.mark.parametrize("path", ALL, ids=lambda p: p.stem)
def test_the_generated_cell_is_valid_python(path):
    sources = _generated_settings_cells(path)
    if not sources:
        pytest.skip("no generated cell")
    for source in sources:
        tree = ast.parse(source)
        assert tree.body, "the generated cell has no statements"


@pytest.mark.parametrize("path", ALL, ids=lambda p: p.stem)
def test_every_key_carries_a_description(path):
    """Every code-cell key is explained in the adjacent Markdown cell."""
    sources = _generated_settings_cells(path)
    if not sources:
        pytest.skip("no generated cell")
    help_text = _generated_help(path)
    keys = []
    for source in sources:
        tree = ast.parse(source)
        for statement in tree.body:
            value = statement.value if isinstance(statement, ast.Assign) else None
            if (isinstance(statement, ast.Expr)
                    and isinstance(statement.value, ast.Call)
                    and statement.value.args):
                value = statement.value.args[0]
            if not isinstance(value, ast.Dict):
                continue
            keys.extend(key.value for key in value.keys
                        if isinstance(key, ast.Constant)
                        and isinstance(key.value, str))
    undescribed = [key for key in keys if f"**`{key}`**" not in help_text]
    assert not undescribed, f"{path.name}: no description for {undescribed}"


@pytest.mark.parametrize("path", ALL, ids=lambda p: p.stem)
def test_explanations_settings_and_call_are_consecutive_cells(path):
    """Readers meet prose, categorized values, and execution in that order."""
    notebook = json.loads(path.read_text())
    cells = notebook["cells"]
    help_index = next((i for i, cell in enumerate(cells)
                       if cell.get("metadata", {}).get("spacr", {}).get(
                           "generated") == "settings-help"), None)
    assert help_index is not None, f"{path.name}: no generated Markdown help"
    assert cells[help_index]["cell_type"] == "markdown"
    assert cells[help_index + 1]["cell_type"] == "code"
    assert cells[help_index + 1].get("metadata", {}).get("spacr", {}).get(
        "generated") == "settings"
    cursor = help_index + 1
    settings_cells = []
    while cursor < len(cells) and cells[cursor].get(
            "metadata", {}).get("spacr", {}).get("generated") in {
                "settings", "settings-organelle"}:
        assert cells[cursor]["cell_type"] == "code"
        settings_cells.append(cells[cursor])
        cursor += 1
    assert settings_cells
    assert cells[cursor]["cell_type"] == "code", (
        f"{path.name}: function call does not follow its settings")

    for settings_cell in settings_cells:
        source = "".join(settings_cell["source"])
        statuses = {
            "# Required settings",
            "# Conditionally required settings",
            "# Optional settings",
        }
        category_lines = [line for line in source.splitlines()
                          if line.startswith("    # ")
                          and line.strip() not in statuses]
        status_lines = [line for line in source.splitlines()
                        if line.strip() in statuses]
        assert category_lines, f"{path.name}: settings have no categories"
        assert status_lines, f"{path.name}: requirement status is absent"


@pytest.mark.parametrize("path", ALL, ids=lambda p: p.stem)
def test_each_reference_links_to_the_callable_api(path):
    tool = _tool()
    notebook = json.loads(path.read_text())
    help_text = _generated_help(path)
    for dotted in tool.declared_functions(notebook):
        assert f"[`{dotted}`]({tool.api_url(dotted)})" in help_text


@pytest.mark.parametrize("path", ALL, ids=lambda p: p.stem)
def test_every_documented_setting_states_its_requirement_status(path):
    help_text = _generated_help(path)
    for line in help_text.splitlines():
        if line.startswith("- **`"):
            assert any(f"*({status})*" in line for status in (
                "required", "conditionally required", "optional")), (
                    f"{path.name}: missing requirement status: {line}")


def test_mask_workflows_are_separate_and_scientifically_described():
    expected = {
        "01_generate_masks.ipynb": [
            "spacr.core.preprocess_generate_masks",
        ],
        "01b_generate_timelapse_masks.ipynb": [
            "spacr.core.preprocess_generate_masks_timelapse",
        ],
        "14_motility_assay.ipynb": [
            "spacr.core.preprocess_generate_masks_timelapse",
            "spacr.timelapse.automated_motility_assay",
        ],
    }
    tool = _tool()
    for name, functions in expected.items():
        path = NOTEBOOKS / name
        notebook = json.loads(path.read_text())
        assert tool.declared_functions(notebook) == functions

    mask = json.loads((NOTEBOOKS / "01_generate_masks.ipynb").read_text())
    overview = "".join(mask["cells"][0]["source"])
    assert "Generate per-object masks" in overview
    assert all(object_name in overview for object_name in (
        "cells", "nuclei", "pathogens", "organelles"))
    assert "Turn raw" not in overview

    motility_cells = _generated_settings_cells(
        NOTEBOOKS / "14_motility_assay.ipynb")
    assert "'src': preprocess_generate_masks_timelapse_settings['src']" in (
        motility_cells[0])


@pytest.mark.parametrize("name", [
    "01_generate_masks.ipynb",
    "01b_generate_timelapse_masks.ipynb",
    "14_motility_assay.ipynb",
])
def test_organelle_settings_have_a_separate_cell(name):
    cells = json.loads((NOTEBOOKS / name).read_text())["cells"]
    general = next(cell for cell in cells
                   if cell.get("metadata", {}).get("spacr", {}).get(
                       "generated") == "settings")
    organelle = next(cell for cell in cells
                     if cell.get("metadata", {}).get("spacr", {}).get(
                         "generated") == "settings-organelle")
    general_source = "".join(general["source"])
    organelle_source = "".join(organelle["source"])
    assert "'organelle_channel'" not in general_source
    assert "'organelle_channel'" in organelle_source
    assert ".update({" in organelle_source


@pytest.mark.parametrize("path", ALL, ids=lambda p: p.stem)
def test_notebook_overviews_use_scientific_section_labels(path):
    notebook = json.loads(path.read_text())
    overview = "".join(notebook["cells"][0]["source"])
    assert "**Purpose.**" in overview
    assert "**Recommended use.**" in overview
    assert "**Primary outputs.**" in overview
    assert "**What it does.**" not in overview
    assert "**What you get.**" not in overview


@pytest.mark.parametrize("path", ALL, ids=lambda p: p.stem)
def test_the_settings_dict_is_used_rather_than_decorative(path):
    """The dict has to BE the call's arguments, not sit beside them.

    Eight notebooks used to carry a commented-out call restating the whole
    signature by hand -- a second paste, and one a renamed parameter would
    have left silently wrong.
    """
    source = _generated(path)
    if not source:
        pytest.skip("no generated cell")
    notebook = json.loads(path.read_text())
    names = [n for n in ("settings",) if f"{n} = {{" in source]
    if not names:
        pytest.skip("multi-function notebook names its dicts per function")
    code = "\n".join("".join(c["source"]) for c in notebook["cells"]
                     if c["cell_type"] == "code" and not
                     "".join(c["source"]).startswith("# Generated"))
    assert "settings)" in code or "**settings" in code, (
        f"{path.name}: the generated dict is never passed to anything")


# ---------------------------------------------------------------------------
# The tool's own rules
# ---------------------------------------------------------------------------

def test_tooltips_are_read_now_and_never_pasted():
    """Tooltip prose comes from the public source rather than a stale copy."""
    source = TOOL.read_text()
    assert "from spacr.settings import tooltips" in source or \
           "spacr.settings import tooltips" in source


def test_the_registry_is_reused_rather_than_a_third_mapping():
    """Rule 1: the GUI and CLI already map module to defaults helper."""
    assert "from spacr.cli import MODULES" in TOOL.read_text()


def test_a_factoryless_function_says_where_its_keys_came_from():
    """Four functions read settings.get() inline and declare nothing.

    A list recovered from a function body is a weaker claim than one read
    off a declaration; printing them identically would hide that.
    """
    tool = _tool()
    entries = [("spacr.submodules.count_phenotypes", "source",
                {"src": None}, {})]
    rendered = tool.render_help(entries)
    assert "does not yet expose a settings factory" in rendered


def test_an_unrepresentable_default_is_flagged_not_silently_wrong():
    """A default that does not round-trip must not be written as if it did."""
    tool = _tool()

    class Odd:
        pass

    rendered = tool.render_cell([("spacr.x.y", "signature", {"k": Odd()}, {})])
    assert "set this yourself" in rendered
    ast.parse(rendered)


def test_bundled_resource_defaults_are_portable(monkeypatch):
    """Generated notebooks must not contain the checkout that built them."""
    import spacr

    tool = _tool()
    resource = REPO / "spacr" / "resources" / "data" / "barcodes_row.csv"
    rendered = tool._literal(str(resource))
    assert str(REPO) not in rendered
    assert "__path__" in rendered
    # Editable Python 3.9 installs can expose this state; the old
    # importlib.resources expression crashed while resolving ``spec.origin``.
    monkeypatch.setattr(spacr, "__spec__", None)
    assert eval(rendered) == str(resource.resolve())


@pytest.mark.parametrize("dotted", [
    "spacr.core.preprocess_generate_masks",
    "spacr.core.preprocess_generate_masks_timelapse",
])
def test_machine_sized_worker_defaults_are_rendered_as_expressions(dotted):
    """A notebook generated on CI must match one generated on a workstation."""
    tool = _tool()
    workstation = tool._literal(28, dotted=dotted, key="n_jobs")
    hosted_runner = tool._literal(1, dotted=dotted, key="n_jobs")

    assert workstation == hosted_runner
    assert "cpu_count" in workstation
    assert eval(workstation) >= 1


def test_check_mode_is_what_the_drift_guard_calls():
    """--check is the contract; the guard above runs it as a subprocess."""
    source = TOOL.read_text()
    assert '"--check"' in source or "'--check'" in source
