"""Phase F — v1 vs v2 mask parity test.

Verifies that the streaming ``spacr.pipeline_v2`` produces per-object
masks equivalent (up to instance-label permutation) to the classic
``spacr.core.preprocess_generate_masks`` pipeline on the same input.

The parity check runs on a **small synthetic dataset** generated by
:func:`spacr.qt.synthetic.generate_mask_demo`, so the test doesn't
depend on any real microscopy data. Cellpose is still required — the
test skips cleanly when Cellpose isn't installed or a CUDA device is
unavailable, since CPU Cellpose on any non-trivial image would push
this test well past the 30-minute mark.

Marked ``@pytest.mark.slow`` + ``@pytest.mark.gpu`` so it only runs
under ``pytest -m "slow and gpu"``. Wall-clock on a GPU box: 3–6
minutes for the full comparison.

Similarity metric
-----------------

We compare masks with the **Adjusted Rand Index** computed over
matched foreground pixels. Two mask images can differ in absolute
label values (v1 → 5, v2 → 12 for the same cell) yet be equivalent as
partitions of the pixel plane. ARI is 1.0 for identical partitions
regardless of label numbering, and ~0 for unrelated partitions —
exactly the right shape for parity.

Threshold: 0.85. This tolerates the tiny per-pixel differences that
sometimes creep in from batching / RNG in Cellpose while still failing
loudly on any real regression.
"""
from __future__ import annotations

import shutil
import time
from pathlib import Path
from typing import List

import numpy as np
import pytest

# ---------------------------------------------------------------------------
# Guards — skip cleanly when the heavy deps aren't around
# ---------------------------------------------------------------------------

def _require_gpu_cellpose():
    try:
        import torch                          # noqa: F401
    except Exception as e:
        pytest.skip(f"torch unavailable: {e}")
    if not torch.cuda.is_available():
        pytest.skip("no CUDA device — this parity test is GPU-only")
    try:
        import cellpose                       # noqa: F401
    except Exception as e:
        pytest.skip(f"cellpose unavailable: {e}")
    try:
        import sklearn                        # noqa: F401
    except Exception as e:
        pytest.skip(f"scikit-learn unavailable (needed for ARI): {e}")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _collect_v1_cell_masks(root: Path) -> List[np.ndarray]:
    """Return every 2-D v1 cell mask under ``masks/cell_mask_stack``.

    v1 writes one ``.npy`` per field; each is a 2-D label array where
    every distinct positive integer is one cell.
    """
    stack_dir = root / "masks" / "cell_mask_stack"
    out: List[np.ndarray] = []
    if not stack_dir.is_dir():
        return out
    for p in sorted(stack_dir.glob("*.npy")):
        arr = np.load(p)
        if arr.ndim == 3:
            arr = arr[0]
        out.append(arr.astype(np.int32))
    return out


def _collect_v2_cell_masks(root: Path) -> List[np.ndarray]:
    """Return every 2-D v2 cell mask under ``merged/stack_*.npy``.

    v2 appends the cell mask as the LAST channel of each per-field
    ``.npy`` stack. We fish it out and coerce to a 2-D label array.
    """
    stack_dir = root / "merged"
    out: List[np.ndarray] = []
    if not stack_dir.is_dir():
        return out
    for p in sorted(stack_dir.glob("stack_*.npy")):
        arr = np.load(p)
        if arr.ndim != 3 or arr.shape[-1] < 2:
            continue
        # Assume the mask is the last-appended channel
        out.append(arr[..., -1].astype(np.int32))
    return out


def _adjusted_rand_over_union(m1: np.ndarray, m2: np.ndarray) -> float:
    """ARI computed on the union of foreground pixels.

    We restrict to pixels labelled by *either* mask because pure
    background dominates otherwise and inflates similarity even when
    the segmentations disagree. Returns 1.0 for identical partitions
    (up to label renumbering) and ~0 for unrelated ones.
    """
    from sklearn.metrics import adjusted_rand_score
    m1 = m1.astype(np.int32); m2 = m2.astype(np.int32)
    if m1.shape != m2.shape:
        # Different image dimensions can happen if v1/v2 crop
        # differently — resize v2 to v1's shape for the ARI compute.
        from PIL import Image
        m2 = np.asarray(
            Image.fromarray(m2, mode="I").resize(
                (m1.shape[1], m1.shape[0]),
                resample=Image.NEAREST),
            dtype=np.int32,
        )
    mask = (m1 > 0) | (m2 > 0)
    if not mask.any():
        return 1.0
    return float(adjusted_rand_score(m1[mask].ravel(), m2[mask].ravel()))


# ---------------------------------------------------------------------------
# Fixture — one synthetic dataset copied twice so v1 and v2 don't fight
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def _synthetic_pair(tmp_path_factory):
    _require_gpu_cellpose()
    from spacr.qt.synthetic import generate_mask_demo
    root = tmp_path_factory.mktemp("v1v2_parity", numbered=True)
    seed = root / "seed"
    generate_mask_demo(seed)
    v1_dir = root / "v1"; v2_dir = root / "v2"
    shutil.copytree(seed, v1_dir)
    shutil.copytree(seed, v2_dir)
    return v1_dir, v2_dir


# ---------------------------------------------------------------------------
# Parity test proper
# ---------------------------------------------------------------------------

@pytest.mark.slow
@pytest.mark.gpu
@pytest.mark.xfail(
    strict=False,
    reason=(
        "As of 1.4.3.2 v1 and v2 disagree on the synthetic mask demo "
        "(ARI ~0.14-0.48 across fields, differing object counts). "
        "This test is xfailed until the pipelines converge — once they "
        "match at ARI >= 0.85 on every field, xfail flips to XPASS and "
        "the test starts guarding regressions."
    ),
)
def test_v1_v2_mask_parity(_synthetic_pair):
    """End-to-end: run both pipelines on the same input and confirm
    the cell masks agree at ARI >= 0.85 on every field."""
    v1_dir, v2_dir = _synthetic_pair

    # --- v1 -------------------------------------------------------------
    # Use the same minimal-settings helper the smoke test uses so we
    # don't drift from what the pipeline actually accepts.
    from spacr.core import preprocess_generate_masks
    from spacr.qt import synthetic as syn
    v1_settings = syn.demo_settings("mask", str(v1_dir))
    for extra_key, extra_val in {
        "consolidate": False, "remove_background": False, "normalize": True,
        "backgrounds": [100, 100, 100, 100],
        "remove_background_cell": False,
        "remove_background_nucleus": False,
        "remove_background_pathogen": False,
        "cells_per_field": 4,
        "test_mode": False,
        "Signal_to_noise": 10,
        "cell_intensity_range": None,
        "nucleus_intensity_range": None,
        "pathogen_intensity_range": None,
        "cytoplasm_intensity_range": None,
        "denoise": False,
        "remove_background_intensity": False,
        "skip_extraction": False,
    }.items():
        v1_settings.setdefault(extra_key, extra_val)
    v1_settings["plot"] = False
    t0 = time.time()
    preprocess_generate_masks(v1_settings)
    t_v1 = time.time() - t0

    # --- v2 -------------------------------------------------------------
    from spacr.pipeline_v2 import run_v2
    t0 = time.time()
    run_v2(
        src=v2_dir,
        channels=(0, 1, 2, 3),
        model_name="cyto",
        channels_for_cellpose=(0, 1),
        diameter=None,
        batch_fields=4,
        metadata_type="cellvoyager",
    )
    t_v2 = time.time() - t0

    print(f"[parity] v1={t_v1:.1f}s v2={t_v2:.1f}s")

    # --- compare --------------------------------------------------------
    v1_masks = _collect_v1_cell_masks(v1_dir)
    v2_masks = _collect_v2_cell_masks(v2_dir)
    assert v1_masks, "v1 produced no cell masks under masks/cell_mask_stack/"
    assert v2_masks, "v2 produced no merged/stack_*.npy with a mask channel"
    assert len(v1_masks) == len(v2_masks), (
        f"different number of fields — v1={len(v1_masks)}, "
        f"v2={len(v2_masks)}. Filename ordering may have diverged.")

    scores = []
    for i, (m1, m2) in enumerate(zip(v1_masks, v2_masks)):
        ari = _adjusted_rand_over_union(m1, m2)
        scores.append((i, ari))
        print(f"[parity] field {i:03d}  ARI={ari:.3f} "
              f"(v1 objects={int(m1.max())}, v2 objects={int(m2.max())})")

    low = [(i, a) for i, a in scores if a < 0.85]
    assert not low, (
        f"v1/v2 mask disagreement on {len(low)}/{len(scores)} field(s): "
        + "; ".join(f"field {i} ARI={a:.2f}" for i, a in low))
