"""The API documentation's logo carries its own background.

Reported 2026-09-01: "same problem with the white icon on a light
background in the API".

``logo_spacr.png`` is pure white on transparent. Sphinx serves ONE
``html_logo`` for both colour schemes, so against the light theme's white
sidebar the bare mark is a blank space -- the same failure the README had
on GitHub, for the same reason and with the same fix unavailable: there
is no per-scheme image to swap to.

So the docs get their own asset with a dark teal panel behind the mark.
"""
from __future__ import annotations

import pathlib

import pytest

Image = pytest.importorskip("PIL.Image", reason="Pillow not installed")

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOCS_LOGO = ROOT / "docs" / "source" / "_static" / "logo_spacr_docs.png"
BARE_LOGO = ROOT / "docs" / "source" / "_static" / "logo_spacr.png"
CONF = ROOT / "docs" / "source" / "conf.py"


def _load(path):
    from PIL import Image as PILImage
    return PILImage.open(path).convert("RGBA")


def test_the_panelled_logo_exists():
    assert DOCS_LOGO.is_file(), (
        "run packaging/generate_readme_visuals.py to write it")


def test_the_bare_mark_really_is_invisible_on_white():
    """THE PREMISE. Without this the panel is unexplained decoration."""
    image = _load(BARE_LOGO)
    pixels = image.load()
    width, height = image.size
    opaque = white = 0
    for y in range(0, height, 8):
        for x in range(0, width, 8):
            r, _g, _b, a = pixels[x, y]
            if a > 40:
                opaque += 1
                if r > 200:
                    white += 1
    assert opaque, "the bare mark has no opaque pixels at all"
    assert white == opaque, (
        "the bare mark is no longer entirely white, so the reason for a "
        "panel has changed and should be re-examined")


def test_the_docs_logo_has_an_opaque_panel_behind_the_mark():
    image = _load(DOCS_LOGO)
    pixels = image.load()
    width, height = image.size

    # The edge midpoint is panel, never mark.
    r, g, b, a = pixels[6, height // 2]
    assert a == 255, "the panel is not opaque, so the page shows through"
    assert (r, g, b) != (255, 255, 255), "the panel is white"
    assert b > r, f"the panel is not teal: {(r, g, b)}"


def test_the_corners_are_rounded():
    """Asked for as a rounded square; a hard corner is a different shape
    from the one every other spaCR tile uses."""
    image = _load(DOCS_LOGO)
    assert image.getpixel((2, 2))[3] == 0, "the top-left corner is filled"
    w, h = image.size
    assert image.getpixel((w - 3, h - 3))[3] == 0


def test_the_mark_is_still_white_and_still_there():
    """A panel that covered the logo would pass every test above."""
    image = _load(DOCS_LOGO)
    pixels = image.load()
    width, height = image.size
    white = sum(1 for y in range(0, height, 3) for x in range(0, width, 3)
                if pixels[x, y][0] > 200 and pixels[x, y][3] > 200)
    assert white > 100, f"only {white} white pixels; the mark is missing"


def test_it_is_square():
    """Sphinx sidebars give the logo a square slot."""
    image = _load(DOCS_LOGO)
    assert image.width == image.height


def test_sphinx_is_pointed_at_the_panelled_one():
    text = CONF.read_text(encoding="utf-8")
    assert "html_logo       = '_static/logo_spacr_docs.png'" in text


def test_the_favicon_stays_the_bare_mark():
    """DELIBERATE, and worth stating so it is not 'fixed' later.

    A favicon is drawn at 16px against the browser's own tab strip, which
    is dark in both themes on every platform that ships one. At that size
    a panel is mostly panel.
    """
    text = CONF.read_text(encoding="utf-8")
    assert "html_favicon    = '_static/logo_spacr.png'" in text


def test_the_index_page_uses_the_panelled_one_too():
    index = ROOT / "docs" / "source" / "index.rst"
    if not index.is_file():
        pytest.skip("index.rst is generated by setup_docs.sh")
    text = index.read_text(encoding="utf-8")
    if ".. image::" in text and "logo_spacr" in text:
        assert "logo_spacr_docs.png" in text, (
            "the index page still shows the bare white mark")
