"""Every shipped notebook lists every setting, and cannot drift from them.

Instruction 88:

    "make sure that all notebooks contain all settings for the functions
     (at least the main functions) and classes they use, with tooltips for
     each setting"

A notebook is the only route into spaCR that does not go through a settings
panel, so it is the one place a setting can be INVISIBLE rather than merely
badly explained -- a reader sees the six keys the example set and has no way
to learn the function reads ninety.

THE TEST IS THE POINT, not the notebooks. Fourteen of the thirty already
carried a settings block, hand-maintained against a settings dict that moves
every week, and instruction 61 has already rewritten 454 tooltips once. The
regeneration check below is what makes "all settings" true tomorrow as well
as today: add a setting and the notebook has to gain it or CI goes red.
"""
from __future__ import annotations

import ast
import importlib.util
import json
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
NOTEBOOKS = REPO / "Notebooks"
TOOL = REPO / "tools" / "build_notebook_settings.py"


def _tool():
    spec = importlib.util.spec_from_file_location("_nb_settings", TOOL)
    module = importlib.util.module_from_spec(spec)
    sys.modules["_nb_settings"] = module
    spec.loader.exec_module(module)
    return module


pytestmark = pytest.mark.skipif(
    not TOOL.exists() or not NOTEBOOKS.is_dir(),
    reason="run from a source checkout")

ALL = sorted(NOTEBOOKS.glob("*.ipynb")) if NOTEBOOKS.is_dir() else []


# ---------------------------------------------------------------------------
# The drift guard
# ---------------------------------------------------------------------------

def test_the_committed_notebooks_match_what_the_tool_generates():
    """Regenerate and compare. This is the whole instruction, enforced.

    If this fails, run::

        python tools/build_notebook_settings.py

    RUN AS A SUBPROCESS, and that is not incidental. spaCR's settings are
    assembled by IMPORT -- modules merge their keys and tooltips into the
    shared dicts from their own module bodies -- so both what a factory
    returns and which text a contested key carries depend on what the process
    has loaded. ``dst`` is registered by surrogate, hit_investigation AND
    sequencing_qc, and ``importlib.import_module`` is a no-op for a module
    already imported, so nothing can re-run a registration to make itself
    last.

    Generating INSIDE pytest therefore answered a different question from
    generating in the tool: the tool was idempotent -- a second run rewrote
    nothing -- while this test still called three notebooks stale. A guard
    that cannot be believed and cannot be silenced is worse than none.

    A subprocess asks the tool the same question a developer asks it.
    """
    import subprocess

    result = subprocess.run(
        [sys.executable, str(TOOL), "--check"],
        cwd=str(REPO), capture_output=True, text=True)
    assert result.returncode == 0, result.stdout + result.stderr


def test_shared_tooltips_do_not_depend_on_optional_module_imports():
    tool = _tool()
    expected = tool.CORE_TOOLTIPS["dst"]
    tool._load_registrations()
    assert tool.tooltip_for("dst", "factory", {}) == expected


def test_every_notebook_has_a_settings_surface():
    """A notebook whose function nobody can enumerate is the defect itself."""
    tool = _tool()
    without = []
    for path in ALL:
        notebook = json.loads(path.read_text())
        declared = tool.declared_functions(notebook)
        if not declared:
            without.append(f"{path.name}: names no function")
            continue
        if not any(tool.surface(tool.resolve(d), d)[1]
                   for d in declared if tool.resolve(d)):
            without.append(f"{path.name}: {declared} declare no settings")
    assert not without, without


# ---------------------------------------------------------------------------
# What the generated cell has to contain
# ---------------------------------------------------------------------------

def _generated(path):
    notebook = json.loads(path.read_text())
    for cell in notebook["cells"]:
        source = "".join(cell["source"])
        if cell["cell_type"] == "code" and source.startswith(
                "# Generated by tools/build_notebook_settings.py"):
            return source
    return ""


@pytest.mark.parametrize("path", ALL, ids=lambda p: p.stem)
def test_the_generated_cell_is_valid_python(path):
    source = _generated(path)
    if not source:
        pytest.skip("no generated cell")
    # Parsing IS the check -- a cell that cannot run is worse than one that
    # is merely wrong -- but an exception is not an assertion to a reader or
    # to the hygiene scan, so the result is named.
    tree = ast.parse(source)
    assert tree.body, "the generated cell has no statements"


@pytest.mark.parametrize("path", ALL, ids=lambda p: p.stem)
def test_every_key_carries_a_description(path):
    """A key with no tooltip is a key the reader still cannot understand.

    Listing the name alone would satisfy "all settings" and miss the point
    of the request, which is "with tooltips for each setting".
    """
    source = _generated(path)
    if not source:
        pytest.skip("no generated cell")
    lines = source.split("\n")
    undescribed = []
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not (stripped.startswith("'") and "':" in stripped):
            continue
        # Walk back over the wrapped comment block above the key.
        back = index - 1
        while back >= 0 and lines[back].strip().startswith("#"):
            back -= 1
        if back == index - 1:
            undescribed.append(stripped.split("'")[1])
    assert not undescribed, f"{path.name}: no description for {undescribed}"


@pytest.mark.parametrize("path", ALL, ids=lambda p: p.stem)
def test_the_settings_dict_is_used_rather_than_decorative(path):
    """The dict has to BE the call's arguments, not sit beside them.

    Eight notebooks used to carry a commented-out call restating the whole
    signature by hand -- a second paste, and one a renamed parameter would
    have left silently wrong.
    """
    source = _generated(path)
    if not source:
        pytest.skip("no generated cell")
    notebook = json.loads(path.read_text())
    names = [n for n in ("settings",) if f"\n{n} = {{" in source]
    if not names:
        pytest.skip("multi-function notebook names its dicts per function")
    code = "\n".join("".join(c["source"]) for c in notebook["cells"]
                     if c["cell_type"] == "code" and not
                     "".join(c["source"]).startswith("# Generated"))
    assert "settings)" in code or "**settings" in code, (
        f"{path.name}: the generated dict is never passed to anything")


# ---------------------------------------------------------------------------
# The tool's own rules
# ---------------------------------------------------------------------------

def test_tooltips_are_read_now_and_never_pasted():
    """Rule 3 of instruction 88, enforced against the tool's own source.

    A literal tooltip in the generator is the same stale copy the hand-made
    notebooks were, one level up.
    """
    source = TOOL.read_text()
    assert "from spacr.settings import tooltips" in source or \
           "spacr.settings import tooltips" in source


def test_the_registry_is_reused_rather_than_a_third_mapping():
    """Rule 1: the GUI and CLI already map module to defaults helper."""
    assert "from spacr.cli import MODULES" in TOOL.read_text()


def test_a_factoryless_function_says_where_its_keys_came_from():
    """Four functions read settings.get() inline and declare nothing.

    A list recovered from a function body is a weaker claim than one read
    off a declaration; printing them identically would hide that.
    """
    tool = _tool()
    entries = [("spacr.submodules.count_phenotypes", "source",
                {"src": None}, {})]
    rendered = tool.render_cell(entries)
    assert "no settings helper declaring its keys" in rendered


def test_an_unrepresentable_default_is_flagged_not_silently_wrong():
    """A default that does not round-trip must not be written as if it did."""
    tool = _tool()

    class Odd:
        pass

    rendered = tool.render_cell([("spacr.x.y", "signature", {"k": Odd()}, {})])
    assert "set this yourself" in rendered
    ast.parse(rendered)


def test_bundled_resource_defaults_are_portable():
    """Generated notebooks must not contain the checkout that built them."""
    tool = _tool()
    resource = REPO / "spacr" / "resources" / "data" / "barcodes_row.csv"
    rendered = tool._literal(str(resource))
    assert str(REPO) not in rendered
    assert "importlib.resources" in rendered
    assert eval(rendered) == str(resource.resolve())


def test_check_mode_is_what_the_drift_guard_calls():
    """--check is the contract; the guard above runs it as a subprocess."""
    source = TOOL.read_text()
    assert '"--check"' in source or "'--check'" in source
