"""Instruction 178 A: right-click a count figure and pick another plot type.

    "the figures that are generated by spacer for gene count, grna well
    count, cell count and the absolute differenc one all need to look better
    they should all be adapted for dark and white themes and i should be able
    to right click on them and show them as: line, bar, jitter-bar,
    jitter-box, jitter, box, violin plots."

`spacrGraph` could already draw all seven; the count figures were hard-coded
to `jitter_bar` and nothing could ask for another. The missing piece was a
way for the MENU to redraw a figure it only has a reference to -- so the
figure carries its own recipe.
"""
import matplotlib
matplotlib.use("Agg")

import numpy as np
import pandas as pd
import pytest

from spacr.plot import create_grouped_plot
from spacr.qt.widgets.figure_settings import (GROUPED_PLOT_TYPES,
                                              build_figure_context_menu,
                                              _replot)


@pytest.fixture()
def figure(qtbot):
    rng = np.random.default_rng(0)
    n = 60
    frame = pd.DataFrame({"grp": rng.choice(["a", "b"], n),
                          "val": rng.normal(5.0, 1.0, n)})
    fig, _results = create_grouped_plot(frame, "grp", "val",
                                        graph_type="jitter_bar", save=False)
    return fig


def test_all_seven_types_are_offered():
    """Named in the request, in that order."""
    offered = [kind for kind, _label in GROUPED_PLOT_TYPES]

    assert offered == ["line", "bar", "jitter_bar", "jitter_box", "jitter",
                       "box", "violin"]


def test_the_figure_carries_its_own_recipe(figure):
    """The menu has a reference to the FIGURE and nothing else, so the data
    has to travel with it."""
    recipe = getattr(figure, "_spacr_replot", None)

    assert isinstance(recipe, dict)
    assert recipe["grouping_column"] == "grp"
    assert recipe["data_column"] == "val"
    assert len(recipe["df"]) == 60


def test_the_recipe_keeps_the_unaggregated_frame(figure):
    """NOT the summary CSV beside the figure: that is already aggregated to
    whatever level the plot used, so a jitter rebuilt from it would draw the
    means and call them cells."""
    assert len(figure._spacr_replot["df"]) == 60


def test_the_menu_offers_show_as(figure, qtbot):
    menu = build_figure_context_menu(None, figure)

    titles = [a.menu().title() for a in menu.actions() if a.menu()]
    # RENAMED to "Graph type", which is the name it was asked for by.
    assert "Graph type" in titles


def test_the_current_type_is_ticked(figure, qtbot):
    menu = build_figure_context_menu(None, figure)
    show_as = next(a.menu() for a in menu.actions()
                   if a.menu() and a.menu().title() == "Graph type")

    checked = [a.text() for a in show_as.actions() if a.isChecked()]
    assert checked == ["Jitter over bar"]


@pytest.mark.parametrize("kind", [k for k, _l in GROUPED_PLOT_TYPES])
def test_every_type_redraws(figure, kind):
    drawn = _replot(figure, kind)

    assert drawn is not None, kind
    assert drawn.axes, "nothing was drawn"
    assert drawn._spacr_replot["graph_type"] == kind


def test_the_new_figure_carries_the_recipe_forward(figure):
    """So the menu still works on the redrawn figure -- otherwise you could
    switch type exactly once."""
    drawn = _replot(figure, "violin")
    again = _replot(drawn, "box")

    assert again is not None
    assert again._spacr_replot["graph_type"] == "box"


def test_the_caller_is_handed_the_new_figure(figure):
    """`create_grouped_plot` builds its OWN Figure -- spacrGraph makes one --
    so there is nothing to draw in place onto, and the queue has to be told
    which object replaced which."""
    handed = []

    _replot(figure, "box", on_change=handed.append)

    assert len(handed) == 1
    assert handed[0] is not figure
    assert handed[0].axes


def test_a_figure_with_nothing_plottable_gets_no_menu_entry(qtbot):
    """The rule CHANGED, and this is what is left of it.

    It used to be "only a figure carrying a recipe offers this", which meant
    only the figures `create_grouped_plot` draws -- so the entry was absent
    from nearly every plot in spaCR. Asked to put it on all of them, the
    menu now DERIVES a recipe from the artists when there is no recipe (see
    `figure_settings.derive_replot_recipe`).

    What survives is the narrower claim: an entry that cannot redraw its
    figure is still worse than an absent one. A two-point line with no
    marker is a reference line rather than data, the deriver says so, and
    nothing is offered.
    """
    import matplotlib.pyplot as plt

    plain = plt.figure()
    plain.add_subplot(111).plot([0, 1], [1, 0])
    menu = build_figure_context_menu(None, plain)

    titles = [a.menu().title() for a in menu.actions() if a.menu()]
    assert "Graph type" not in titles


def test_a_replot_that_cannot_work_is_not_a_crash(figure):
    """A right-click must never take the application down."""
    figure._spacr_replot = {"df": None}

    assert _replot(figure, "violin") is None


def test_the_change_is_announced(figure):
    """The grid is built from pictures, so it has to be told to rebuild or
    the tile keeps showing the old one and the menu looks broken."""
    told = []

    _replot(figure, "box", on_change=lambda *_a: told.append(1))

    assert told == [1]
