"""Mandelbrot coordinates the backdrop camera tours.

GENERATED by tools/find_mandelbrot_regions.py -- do not hand-edit.
Each entry is a point that keeps a high escape-time gradient across four
decades of zoom, so the camera still has something to show when it
arrives.
"""
from __future__ import annotations

from typing import Final, Tuple

#: ``(name, real, imaginary, deepest_useful_half_width, score)``.
#: The half-width is how far down this point stays interesting;
#: the score is the worst mean escape-time gradient across ZOOMS.
REGIONS: Final[Tuple[Tuple[str, float, float, float, float], ...]] = (
    ("region 01", -0.3739430267245063, 0.6064570528777626, 1e-05, 52.394039),
    ("region 02", -0.5736721042973509, 0.46675978506773097, 1e-05, 40.442497),
    ("region 03", -1.0682963519716877, -0.24413865676951063, 1e-05, 40.119321),
    ("region 04", -0.07905930571568964, 0.6503041284733808, 1e-05, 36.806709),
    ("region 05", -1.2498235389819237, 0.03724993844429991, 1e-05, 31.179895),
    ("region 06", -0.2045916866627584, -0.8160569518185596, 1e-05, 25.132656),
    ("region 07", -1.0365316857520077, 0.2580797936485466, 1e-05, 24.201127),
    ("region 08", -0.1306980598755425, 0.839264022351472, 1e-05, 23.689194),
    ("region 09", -0.03025514289127562, 0.7370883929453065, 1e-05, 23.443242),
    ("region 10", -0.0889239291365258, -0.8650572737496657, 1e-05, 18.804036),
    ("region 11", 0.398639628799923, 0.23194280965469116, 1e-05, 18.344938),
    ("region 12", 0.29421298516462846, 0.46024309847881395, 1e-05, 11.824799),
    ("region 13", 0.1373755661448155, -0.6381327144140291, 1e-05, 10.407882),
    ("region 14", 0.40452263695131885, -0.23225216238687252, 1e-05, 7.47519),
    ("region 15", -0.7354595644900115, 0.2889250409746349, 1e-05, 7.352),
    ("region 16", -0.23801656609003508, -0.6432052218030987, 1e-05, 6.140115),
    ("region 17", -0.28482925220180144, 0.6273788216996548, 1e-05, 5.887801),
    ("region 18", -0.6758502096930386, 0.4335087144443335, 1e-05, 5.433436),
    ("region 19", 0.33553714260980927, 0.5674484793375725, 1e-05, 4.658783),
    ("region 20", -1.2391839447618826, -0.15776602257089656, 1e-05, 4.329949),
)
