"""The twenty regions are on screen, and the tour is wired to the camera.

Instruction 327 item 3 asked for "say 20 regions on the image that the
camera will automatically smoothely float towards". The coordinates were
found, generated by a committed script, stored as named data with a zoom
range, and covered by tests -- and then NOTHING CALLED THEM. The 2026-09-05
audit found it: "(3)'s RegionTour is built and tested and NOTHING CALLS IT.
The pieces are there; the wire is not."

`TourPilot` is the wire, and it is a plain object for the same reason
`SteeringCamera` is one: the GPU canvas needs a GL context to exist, so
logic left inside it can only be argued about, not driven. These tests
drive it frame by frame.
"""

import pytest

from spacr.qt.widgets.fractal_mandelbrot import SteeringCamera
from spacr.qt.widgets.fractal_regions import REGIONS
from spacr.qt.widgets.fractal_travel import RegionTour, _TourPilot as TourPilot


WIDE = 1.0          # a surface-scale view; every region is still about it.
NARROW = 1e-9       # far below the deepest half-width the regions carry.


class TestTheWireExists:

    def test_a_pilot_with_no_tour_flies_the_committed_regions(self):
        pilot = TourPilot()
        assert pilot.tour.regions == REGIONS
        assert len(REGIONS) == 20
        assert pilot.flying

    def test_it_writes_the_camera_a_target(self):
        camera = SteeringCamera()
        pilot = TourPilot()
        assert camera.target is None

        assert pilot.steer(camera, 0.0, WIDE) is True
        assert camera.target is not None
        # The first region, because a tour dwells before it travels.
        assert camera.target == pytest.approx((REGIONS[0][1], REGIONS[0][2]))

    def test_the_camera_actually_moves_toward_it(self):
        """The pilot sets the target; the camera's own follow does the move."""
        camera = SteeringCamera()
        pilot = TourPilot()
        pilot.steer(camera, 0.0, WIDE)

        start = camera.centre
        camera.advance(0.0)                 # first call only takes the clock
        # EIGHT SECONDS, not two. The follow is exponential with a time
        # constant the camera bounds at 3.8 s, so two seconds is 41 % of
        # the way and eight is 88 % -- and "most of the way there" has to
        # be asked after the camera has had time to get there.
        for tick in range(1, 161):
            camera.advance(tick * 0.05)

        target = camera.target
        assert camera.centre != start
        moved = abs(camera.centre[0] - start[0]) + abs(camera.centre[1] - start[1])
        left = abs(target[0] - camera.centre[0]) + abs(target[1] - camera.centre[1])
        assert moved > left, "the camera did not get most of the way there"


class TestItMovesSmoothly:

    def test_no_frame_jumps_further_than_the_ones_around_it(self):
        """The whole ask was "gently and smoothely", so measure it.

        A tour that cut between regions would show one step far larger
        than its neighbours. The tour eases with a smoothstep and the
        camera follows exponentially, so the largest step in a circuit
        must stay within a small multiple of the median one.
        """
        tour = RegionTour(REGIONS, dwell=1.0, travel=1.0)
        pilot = TourPilot(tour)
        camera = SteeringCamera()
        camera.advance(0.0)

        steps = []
        previous = camera.centre
        for frame in range(1, 1200):
            now = frame * 0.02
            pilot.steer(camera, now, WIDE)
            here = camera.advance(now)
            steps.append(abs(here[0] - previous[0]) + abs(here[1] - previous[1]))
            previous = here

        ordered = sorted(steps)
        median = ordered[len(ordered) // 2]
        assert median > 0.0, "the camera never moved"
        assert max(steps) < 25.0 * median, (
            "one frame moved far further than the rest -- the tour is "
            "cutting between regions rather than floating between them")


class TestTheUserWins:

    def test_a_drag_stops_the_tour_for_good(self):
        camera = SteeringCamera()
        pilot = TourPilot()
        assert pilot.steer(camera, 0.0, WIDE) is True

        pilot.dragged()
        assert pilot.flying is False
        camera.target = None
        assert pilot.steer(camera, 5.0, WIDE) is False
        assert camera.target is None, (
            "the tour steered over a drag -- the application arguing with "
            "the user about where they want to be")

    def test_ctrl_r_hands_the_camera_back(self):
        camera = SteeringCamera()
        pilot = TourPilot()
        pilot.dragged()
        assert pilot.flying is False

        pilot.restarted()
        assert pilot.flying is True
        assert pilot.steer(camera, 0.0, WIDE) is True


class TestItKnowsWhereItsItineraryEnds:

    def test_it_stops_steering_once_the_view_is_narrower_than_the_regions(self):
        """The half-width column is how far down a region holds up.

        Steering toward the next region at a scale where the current one
        no longer has detail would fly the picture past at a magnification
        where nothing is recognisable.
        """
        camera = SteeringCamera()
        pilot = TourPilot()
        assert pilot.steer(camera, 0.0, WIDE) is True

        camera.target = None
        assert pilot.steer(camera, 30.0, NARROW) is False
        assert camera.target is None

    def test_the_floor_comes_from_the_data_and_not_from_a_constant(self):
        widest = max(float(row[3]) for row in REGIONS)
        assert TourPilot()._floor() == pytest.approx(widest)

        # A tour over different regions floors somewhere else, so nobody
        # has to keep a constant in step with the generated file.
        other = RegionTour((("made up", 0.1, 0.2, 0.5, 1.0),))
        assert TourPilot(other)._floor() == pytest.approx(0.5)


class TestItNeverCostsThePicture:

    def test_a_tour_that_throws_costs_a_frame_and_not_the_backdrop(self):
        class Exploding:
            active = True
            regions = ()

            def target_at(self, _seconds):
                raise RuntimeError("no")

        camera = SteeringCamera()
        pilot = TourPilot(Exploding())
        assert pilot.steer(camera, 0.0, WIDE) is False
        assert camera.target is None

    def test_an_empty_tour_simply_does_not_steer(self):
        camera = SteeringCamera()
        pilot = TourPilot(RegionTour(()))
        assert pilot.flying is False
        assert pilot.steer(camera, 0.0, WIDE) is False
