"""Annotation class colours were unreadable on the light theme (issue #6).

Reported as "on OSX, the labels do not appear with good contrast in the
annotation app like they do on Linux machines". It is not a platform
difference -- it is a THEME one, and macOS simply defaults to the light
appearance far more often than Linux does.

The palette was tuned against a dark tile, where it measures 3.5 to 12.0
contrast. Against a light tile the SAME colours measured:

    class 1  #3ea6ff   6.43 dark   2.38 light
    class 2  #ff5252   5.22 dark   2.93 light
    class 4  #55f2d8  11.97 dark   1.28 light

Five of the first six were below the 3.0 readability floor.

Classes 3 and up are generated by a golden-ratio hue rotation, so the set is
open-ended: it cannot be fixed by hand-picking colours, and a flat darkening
factor does not work either -- blues manage at 0.79 of their value while
yellow needs 0.48. So the colour is darkened until it MEASURES readable, and
no further, which keeps the classes distinguishable from each other rather
than all collapsing toward black.
"""

import pytest

pytest.importorskip("PySide6")

from spacr.qt.annotate_engine import label_to_hex


DARK_TILE = "#1e1e1e"
LIGHT_TILE = "#f5f5f5"


def _luminance(hex_colour):
    raw = hex_colour.lstrip("#")
    channels = [int(raw[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    channels = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
                for c in channels]
    return (0.2126 * channels[0] + 0.7152 * channels[1]
            + 0.0722 * channels[2])


def contrast(colour, background):
    a, b = _luminance(colour), _luminance(background)
    hi, lo = max(a, b), min(a, b)
    return (hi + 0.05) / (lo + 0.05)


@pytest.mark.parametrize("cls", range(1, 21))
def test_every_class_reads_on_the_light_theme(cls):
    """The defect. Twenty classes, because the hue rotation is open-ended."""
    colour = label_to_hex(cls, dark=False)
    measured = contrast(colour, LIGHT_TILE)
    assert measured >= 4.5, (
        f"class {cls} is {colour} on the light theme, contrast "
        f"{measured:.2f} against {LIGHT_TILE}")


@pytest.mark.parametrize("cls", range(1, 21))
def test_every_class_still_reads_on_the_dark_theme(cls):
    """Fixing light must not cost dark, which was already fine."""
    colour = label_to_hex(cls, dark=True)
    measured = contrast(colour, DARK_TILE)
    assert measured >= 3.0, (
        f"class {cls} is {colour} on the dark theme, contrast "
        f"{measured:.2f} against {DARK_TILE}")


def test_a_class_keeps_its_hue_across_themes():
    """A class must stay recognisably the same colour, or the two themes
    disagree about which class is which."""
    import colorsys

    for cls in range(1, 10):
        def hue(hex_colour):
            raw = hex_colour.lstrip("#")
            rgb = [int(raw[i:i + 2], 16) / 255 for i in (0, 2, 4)]
            return colorsys.rgb_to_hsv(*rgb)[0]

        light, dark = label_to_hex(cls, dark=False), label_to_hex(cls, True)
        delta = abs(hue(light) - hue(dark))
        delta = min(delta, 1.0 - delta)          # hue is circular
        assert delta < 0.02, (
            f"class {cls} changed hue between themes: {dark} -> {light}")


def test_classes_stay_distinguishable_from_each_other_on_light():
    """Darkening until readable, and no further, is what keeps this true.

    Driving every colour to near-black would pass the contrast tests above
    and make the app useless.
    """
    colours = {label_to_hex(c, dark=False) for c in range(1, 8)}
    assert len(colours) == 7, f"classes collapsed onto shared colours: {colours}"

    darkest = max(_luminance(c) for c in colours)
    assert darkest > 0.02, "every class was driven to near-black"


def test_no_border_for_the_unannotated():
    for value in (None, 0, -1, "x"):
        assert label_to_hex(value, dark=False) is None
        assert label_to_hex(value, dark=True) is None


def test_the_default_is_the_dark_palette():
    """Callers that predate the theme argument keep their behaviour."""
    assert label_to_hex(1) == label_to_hex(1, dark=True)
