"""Where each setting is actually READ. Generated -- do not edit.

Written by ``tools/build_setting_consumer_map.py``.
The API link used to be built from the SCREEN's app_key, so every row
on a panel pointed at that module's entry point whether the value was
read there or twelve calls down. These targets come from an AST walk of
the package instead.

``exact`` is False where the only consumer is a closure: Sphinx cannot
address one, so the link aims at the enclosing function that it can.
"""

#: ``key -> (module, symbol, exact)``
SETTING_API_TARGETS = {
    'CP_prob': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'CP_probability': ('spacr.submodules', 'test_cellpose_model', True),
    'FT': ('spacr.submodules', 'test_cellpose_model', True),
    'Signal_to_noise': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'Toxoplasma': ('spacr.parameter_sweep', 'settings_for_trial', True),
    'adjust_cells': ('spacr.core', 'preprocess_generate_masks', True),
    'agg_type': ('spacr.ml', 'resolve_auto_inference', True),
    'alpha': ('spacr.refit', 'refit_settings', True),
    'amsgrad': ('spacr.deep_spacr', 'train_test_model', True),
    'analysis_mode': ('spacr.ml', 'resolve_auto_inference', True),
    'analysis_unit': ('spacr.ml', 'resolve_auto_inference', True),
    'analyze_clusters': ('spacr.core', 'generate_image_umap', True),
    'anisotropy': ('spacr.measure', 'resolve_measurement_spacing', True),
    'annotated_classes': ('spacr.classify_classes', '', False),
    'annotation_column': ('spacr.classify_classes', 'annotation_column_of', True),
    'annotation_source': ('spacr.ml', '', False),
    'apply_model_to_dataset': ('spacr.deep_spacr', 'deep_spacr', True),
    'attribution_baseline': ('spacr.hyperparam', 'run_search_for_app', True),
    'attribution_steps': ('spacr.hyperparam', 'run_search_for_app', True),
    'augment': ('spacr.deep_spacr', 'train_test_model', True),
    'background': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'background_correction': ('spacr.submodules', 'analyze_invasion', True),
    'balance_to_smallest': ('spacr.io', 'generate_training_dataset', True),
    'barcode_mismatches': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'baseline': ('spacr.attribution', 'deletion_curve', True),
    'batch_column': ('spacr.batch_correction', 'correction_kwargs', True),
    'batch_combat_mean_only': ('spacr.core', 'generate_image_umap', True),
    'batch_control_column': ('spacr.batch_correction', 'correction_kwargs', True),
    'batch_control_values': ('spacr.batch_correction', 'correction_kwargs', True),
    'batch_correction': ('spacr.batch_correction', 'correction_kwargs', True),
    'batch_covariate_column': ('spacr.core', 'generate_image_umap', True),
    'batch_fields': ('spacr.core', 'preprocess_generate_masks', True),
    'batch_min_samples': ('spacr.batch_correction', 'correction_kwargs', True),
    'batch_missing_control': ('spacr.batch_correction', 'correction_kwargs', True),
    'batch_size': ('spacr.deep_spacr', 'apply_model_to_tar', True),
    'bimodality_cutoff': ('spacr.submodules', '', False),
    'black_background': ('spacr.core', 'generate_image_umap', True),
    'blue_channel': ('spacr.core', 'preprocess_generate_masks', True),
    'bounding_box': ('spacr.annotation_dataset', 'generate_annotation_dataset', True),
    'calculate_correlation': ('spacr.measure', '', False),
    'calibrate_fraction_threshold': ('spacr.ml', '', False),
    'cam_type': ('spacr.deep_spacr', 'generate_activation_map', True),
    'cap': ('spacr.cell_montage', 'select_montage', True),
    'cell_area_multiplier': ('spacr.object', 'merge_split_filter_masks', False),
    'cell_area_outlier_mads': ('spacr.outlier_filter', 'apply', True),
    'cell_background': ('spacr.io', '', False),
    'cell_cellprob_threshold': ('spacr.core', 'preprocess_generate_masks', True),
    'cell_chann_dim': ('spacr.submodules', 'analyze_recruitment', True),
    'cell_channel': ('spacr.core', 'preprocess_generate_masks', True),
    'cell_diameter': ('spacr.core', 'preprocess_generate_masks', True),
    'cell_flow_threshold': ('spacr.core', 'preprocess_generate_masks', True),
    'cell_intensity_merge': ('spacr.object', 'merge_split_filter_masks', True),
    'cell_intensity_outlier_mads': ('spacr.outlier_filter', 'apply', True),
    'cell_intensity_percentile': ('spacr.object', 'merge_split_filter_masks', False),
    'cell_intensity_range': ('spacr.submodules', 'analyze_recruitment', True),
    'cell_intensity_split': ('spacr.object', 'merge_split_filter_masks', True),
    'cell_intensity_threshold_method': ('spacr.validate', '', False),
    'cell_loc': ('spacr.deep_spacr', 'annotate_filter_vision', True),
    'cell_mask_dim': ('spacr.measure', 'measure_crop', True),
    'cell_max_area': ('spacr.object', 'merge_split_filter_masks', True),
    'cell_max_intensity_percentile': ('spacr.object', 'merge_split_filter_masks', True),
    'cell_max_size': ('spacr.annotation_dataset', 'filter_selection', True),
    'cell_min_area': ('spacr.core', 'preprocess_generate_masks', True),
    'cell_min_distance': ('spacr.object', 'merge_split_filter_masks', False),
    'cell_min_intensity_percentile': ('spacr.object', 'merge_split_filter_masks', True),
    'cell_min_size': ('spacr.annotation_dataset', 'filter_selection', True),
    'cell_min_split_area': ('spacr.object', 'merge_split_filter_masks', True),
    'cell_model_name': ('spacr.core', 'preprocess_generate_masks', True),
    'cell_perimeter_fraction': ('spacr.object', 'merge_split_filter_masks', True),
    'cell_plate_metadata': ('spacr.plot', 'plot_data_from_db', True),
    'cell_remove_border_objects': ('spacr.object', 'merge_split_filter_masks', True),
    'cell_signal_to_noise': ('spacr.io', '', False),
    'cell_size_range': ('spacr.submodules', 'analyze_recruitment', True),
    'cell_types': ('spacr.plot', 'plot_data_from_db', True),
    'cells': ('spacr.core', 'generate_screen_graphs', True),
    'cells_per_well': ('spacr.submodules', 'analyze_recruitment', True),
    'change_plate': ('spacr.submodules', 'analyze_endodyogeny', True),
    'channel_arrays': ('spacr.annotation_dataset', 'generate_annotation_dataset', True),
    'channel_dims': ('spacr.submodules', 'analyze_recruitment', True),
    'channel_of_interest': ('spacr.ml', 'generate_ml_scores', True),
    'channels': ('spacr.core', 'preprocess_generate_masks', True),
    'checkpoint_path': ('spacr.hyperparam', 'umap_checkpoint_path', True),
    'chunk_size': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'circularize': ('spacr.submodules', 'apply_cellpose_model', True),
    'class_balance': ('spacr.deep_spacr', 'train_test_model', True),
    'class_column': ('spacr.submodules', 'analyze_endodyogeny', True),
    'class_metadata': ('spacr.classify_classes', 'class_metadata_of', True),
    'classes': ('spacr.active_learning', 'retrain_round', True),
    'classifier_evaluation': ('spacr.deep_spacr', '', False),
    'classifier_family': ('spacr.classify', 'resolve_family', True),
    'clustering': ('spacr.core', 'generate_image_umap', True),
    'cmap': ('spacr.core', 'preprocess_generate_masks', True),
    'col_to_compare': ('spacr.core', 'generate_image_umap', True),
    'color_by': ('spacr.core', 'generate_image_umap', True),
    'columnID': ('spacr.submodules', 'generate_score_heatmap', True),
    'column_csv': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'comp_level': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'comp_type': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'compartment': ('spacr.submodules', 'analyze_endodyogeny', True),
    'consolidate': ('spacr.core', 'preprocess_generate_masks', True),
    'control_quantile': ('spacr.submodules', 'analyze_invasion', True),
    'control_sgrnas': ('spacr.submodules', 'generate_score_heatmap', True),
    'control_wells': ('spacr.sequencing', 'graph_sequencing_stats', True),
    'controls': ('spacr.core', 'generate_screen_graphs', True),
    'coordinate_columns': ('spacr.crop_source', 'validate', True),
    'correlation': ('spacr.deep_spacr', 'generate_activation_map', True),
    'count_data': ('spacr.ml', 'minimum_cell_simulation', True),
    'count_grna_column': ('spacr.ml', '', False),
    'count_value_column': ('spacr.ml', '', False),
    'cov_type': ('spacr.ml', 'regression_model', True),
    'crop_dtype': ('spacr.measure', '', False),
    'crop_mode': ('spacr.crops', 'crop_spec_from_settings', True),
    'crop_shape': ('spacr.crop_source', 'crops_from_merged', True),
    'crop_source': ('spacr.crop_source', 'resolve_source', True),
    'cross_validation': ('spacr.ml', 'generate_ml_scores', True),
    'cross_validation_enabled': ('spacr.deep_spacr', 'train_test_model', True),
    'cross_validation_folds': ('spacr.deep_spacr', 'train_test_model', True),
    'csv': ('spacr.submodules', 'generate_score_heatmap', True),
    'csv_name': ('spacr.submodules', 'generate_score_heatmap', True),
    'custom_model': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'custom_model_path': ('spacr.deep_spacr', 'train_test_model', True),
    'custom_regex': ('spacr.core', 'preprocess_generate_masks', True),
    'cv_csv': ('spacr.submodules', 'generate_score_heatmap', True),
    'cv_group_by': ('spacr.deep_spacr', 'train_test_model', True),
    'cytoplasm': ('spacr.measure', 'measure_crop', True),
    'cytoplasm_min_size': ('spacr.annotation_dataset', 'filter_selection', True),
    'data_column': ('spacr.plot', 'plot_data_from_db', True),
    'data_column_cv': ('spacr.submodules', 'generate_score_heatmap', True),
    'dataset': ('spacr.deep_spacr', 'generate_activation_map', True),
    'dataset_mode': ('spacr.training_basis', 'resolve_basis', True),
    'db_path': ('spacr.ml', 'generate_ml_scores', True),
    'db_table_name': ('spacr.timelapse', 'automated_motility_assay', True),
    'delete_intermediate': ('spacr.core', 'preprocess_generate_masks', True),
    'dependent_variable': ('spacr.ml', 'minimum_cell_simulation', True),
    'dialate_png_ratios': ('spacr.crops', 'crop_spec_from_settings', True),
    'dialate_pngs': ('spacr.crops', 'crop_spec_from_settings', True),
    'diameter': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'distance_gaussian_sigma': ('spacr.measure', '', False),
    'dot_size': ('spacr.core', 'generate_image_umap', True),
    'dropout_rate': ('spacr.deep_spacr', 'train_test_model', True),
    'dry_run': ('spacr.core', 'preprocess_generate_masks', True),
    'dst': ('spacr.annotation_dataset', 'generate_annotation_dataset', True),
    'early_stopping_patience': ('spacr.deep_spacr', 'train_test_model', True),
    'edge_image': ('spacr.picture_settings', 'draw_crop', True),
    'edge_thickness': ('spacr.picture_settings', 'draw_crop', True),
    'edge_transparency': ('spacr.picture_settings', 'draw_crop', True),
    'embedding_by_controls': ('spacr.core', 'generate_image_umap', True),
    'epochs': ('spacr.deep_spacr', 'train_test_model', True),
    'eps': ('spacr.core', 'generate_image_umap', True),
    'evaluation_bins': ('spacr.deep_spacr', '', False),
    'evaluation_calibration': ('spacr.deep_spacr', '', False),
    'evaluation_fail_on_leakage': ('spacr.deep_spacr', 'train_test_model', True),
    'examples_to_plot': ('spacr.core', 'preprocess_generate_masks', True),
    'exclude': ('spacr.core', 'generate_image_umap', True),
    'exclude_conditions': ('spacr.core', 'generate_image_umap', True),
    'exclude_grnas': ('spacr.ml', '', False),
    'exclude_rows': ('spacr.core', 'generate_image_umap', True),
    'expected_end': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'experiment': ('spacr.foreign', 'run_import', True),
    'extracellular_class': ('spacr.submodules', 'analyze_invasion', True),
    'fdr_alpha': ('spacr.parameter_sweep', 'run_sweep', True),
    'feature_importance': ('spacr.ml', 'interpret_vision_model', True),
    'fields': ('spacr.io', 'preprocess_img_data', True),
    'figuresize': ('spacr.core', 'preprocess_generate_masks', True),
    'file_metadata': ('spacr.io', 'generate_dataset', True),
    'file_type': ('spacr.crop_source', 'select_crops', True),
    'fill_in': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'fill_na': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'filter': ('spacr.object', 'generate_cellpose_masks', True),
    'filter_1': ('spacr.submodules', 'analyze_percent_positive', True),
    'filter_by': ('spacr.core', 'generate_image_umap', True),
    'filter_column': ('spacr.deep_spacr', 'annotate_filter_vision', True),
    'filter_min_max': ('spacr.plot', 'plot_merged', True),
    'filter_value': ('spacr.ml', '', False),
    'flow_threshold': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'focal_alpha': ('spacr.deep_spacr', 'train_test_model', True),
    'focal_gamma': ('spacr.deep_spacr', 'train_test_model', True),
    'folders': ('spacr.submodules', 'generate_score_heatmap', True),
    'fps': ('spacr.io', 'preprocess_img_data', True),
    'fraction_grna': ('spacr.submodules', 'generate_score_heatmap', True),
    'fraction_threshold': ('spacr.annotation_validation', 'default_scenarios', True),
    'frame_interval_s': ('spacr.zstack', 'plan_4d_from_settings', True),
    'generate_full_dataset': ('spacr.deep_spacr', 'deep_spacr', True),
    'generate_training_dataset': ('spacr.deep_spacr', 'deep_spacr', True),
    'gpu': ('spacr.core', 'generate_image_umap', True),
    'gradient_accumulation': ('spacr.deep_spacr', 'train_test_model', True),
    'gradient_accumulation_steps': ('spacr.deep_spacr', 'train_test_model', True),
    'grayscale': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'green_channel': ('spacr.core', 'preprocess_generate_masks', True),
    'grna_csv': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'grna_statistic': ('spacr.run_recommendations', 'recommend', True),
    'group_by_class': ('spacr.submodules', 'analyze_endodyogeny', True),
    'group_column': ('spacr.submodules', 'analyze_endodyogeny', True),
    'group_lasso_lambda': ('spacr.ml', 'regression', True),
    'grouping': ('spacr.ml', 'generate_ml_scores', True),
    'guide_min_wells': ('spacr.ml', '', False),
    'guide_nuisance_columns': ('spacr.run_recommendations', 'recommend', True),
    'guide_permutation_batch_size': ('spacr.ml', '', False),
    'guide_permutation_block': ('spacr.ml', 'resolve_auto_inference', True),
    'guide_permutation_seed': ('spacr.ml', '', False),
    'guide_permutations': ('spacr.ml', '', False),
    'guide_presence_threshold': ('spacr.ml', '', False),
    'guide_primary_min_wells': ('spacr.ml', '', False),
    'half_widths': ('spacr.cell_montage', 'score_window', True),
    'heatmap_feature': ('spacr.ml', 'generate_ml_scores', True),
    'hinge_n_boot': ('spacr.ml', 'regression', True),
    'hinge_threshold': ('spacr.ml', 'regression', True),
    'holdout_plate': ('spacr.ml', 'generate_ml_scores', True),
    'homogeneity': ('spacr.measure', '', False),
    'homogeneity_distances': ('spacr.measure', '', False),
    'huber_t': ('spacr.ml', 'regression', True),
    'illumination_correction': ('spacr.core', 'preprocess_generate_masks', True),
    'illumination_dark': ('spacr.illumination', 'prepare_illumination_model', True),
    'illumination_degree': ('spacr.illumination', 'prepare_illumination_model', True),
    'illumination_estimator': ('spacr.illumination', 'prepare_illumination_model', True),
    'illumination_max_fields': ('spacr.illumination', 'prepare_illumination_model', True),
    'illumination_model': ('spacr.illumination', 'load_segmentation_illumination_resume', True),
    'illumination_on_missing': ('spacr.illumination', 'load_segmentation_illumination_resume', True),
    'illumination_per_plate': ('spacr.illumination', 'prepare_illumination_model', True),
    'illumination_qc': ('spacr.illumination', 'prepare_illumination_model', True),
    'image_nr': ('spacr.core', 'generate_image_umap', True),
    'image_size': ('spacr.crop_source', 'crops_from_merged', True),
    'image_type': ('spacr.active_learning', 'retrain_round', True),
    'img_zoom': ('spacr.core', 'generate_image_umap', True),
    'include_all': ('spacr.submodules', 'interpret_vision_model', True),
    'independent_variable_layout': ('spacr.ml', '', False),
    'infection_intensity_mode': ('spacr.timelapse', '', False),
    'infection_intensity_n_bins': ('spacr.timelapse', '', False),
    'infection_intensity_qc': ('spacr.timelapse', 'automated_motility_assay', True),
    'infection_intensity_qc_graphs': ('spacr.timelapse', '', False),
    'infection_intensity_qc_panel_path': ('spacr.timelapse', '', False),
    'infection_intensity_qc_scope': ('spacr.timelapse', '', False),
    'infection_intensity_strategy': ('spacr.timelapse', 'automated_motility_assay', True),
    'infection_pca_log_intensity': ('spacr.timelapse', '', False),
    'infection_pca_max_cells': ('spacr.timelapse', '', False),
    'infection_pca_method': ('spacr.timelapse', '', False),
    'infection_pca_min_gt_separation': ('spacr.timelapse', '', False),
    'infection_pca_min_silhouette': ('spacr.timelapse', '', False),
    'infection_pca_pathogen_weight': ('spacr.timelapse', '', False),
    'infection_pca_random_state': ('spacr.timelapse', '', False),
    'infection_xgb_ambiguous_high': ('spacr.timelapse', 'automated_motility_assay', True),
    'infection_xgb_ambiguous_low': ('spacr.timelapse', 'automated_motility_assay', True),
    'infection_xgb_colsample_bytree': ('spacr.timelapse', '', False),
    'infection_xgb_drop_ambiguous': ('spacr.timelapse', 'automated_motility_assay', True),
    'infection_xgb_learning_rate': ('spacr.timelapse', '', False),
    'infection_xgb_margin': ('spacr.timelapse', '', False),
    'infection_xgb_max_depth': ('spacr.timelapse', '', False),
    'infection_xgb_min_cells_per_class': ('spacr.timelapse', '', False),
    'infection_xgb_n_estimators': ('spacr.timelapse', '', False),
    'infection_xgb_n_jobs': ('spacr.timelapse', '', False),
    'infection_xgb_proba_column': ('spacr.timelapse', 'automated_motility_assay', True),
    'infection_xgb_proba_threshold': ('spacr.timelapse', '', False),
    'infection_xgb_random_state': ('spacr.timelapse', '', False),
    'infection_xgb_reg_lambda': ('spacr.timelapse', '', False),
    'infection_xgb_subsample': ('spacr.timelapse', '', False),
    'infection_xgb_top_features': ('spacr.timelapse', '', False),
    'inference': ('spacr.ml', 'resolve_auto_inference', True),
    'inflation_warn': ('spacr.submodules', '', False),
    'init_weights': ('spacr.deep_spacr', 'train_test_model', True),
    'input_mean': ('spacr.deep_spacr', 'apply_model_to_tar', True),
    'input_statistics': ('spacr.deep_spacr', 'apply_model_to_tar', True),
    'input_std': ('spacr.deep_spacr', 'apply_model_to_tar', True),
    'intensity_statistic': ('spacr.submodules', 'analyze_invasion', True),
    'intercept': ('spacr.ml', 'regression', True),
    'intercept_value': ('spacr.ml', '', False),
    'intermedeate_save': ('spacr.deep_spacr', 'train_test_model', True),
    'invert': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'invert_dependent_variable': ('spacr.ml', '', False),
    'isomap_n_neighbors': ('spacr.core', 'generate_image_umap', True),
    'isomap_path_method': ('spacr.core', 'generate_image_umap', True),
    'keep_intermediate': ('spacr.core', 'preprocess_generate_masks', True),
    'keep_npz': ('spacr.core', 'preprocess_generate_masks', True),
    'keep_original_images': ('spacr.core', 'preprocess_generate_masks', True),
    'l1_ratio': ('spacr.ml', 'regression_model', True),
    'label_smoothing': ('spacr.deep_spacr', 'train_test_model', True),
    'lasso_n_boot': ('spacr.ml', '', False),
    'lasso_selection_threshold': ('spacr.ml', '', False),
    'leakage_audit_train_test': ('spacr.deep_spacr', 'train_test_model', True),
    'leakage_hash_content': ('spacr.deep_spacr', 'train_test_model', True),
    'leakage_require_identity': ('spacr.deep_spacr', 'train_test_model', True),
    'learning_rate': ('spacr.deep_spacr', 'train_test_model', True),
    'level': ('spacr.cell_montage', 'select_montage_per_guide', True),
    'location_column': ('spacr.hyperparam', 'load_search_data', True),
    'log_data': ('spacr.core', 'generate_image_umap', True),
    'log_x': ('spacr.plot', 'plot_data_from_csv', True),
    'log_y': ('spacr.plot', 'plot_data_from_csv', True),
    'logit_adjust_tau': ('spacr.deep_spacr', 'train_test_model', True),
    'loss_type': ('spacr.deep_spacr', 'train_test_model', True),
    'lower_percentile': ('spacr.plot', 'plot_object_outlines', True),
    'magnification': ('spacr.utils', '', False),
    'manders_thresholds': ('spacr.deep_spacr', 'generate_activation_map', True),
    'mask': ('spacr.deep_spacr', 'analyze_activation_maps', True),
    'masks': ('spacr.core', 'preprocess_generate_masks', True),
    'max_area': ('spacr.submodules', 'analyze_endodyogeny', True),
    'max_bins': ('spacr.submodules', 'analyze_endodyogeny', True),
    'max_displacement': ('spacr.timelapse', 'automated_motility_assay', True),
    'max_parasite_area': ('spacr.submodules', 'analyze_replication', True),
    'max_parasites_per_vacuole': ('spacr.submodules', 'analyze_replication', True),
    'measurement': ('spacr.benchmark', 'recommend_workers', True),
    'merge_edge_pathogen_cells': ('spacr.measure', '', False),
    'merge_pathogens': ('spacr.utils', '', False),
    'metadata_files': ('spacr.ml', '', False),
    'metadata_type': ('spacr.core', 'preprocess_generate_masks', True),
    'metric': ('spacr.core', 'generate_image_umap', True),
    'min_area_bin': ('spacr.submodules', 'analyze_endodyogeny', True),
    'min_cell_count': ('spacr.ml', 'minimum_cell_simulation', True),
    'min_control_objects': ('spacr.submodules', 'analyze_invasion', True),
    'min_dist': ('spacr.core', 'generate_image_umap', True),
    'min_max': ('spacr.ml', 'generate_ml_scores', True),
    'min_n': ('spacr.ml', '', False),
    'min_objects_for_bimodality': ('spacr.submodules', '', False),
    'min_objects_for_threshold': ('spacr.submodules', '', False),
    'min_parasite_area': ('spacr.submodules', 'analyze_replication', True),
    'min_parasites_per_well': ('spacr.submodules', '', False),
    'min_samples': ('spacr.core', 'generate_image_umap', True),
    'min_total_intensity': ('spacr.submodules', 'analyze_invasion', True),
    'mix': ('spacr.core', 'generate_image_umap', True),
    'mixed_precision': ('spacr.deep_spacr', 'train_model', True),
    'mode': ('spacr.plot', 'plot_region', True),
    'model_data_layout': ('spacr.ml', '', False),
    'model_name': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'model_path': ('spacr.deep_spacr', 'apply_model_to_tar', True),
    'model_plate_position': ('spacr.ml', 'regression', True),
    'model_type': ('spacr.classify', 'resolve_ml_model_type', True),
    'model_type_ml': ('spacr.classify', 'resolve_ml_model_type', True),
    'motility_analysis': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'motility_xlim': ('spacr.timelapse', '', False),
    'motility_ylim': ('spacr.timelapse', '', False),
    'multiple_testing_method': ('spacr.ml', '', False),
    'n_epochs': ('spacr.submodules', 'train_cellpose', True),
    'n_estimators': ('spacr.ml', 'generate_ml_scores', True),
    'n_jobs': ('spacr.core', 'preprocess_generate_masks', True),
    'n_neighbors': ('spacr.core', 'generate_image_umap', True),
    'n_repeats': ('spacr.ml', 'generate_ml_scores', True),
    'n_top_examples': ('spacr.deep_spacr', 'deep_spacr', True),
    'neg': ('spacr.core', 'generate_image_umap', True),
    'negative_control': ('spacr.hyperparam', 'load_search_data', True),
    'nested_cv_inner_folds': ('spacr.deep_spacr', '', False),
    'non_power_of_two_warn': ('spacr.submodules', 'analyze_replication', True),
    'normalise_fraction': ('spacr.ml', '', False),
    'normalization': ('spacr.align', '', False),
    'normalization_percentiles': ('spacr.plot', 'plot_merged', True),
    'normalize': ('spacr.core', 'preprocess_generate_masks', True),
    'normalize_by': ('spacr.crops', 'crop_spec_from_settings', True),
    'normalize_input': ('spacr.deep_spacr', 'generate_activation_map', True),
    'nr': ('spacr.io', 'preprocess_img_data', True),
    'nuclei_limit': ('spacr.core', 'generate_screen_graphs', True),
    'nucleus_area_multiplier': ('spacr.object', 'merge_split_filter_masks', False),
    'nucleus_area_outlier_mads': ('spacr.outlier_filter', 'apply', True),
    'nucleus_background': ('spacr.io', '', False),
    'nucleus_cellprob_threshold': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'nucleus_chann_dim': ('spacr.submodules', 'analyze_recruitment', True),
    'nucleus_channel': ('spacr.core', 'preprocess_generate_masks', True),
    'nucleus_diameter': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'nucleus_flow_threshold': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'nucleus_intensity_merge': ('spacr.object', 'merge_split_filter_masks', True),
    'nucleus_intensity_outlier_mads': ('spacr.outlier_filter', 'apply', True),
    'nucleus_intensity_percentile': ('spacr.object', 'merge_split_filter_masks', False),
    'nucleus_intensity_range': ('spacr.submodules', 'analyze_recruitment', True),
    'nucleus_intensity_split': ('spacr.object', 'merge_split_filter_masks', True),
    'nucleus_intensity_threshold_method': ('spacr.validate', '', False),
    'nucleus_mask_dim': ('spacr.measure', 'measure_crop', True),
    'nucleus_max_area': ('spacr.object', 'merge_split_filter_masks', True),
    'nucleus_max_intensity_percentile': ('spacr.object', 'merge_split_filter_masks', True),
    'nucleus_max_size': ('spacr.annotation_dataset', 'filter_selection', True),
    'nucleus_min_area': ('spacr.object', 'merge_split_filter_masks', True),
    'nucleus_min_distance': ('spacr.object', 'merge_split_filter_masks', False),
    'nucleus_min_intensity_percentile': ('spacr.object', 'merge_split_filter_masks', True),
    'nucleus_min_size': ('spacr.measure', 'measure_crop', True),
    'nucleus_min_split_area': ('spacr.object', 'merge_split_filter_masks', True),
    'nucleus_model_name': ('spacr.utils', '', False),
    'nucleus_perimeter_fraction': ('spacr.object', 'merge_split_filter_masks', True),
    'nucleus_remove_border_objects': ('spacr.object', 'merge_split_filter_masks', True),
    'nucleus_signal_to_noise': ('spacr.io', '', False),
    'nucleus_size_range': ('spacr.submodules', 'analyze_recruitment', True),
    'object_array': ('spacr.annotation_dataset', 'filter_selection', True),
    'object_distance_intensity': ('spacr.measure', '', False),
    'object_distance_maxima': ('spacr.measure', '', False),
    'object_distances': ('spacr.measure', '', False),
    'object_size': ('spacr.picture_settings', 'draw_crop', True),
    'object_type': ('spacr.crops', 'extract_crop', True),
    'offset_start': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'optimizer_type': ('spacr.deep_spacr', 'train_test_model', True),
    'organelle_adaptive_block_size': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_adaptive_offset': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_area_multiplier': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_cellprob_threshold': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'organelle_chann_dim': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_channel': ('spacr.core', 'preprocess_generate_masks', True),
    'organelle_clahe': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_clahe_clip_limit': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_diameter': ('spacr.organelle_types', 'apply_preset', True),
    'organelle_dog_sigma_high': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_dog_sigma_low': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_fill_holes': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_flow_threshold': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'organelle_hysteresis_high': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_hysteresis_low': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_intensity_merge': ('spacr.object', 'merge_split_filter_masks', True),
    'organelle_intensity_percentile': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_intensity_split': ('spacr.object', 'merge_split_filter_masks', True),
    'organelle_intensity_threshold_method': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_log_max_sigma': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_log_min_sigma': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_log_num_sigma': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_log_threshold': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_mask_dim': ('spacr.crops', 'mask_dims_from_settings', True),
    'organelle_mask_within_cells': ('spacr.object', 'generate_organelle_masks_sam', True),
    'organelle_max_area': ('spacr.object', 'generate_organelle_masks_sam', True),
    'organelle_max_intensity_percentile': ('spacr.object', 'merge_split_filter_masks', True),
    'organelle_method': ('spacr.object', 'generate_organelle_masks_sam', True),
    'organelle_min_area': ('spacr.object', 'generate_organelle_masks_sam', True),
    'organelle_min_distance': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_min_intensity_percentile': ('spacr.object', 'merge_split_filter_masks', True),
    'organelle_min_split_area': ('spacr.object', 'merge_split_filter_masks', True),
    'organelle_model_name': ('spacr.object', 'generate_organelle_masks_sam', True),
    'organelle_morph_radius': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_morphology': ('spacr.object', 'generate_organelle_masks_sam', True),
    'organelle_network_threshold': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_perimeter_fraction': ('spacr.object', 'merge_split_filter_masks', True),
    'organelle_remove_border': ('spacr.object', 'generate_organelle_masks_sam', True),
    'organelle_remove_border_objects': ('spacr.object', 'merge_split_filter_masks', True),
    'organelle_resample': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_ridge_filter': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_ridge_sigmas': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_ring_fill_method': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_ring_min_prominence': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_ring_sigma_inner': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_ring_sigma_outer': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_rolling_ball': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_rolling_ball_radius': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_skeletonize': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_tophat_radius': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_type': ('spacr.organelle_types', 'apply_preset', True),
    'organelle_unet_model_path': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_unet_threshold': ('spacr.object_roles', 'organelle_settings_view', True),
    'organelle_watershed_spots': ('spacr.object_roles', 'organelle_settings_view', True),
    'outlier_detection': ('spacr.ml', '', False),
    'outline_color': ('spacr.plot', 'plot_merged', True),
    'outline_palette': ('spacr.core', 'preprocess_generate_masks', True),
    'outline_thickness': ('spacr.plot', 'plot_merged', True),
    'outline_threshold_factor': ('spacr.picture_settings', 'draw_crop', True),
    'outline_width': ('spacr.core', 'generate_image_umap', True),
    'outside_channel': ('spacr.submodules', 'analyze_invasion', True),
    'outside_threshold': ('spacr.submodules', 'analyze_invasion', True),
    'outside_threshold_method': ('spacr.submodules', '', False),
    'overlay': ('spacr.deep_spacr', 'generate_activation_map', True),
    'overlay_chans': ('spacr.plot', 'plot_merged', True),
    'p_threshold_alpha': ('spacr.ml', '', False),
    'p_threshold_kind': ('spacr.ml', '', False),
    'paired_data': ('spacr.ml', 'normalize_regression_input_pairs', True),
    'parasite_count_column': ('spacr.submodules', 'analyze_replication', True),
    'parasite_table': ('spacr.submodules', 'analyze_replication', True),
    'path_column': ('spacr.surrogate', 'explain_classifier', True),
    'path_string': ('spacr.crop_source', 'select_crops', True),
    'pathogen_area_multiplier': ('spacr.object', 'merge_split_filter_masks', False),
    'pathogen_background': ('spacr.io', '', False),
    'pathogen_cellprob_threshold': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'pathogen_chann_dim': ('spacr.submodules', 'analyze_recruitment', True),
    'pathogen_channel': ('spacr.core', 'preprocess_generate_masks', True),
    'pathogen_diameter': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'pathogen_flow_threshold': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'pathogen_intensity_merge': ('spacr.object', 'merge_split_filter_masks', True),
    'pathogen_intensity_percentile': ('spacr.object', 'merge_split_filter_masks', False),
    'pathogen_intensity_range': ('spacr.submodules', 'analyze_recruitment', True),
    'pathogen_intensity_split': ('spacr.object', 'merge_split_filter_masks', True),
    'pathogen_intensity_threshold_method': ('spacr.validate', '', False),
    'pathogen_limit': ('spacr.core', 'generate_screen_graphs', True),
    'pathogen_loc': ('spacr.deep_spacr', 'annotate_filter_vision', True),
    'pathogen_mask_dim': ('spacr.measure', 'measure_crop', True),
    'pathogen_max_area': ('spacr.object', 'merge_split_filter_masks', True),
    'pathogen_max_intensity_percentile': ('spacr.object', 'merge_split_filter_masks', True),
    'pathogen_max_size': ('spacr.annotation_dataset', 'filter_selection', True),
    'pathogen_min_area': ('spacr.object', 'merge_split_filter_masks', True),
    'pathogen_min_distance': ('spacr.object', 'merge_split_filter_masks', False),
    'pathogen_min_intensity_percentile': ('spacr.object', 'merge_split_filter_masks', True),
    'pathogen_min_size': ('spacr.measure', 'measure_crop', True),
    'pathogen_min_split_area': ('spacr.object', 'merge_split_filter_masks', True),
    'pathogen_model': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'pathogen_model_name': ('spacr.utils', '', False),
    'pathogen_perimeter_fraction': ('spacr.object', 'merge_split_filter_masks', True),
    'pathogen_plate_metadata': ('spacr.plot', 'plot_data_from_db', True),
    'pathogen_remove_border_objects': ('spacr.object', 'merge_split_filter_masks', True),
    'pathogen_signal_to_noise': ('spacr.io', '', False),
    'pathogen_size_range': ('spacr.submodules', 'analyze_recruitment', True),
    'pathogen_types': ('spacr.plot', 'plot_data_from_db', True),
    'pathogens': ('spacr.deep_spacr', 'annotate_filter_vision', True),
    'pca_svd_solver': ('spacr.core', 'generate_image_umap', True),
    'pca_whiten': ('spacr.core', 'generate_image_umap', True),
    'percentiles': ('spacr.plot', 'plot_region', True),
    'permutation_importance': ('spacr.ml', 'interpret_vision_model', True),
    'pin_memory': ('spacr.deep_spacr', 'train_test_model', True),
    'pipeline_style': ('spacr.core', 'preprocess_generate_masks', True),
    'pixels_per_um': ('spacr.timelapse', 'automated_motility_assay', True),
    'plaque_model': ('spacr.submodules', '', False),
    'plate': ('spacr.spacrops', 'stitch_cycle_wells', True),
    'plateID': ('spacr.submodules', 'generate_score_heatmap', True),
    'plate_format': ('spacr.omero', 'well_position', True),
    'plot': ('spacr.core', 'preprocess_generate_masks', True),
    'plot_by_cluster': ('spacr.core', 'generate_image_umap', True),
    'plot_cluster_grids': ('spacr.core', 'generate_image_umap', True),
    'plot_control': ('spacr.submodules', 'analyze_recruitment', True),
    'plot_images': ('spacr.core', 'generate_image_umap', True),
    'plot_nr': ('spacr.submodules', 'analyze_recruitment', True),
    'plot_outlines': ('spacr.core', 'generate_image_umap', True),
    'plot_points': ('spacr.core', 'generate_image_umap', True),
    'png_size': ('spacr.annotation_dataset', 'generate_annotation_dataset', True),
    'png_type': ('spacr.crop_source', 'select_crops', True),
    'point_alpha': ('spacr.core', 'generate_image_umap', True),
    'point_color': ('spacr.core', 'generate_image_umap', True),
    'pos': ('spacr.core', 'generate_image_umap', True),
    'positive_control': ('spacr.hyperparam', 'load_search_data', True),
    'preprocess': ('spacr.core', 'preprocess_generate_masks', True),
    'prune_features': ('spacr.ml', 'generate_ml_scores', True),
    'qc_plot_max_panels': ('spacr.submodules', 'analyze_invasion', True),
    'quantile': ('spacr.ml', 'regression', True),
    'radial_dist': ('spacr.measure', '', False),
    'random_row_column_effects': ('spacr.refit', 'refit_settings', True),
    'random_seed': ('spacr.annotation_dataset', 'generate_annotation_dataset', True),
    'random_test': ('spacr.io', 'preprocess_img_data', True),
    'randomize': ('spacr.core', 'preprocess_generate_masks', True),
    'red_channel': ('spacr.core', 'preprocess_generate_masks', True),
    'reduction_method': ('spacr.core', 'generate_image_umap', True),
    'reg_alpha': ('spacr.ml', 'generate_ml_scores', True),
    'reg_lambda': ('spacr.ml', 'generate_ml_scores', True),
    'regex': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'regression_backend': ('spacr.ml', 'regression_model', True),
    'regression_panel_manifest': ('spacr.ml', '', False),
    'regression_qc': ('spacr.ml', '', False),
    'regression_type': ('spacr.ml', 'results_folder_kind', True),
    'remove_background': ('spacr.plot', 'plot_merged', True),
    'remove_background_cell': ('spacr.io', '', False),
    'remove_background_nucleus': ('spacr.io', '', False),
    'remove_background_pathogen': ('spacr.io', '', False),
    'remove_cluster_noise': ('spacr.core', 'generate_image_umap', True),
    'remove_highly_correlated': ('spacr.core', 'generate_image_umap', True),
    'remove_highly_correlated_features': ('spacr.ml', 'generate_ml_scores', True),
    'remove_image_canvas': ('spacr.core', 'generate_image_umap', True),
    'remove_low_variance_features': ('spacr.ml', 'generate_ml_scores', True),
    'require_host_cell': ('spacr.submodules', 'analyze_replication', True),
    'resample': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'rescale': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'resize': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'resnet_features': ('spacr.core', 'generate_image_umap', True),
    'resume': ('spacr.core', 'preprocess_generate_masks', True),
    'resume_checkpoint': ('spacr.deep_spacr', 'train_test_model', True),
    'reuse_existing_measurements': ('spacr.timelapse', 'automated_motility_assay', True),
    'row_csv': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'row_limit': ('spacr.core', 'generate_image_umap', True),
    'rra_alpha': ('spacr.ml', 'regression', True),
    'rra_permutations': ('spacr.ml', 'regression', True),
    'sample': ('spacr.io', 'generate_dataset', True),
    'sanity_check': ('spacr.hyperparam', 'run_search_for_app', True),
    'save': ('spacr.core', 'preprocess_generate_masks', True),
    'save_arrays': ('spacr.measure', '', False),
    'save_dtype': ('spacr.io', 'concatenate_and_normalize', True),
    'save_figure': ('spacr.core', 'generate_image_umap', True),
    'save_h5': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'save_measurements': ('spacr.foreign', 'run_import', True),
    'save_original_images': ('spacr.io', 'preprocess_img_data', True),
    'save_png': ('spacr.measure', 'measure_crop', True),
    'schedule': ('spacr.deep_spacr', 'train_test_model', True),
    'score_column': ('spacr.cell_montage', 'select_montage', True),
    'score_data': ('spacr.ml', 'minimum_cell_simulation', True),
    'score_threshold': ('spacr.deep_spacr', 'apply_model_to_tar', True),
    'scores': ('spacr.active_learning', 'build_queue', True),
    'seconds_per_frame': ('spacr.timelapse', 'automated_motility_assay', True),
    'seed_wells_from_cells': ('spacr.submodules', 'analyze_replication', True),
    'seg_qc_min_diameter': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'shap': ('spacr.ml', 'interpret_vision_model', True),
    'shap_sample': ('spacr.ml', 'interpret_vision_model', True),
    'shuffle': ('spacr.deep_spacr', 'generate_activation_map', True),
    'single_direction': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'size': ('spacr.active_learning', 'retrain_round', True),
    'smooth_lines': ('spacr.core', 'generate_image_umap', True),
    'smoothgrad_samples': ('spacr.deep_spacr', 'generate_activation_map', True),
    'smoothgrad_sigma': ('spacr.deep_spacr', 'generate_activation_map', True),
    'spatial_measurements': ('spacr.measure', '', False),
    'spatial_neighbor_radius': ('spacr.measure', '', False),
    'spectral_affinity': ('spacr.core', 'generate_image_umap', True),
    'spectral_n_neighbors': ('spacr.core', 'generate_image_umap', True),
    'spline_degree': ('spacr.ml', 'regression', True),
    'spline_knots': ('spacr.ml', 'regression', True),
    'src': ('spacr.annotation_dataset', 'generate_annotation_dataset', True),
    'stitch_threshold': ('spacr.zstack', 'plan_from_settings', True),
    'straightness_filter': ('spacr.timelapse', '', False),
    'straightness_threshold': ('spacr.timelapse', '', False),
    'stream_method': ('spacr.validate', '', False),
    'strict_errors': ('spacr.errors', 'strict_errors', True),
    'summarize_organelles_by': ('spacr.measure', '', False),
    't_axis': ('spacr.zstack', 'plan_4d_from_settings', True),
    't_axis_order': ('spacr.zstack', 'plan_4d_from_settings', True),
    't_link_threshold': ('spacr.zstack', 'plan_4d_from_settings', True),
    't_max_displacement_px': ('spacr.zstack', 'plan_4d_from_settings', True),
    't_max_displacement_um': ('spacr.zstack', 'plan_4d_from_settings', True),
    't_project_for_tracking': ('spacr.zstack', 'plan_4d_from_settings', True),
    't_stack': ('spacr.zstack', 'plan_4d_from_settings', True),
    't_track_backend': ('spacr.zstack', 'plan_4d_from_settings', True),
    'tables': ('spacr.core', 'generate_image_umap', True),
    'tar_path': ('spacr.deep_spacr', 'apply_model_to_tar', True),
    'target': ('spacr.submodules', 'analyze_recruitment', True),
    'target_height': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'target_intensity_min': ('spacr.submodules', 'analyze_recruitment', True),
    'target_layer': ('spacr.deep_spacr', 'generate_activation_map', True),
    'target_sequence': ('spacr.sequencing', 'generate_barecode_mapping', True),
    'target_size': ('spacr.submodules', 'train_cellpose', True),
    'target_unique_count': ('spacr.sequencing', 'graph_sequencing_stats', True),
    'target_width': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'tensorboard': ('spacr.deep_spacr', 'train_test_model', True),
    'test': ('spacr.deep_spacr', 'train_test_model', True),
    'test_images': ('spacr.io', 'preprocess_img_data', True),
    'test_mode': ('spacr.core', 'preprocess_generate_masks', True),
    'test_nr': ('spacr.utils', 'measure_test_mode', True),
    'test_size': ('spacr.ml', 'generate_ml_scores', True),
    'test_split': ('spacr.annotation_dataset', 'generate_annotation_dataset', True),
    'threshold': ('spacr.submodules', 'analyze_percent_positive', True),
    'threshold_agreement_tolerance': ('spacr.submodules', '', False),
    'threshold_method': ('spacr.ml', '', False),
    'threshold_multiplier': ('spacr.ml', '', False),
    'threshold_sensitivity': ('spacr.hit_attribution', 'fit_hit_attribution', True),
    'timelapse': ('spacr.core', 'preprocess_generate_masks', True),
    'timelapse_displacement': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'timelapse_frame_limits': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'timelapse_memory': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'timelapse_mode': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'timelapse_objects': ('spacr.measure', 'measure_crop', True),
    'timelapse_remove_transient': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'tolerance': ('spacr.ml', 'minimum_cell_simulation', True),
    'top_features': ('spacr.ml', 'generate_ml_scores', True),
    'total_channel': ('spacr.submodules', 'analyze_invasion', True),
    'trackastra_linking': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'trackastra_model': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'tracked_object': ('spacr.timelapse', '', False),
    'train': ('spacr.deep_spacr', 'train_test_model', True),
    'train_channels': ('spacr.deep_spacr', 'train_test_model', True),
    'transform': ('spacr.deep_spacr', 'apply_model', True),
    'treatment_loc': ('spacr.deep_spacr', 'annotate_filter_vision', True),
    'treatment_plate_metadata': ('spacr.plot', 'plot_data_from_db', True),
    'treatments': ('spacr.deep_spacr', 'annotate_filter_vision', True),
    'tsne_early_exaggeration': ('spacr.core', 'generate_image_umap', True),
    'tsne_learning_rate': ('spacr.core', 'generate_image_umap', True),
    'tsne_max_iter': ('spacr.core', 'generate_image_umap', True),
    'tsne_perplexity': ('spacr.core', 'generate_image_umap', True),
    'ultrack_contour_sigma': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'ultrack_division_weight': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'ultrack_max_distance': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'ultrack_n_workers': ('spacr.object', 'generate_cellpose_masks_sam', True),
    'um_per_px': ('spacr.submodules', 'analyze_endodyogeny', True),
    'umap_canvas_width': ('spacr.core', 'generate_image_umap', True),
    'umap_sidebar_width': ('spacr.core', 'generate_image_umap', True),
    'uninfected': ('spacr.measure', 'measure_crop', True),
    'use_bounding_box': ('spacr.crops', 'crop_spec_from_settings', True),
    'use_checkpoint': ('spacr.deep_spacr', 'train_test_model', True),
    'vacuole_key': ('spacr.submodules', 'analyze_replication', True),
    'vacuole_link_distance': ('spacr.submodules', 'analyze_replication', True),
    'vacuole_link_factor': ('spacr.submodules', 'analyze_replication', True),
    'val_split': ('spacr.deep_spacr', 'train_test_model', True),
    'value_col': ('spacr.submodules', 'analyze_percent_positive', True),
    'verbose': ('spacr.core', 'preprocess_generate_masks', True),
    'visualize': ('spacr.spacr_cellpose', 'identify_masks_finetune', True),
    'voxel_size_xy_um': ('spacr.measure', 'resolve_measurement_spacing', True),
    'voxel_size_z_um': ('spacr.measure', 'resolve_measurement_spacing', True),
    'weight_decay': ('spacr.deep_spacr', 'train_test_model', True),
    'well_confidence': ('spacr.submodules', 'split_wells', True),
    'well_detection': ('spacr.submodules', 'analyze_plaques', True),
    'well_diameter_mm': ('spacr.plaque', 'scale_from_well', True),
    'well_pad': ('spacr.submodules', 'split_wells', True),
    'wide_predictor_columns': ('spacr.ml', '', False),
    'width_height': ('spacr.model_zoo', '', False),
    'write_random_annotation_column': ('spacr.io', 'generate_training_dataset', True),
    'x_lim': ('spacr.ml', '', False),
    'y_lims': ('spacr.ml', '', False),
    'z_axis': ('spacr.zstack', 'plan_from_settings', True),
    'z_projection': ('spacr.zstack', 'plan_from_settings', True),
    'z_segmentation_mode': ('spacr.zstack', 'plan_from_settings', True),
    'z_stack': ('spacr.zstack', 'plan_from_settings', True),
    'zscore_thresh': ('spacr.timelapse', 'automated_motility_assay', True),
}

#: ``key -> {module: (symbol, exact)}``, for the modules an app's
#: help actually links to.
#:
#: Consulted FIRST, by app. The table above answers "where is this
#: setting read" with one module for the whole package; this one
#: answers it for the panel the reader is looking at, which is a
#: different question and the one they are asking. A setting the
#: app's own module does not read falls through to the single
#: answer above, which is what it had before.
SETTING_API_TARGETS_BY_MODULE = {
    'CP_prob': {'spacr.spacr_cellpose': ('identify_masks_finetune', True)},
    'CP_probability': {'spacr.submodules': ('test_cellpose_model', True)},
    'FT': {'spacr.submodules': ('test_cellpose_model', True)},
    'Signal_to_noise': {'spacr.spacr_cellpose': ('identify_masks_finetune', True)},
    'Toxoplasma': {'spacr.parameter_sweep': ('settings_for_trial', True)},
    'adjust_cells': {'spacr.core': ('preprocess_generate_masks', True)},
    'agg_type': {'spacr.ml': ('resolve_auto_inference', True)},
    'alpha': {'spacr.ml': ('regression_model', True), 'spacr.parameter_sweep': ('correction_rows', True), 'spacr.plate_qc': ('detect_edge_effect', True), 'spacr.plot': ('create_grouped_plot', True), 'spacr.sequencing_qc': ('plot_barcode_qc', True), 'spacr.submodules': ('interpret_vision_model', False), 'spacr.surrogate': ('write_surrogate_result', True), 'spacr.timelapse': ('', False), 'spacr.train_compare': ('plot_curves', True), 'spacr.volcano_style': ('', False)},
    'amsgrad': {'spacr.deep_spacr': ('train_test_model', True)},
    'analysis_mode': {'spacr.ml': ('resolve_auto_inference', True)},
    'analysis_unit': {'spacr.ml': ('resolve_auto_inference', True)},
    'analyze_clusters': {'spacr.core': ('generate_image_umap', True)},
    'anisotropy': {'spacr.measure': ('resolve_measurement_spacing', True), 'spacr.submodules': ('test_cellpose_model', True)},
    'annotation_column': {'spacr.ml': ('generate_ml_scores', True), 'spacr.submodules': ('count_phenotypes', True)},
    'annotation_source': {'spacr.ml': ('', False)},
    'apply_model_to_dataset': {'spacr.deep_spacr': ('deep_spacr', True)},
    'augment': {'spacr.deep_spacr': ('train_test_model', True), 'spacr.submodules': ('train_cellpose', True)},
    'background': {'spacr.spacr_cellpose': ('identify_masks_finetune', True)},
    'background_correction': {'spacr.submodules': ('analyze_invasion', True)},
    'barcode_mismatches': {'spacr.sequencing': ('generate_barecode_mapping', True)},
    'baseline': {'spacr.cell_montage': ('score_window', True), 'spacr.deep_spacr': ('analyze_activation_maps', True), 'spacr.surrogate': ('fit_surrogate', True)},
    'batch_column': {'spacr.ml': ('ml_analysis', True)},
    'batch_combat_mean_only': {'spacr.core': ('generate_image_umap', True), 'spacr.ml': ('generate_ml_scores', True)},
    'batch_control_column': {'spacr.ml': ('ml_analysis', True)},
    'batch_control_values': {'spacr.ml': ('ml_analysis', True)},
    'batch_correction': {'spacr.ml': ('ml_analysis', True)},
    'batch_covariate_column': {'spacr.core': ('generate_image_umap', True), 'spacr.ml': ('generate_ml_scores', True)},
    'batch_fields': {'spacr.core': ('preprocess_generate_masks', True)},
    'batch_min_samples': {'spacr.ml': ('ml_analysis', True)},
    'batch_missing_control': {'spacr.ml': ('ml_analysis', True)},
    'batch_size': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.deep_spacr': ('apply_model_to_tar', True), 'spacr.ml': ('', False), 'spacr.sequencing': ('paired_read_chunked_processing', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.submodules': ('train_cellpose', True)},
    'bimodality_cutoff': {'spacr.submodules': ('', False)},
    'black_background': {'spacr.core': ('generate_image_umap', True)},
    'blue_channel': {'spacr.core': ('preprocess_generate_masks', True)},
    'calculate_correlation': {'spacr.measure': ('', False)},
    'calibrate_fraction_threshold': {'spacr.ml': ('', False)},
    'cam_type': {'spacr.deep_spacr': ('generate_activation_map', True)},
    'cap': {'spacr.cell_montage': ('select_montage', True)},
    'cell_cellprob_threshold': {'spacr.core': ('preprocess_generate_masks', True)},
    'cell_chann_dim': {'spacr.foreign': ('', False), 'spacr.submodules': ('analyze_recruitment', True)},
    'cell_channel': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.plot': ('plot_region', True), 'spacr.timelapse': ('automated_motility_assay', True)},
    'cell_diameter': {'spacr.core': ('preprocess_generate_masks', True)},
    'cell_flow_threshold': {'spacr.core': ('preprocess_generate_masks', True)},
    'cell_intensity_range': {'spacr.submodules': ('analyze_recruitment', True)},
    'cell_loc': {'spacr.core': ('generate_screen_graphs', True), 'spacr.deep_spacr': ('annotate_filter_vision', True), 'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'cell_mask_dim': {'spacr.measure': ('measure_crop', True), 'spacr.plot': ('plot_merged', True)},
    'cell_max_size': {'spacr.measure': ('', False)},
    'cell_min_area': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.measure': ('', False)},
    'cell_min_size': {'spacr.measure': ('', False)},
    'cell_model_name': {'spacr.core': ('preprocess_generate_masks', True)},
    'cell_plate_metadata': {'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'cell_size_range': {'spacr.submodules': ('analyze_recruitment', True)},
    'cell_types': {'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'cells': {'spacr.core': ('generate_screen_graphs', True), 'spacr.deep_spacr': ('annotate_filter_vision', True), 'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'cells_per_well': {'spacr.submodules': ('analyze_recruitment', True), 'spacr.timelapse': ('summarize_per_well', True)},
    'change_plate': {'spacr.submodules': ('analyze_endodyogeny', True)},
    'channel_arrays': {'spacr.measure': ('', False)},
    'channel_dims': {'spacr.submodules': ('analyze_recruitment', True)},
    'channel_of_interest': {'spacr.ml': ('generate_ml_scores', True), 'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'channels': {'spacr.align': ('plan_canvas', True), 'spacr.cell_montage': ('resolve_montage_crop_source', True), 'spacr.core': ('preprocess_generate_masks', True), 'spacr.deep_spacr': ('apply_model_to_tar', True), 'spacr.feature_dict': ('', False), 'spacr.foreign': ('run_import', True), 'spacr.illumination': ('prepare_illumination_model', True), 'spacr.measure': ('measure_crop', True), 'spacr.plot': ('plot_region', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.submodules': ('interpret_vision_model', True), 'spacr.timelapse': ('automated_motility_assay', True)},
    'checkpoint_path': {'spacr.convert': ('convert', True)},
    'chunk_size': {'spacr.model_zoo': ('open_uri', True), 'spacr.sequencing': ('generate_barecode_mapping', True)},
    'circularize': {'spacr.submodules': ('apply_cellpose_model', True)},
    'class_balance': {'spacr.deep_spacr': ('train_test_model', True)},
    'class_column': {'spacr.submodules': ('analyze_endodyogeny', True)},
    'classes': {'spacr.classifier_evaluation': ('evaluate_predictions', True), 'spacr.deep_spacr': ('train_test_model', True), 'spacr.model_zoo': ('', False)},
    'classifier_evaluation': {'spacr.deep_spacr': ('', False)},
    'classifier_family': {'spacr.classify': ('resolve_family', True)},
    'clustering': {'spacr.core': ('generate_image_umap', True)},
    'cmap': {'spacr.classifier_evaluation': ('', False), 'spacr.core': ('preprocess_generate_masks', True), 'spacr.deep_spacr': ('visualize_integrated_gradients', True), 'spacr.illumination': ('', False), 'spacr.ml': ('generate_ml_scores', True), 'spacr.plot': ('plot_merged', True), 'spacr.sequencing': ('graph_sequencing_stats', True), 'spacr.spacrops': ('spacrStitcher.stitch_pair', True), 'spacr.submodules': ('analyze_endodyogeny', True), 'spacr.timelapse': ('', False), 'spacr.volcano_style': ('', False)},
    'col_to_compare': {'spacr.core': ('generate_image_umap', True)},
    'color_by': {'spacr.core': ('generate_image_umap', True)},
    'columnID': {'spacr.submodules': ('generate_score_heatmap', True), 'spacr.timelapse': ('', False)},
    'column_csv': {'spacr.sequencing': ('generate_barecode_mapping', True), 'spacr.sequencing_qc': ('barcode_qc_defaults', True)},
    'comp_level': {'spacr.sequencing': ('generate_barecode_mapping', True)},
    'comp_type': {'spacr.sequencing': ('generate_barecode_mapping', True)},
    'compartment': {'spacr.submodules': ('analyze_endodyogeny', True)},
    'consolidate': {'spacr.core': ('preprocess_generate_masks', True)},
    'control_quantile': {'spacr.submodules': ('analyze_invasion', True)},
    'control_sgrnas': {'spacr.submodules': ('generate_score_heatmap', True)},
    'control_wells': {'spacr.sequencing': ('graph_sequencing_stats', True), 'spacr.submodules': ('analyze_invasion', True)},
    'controls': {'spacr.core': ('generate_screen_graphs', True), 'spacr.ml': ('process_model_coefficients', True), 'spacr.parameter_sweep': ('run_sweep', True)},
    'correlation': {'spacr.deep_spacr': ('generate_activation_map', True)},
    'count_data': {'spacr.ml': ('minimum_cell_simulation', True), 'spacr.sequencing': ('graph_sequencing_stats', True), 'spacr.sequencing_qc': ('barcode_qc_defaults', True)},
    'count_grna_column': {'spacr.ml': ('', False)},
    'count_value_column': {'spacr.ml': ('', False)},
    'cov_type': {'spacr.ml': ('regression_model', True), 'spacr.plot': ('proportion_mixed_model', True)},
    'crop_dtype': {'spacr.measure': ('', False)},
    'crop_mode': {'spacr.measure': ('measure_crop', True)},
    'cross_validation': {'spacr.ml': ('generate_ml_scores', True)},
    'cross_validation_enabled': {'spacr.deep_spacr': ('train_test_model', True)},
    'cross_validation_folds': {'spacr.deep_spacr': ('train_test_model', True)},
    'csv': {'spacr.submodules': ('generate_score_heatmap', True)},
    'csv_name': {'spacr.submodules': ('generate_score_heatmap', True)},
    'custom_model': {'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.submodules': ('analyze_plaques', True)},
    'custom_model_path': {'spacr.deep_spacr': ('train_test_model', True)},
    'custom_regex': {'spacr.core': ('preprocess_generate_masks', True)},
    'cv_csv': {'spacr.submodules': ('generate_score_heatmap', True)},
    'cv_group_by': {'spacr.deep_spacr': ('train_test_model', True), 'spacr.ml': ('generate_ml_scores', True)},
    'cytoplasm': {'spacr.measure': ('measure_crop', True)},
    'cytoplasm_min_size': {'spacr.measure': ('', False)},
    'data_column': {'spacr.core': ('generate_screen_graphs', True), 'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('generate_score_heatmap', True)},
    'data_column_cv': {'spacr.submodules': ('generate_score_heatmap', True)},
    'dataset': {'spacr.deep_spacr': ('generate_activation_map', True)},
    'db_path': {'spacr.agreement': ('agreement_report', True), 'spacr.core': ('preprocess_generate_masks', True), 'spacr.external_masks': ('run_external_masks', True), 'spacr.ml': ('generate_ml_scores', True)},
    'db_table_name': {'spacr.timelapse': ('automated_motility_assay', True)},
    'delete_intermediate': {'spacr.core': ('preprocess_generate_masks', True)},
    'dependent_variable': {'spacr.ml': ('minimum_cell_simulation', True)},
    'dialate_png_ratios': {'spacr.measure': ('', False)},
    'dialate_pngs': {'spacr.measure': ('', False)},
    'diameter': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.model_zoo': ('', False), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.spacrops': ('', False), 'spacr.submodules': ('test_cellpose_model', True)},
    'distance_gaussian_sigma': {'spacr.measure': ('', False)},
    'dot_size': {'spacr.core': ('generate_image_umap', True)},
    'dropout_rate': {'spacr.deep_spacr': ('train_test_model', True)},
    'dry_run': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.foreign': ('', False), 'spacr.measure': ('measure_crop', True), 'spacr.spacrops': ('stitch_cycle_wells', True)},
    'dst': {'spacr.convert': ('convert', True), 'spacr.core': ('', False), 'spacr.deep_spacr': ('train_test_model', True), 'spacr.foreign': ('run_import', True), 'spacr.ml': ('fit_mixed_model', True), 'spacr.plot': ('plot_data_from_db', True), 'spacr.sequencing': ('graph_sequencing_stats', True), 'spacr.sequencing_qc': ('barcode_qc_defaults', True), 'spacr.submodules': ('analyze_plaques', True)},
    'early_stopping_patience': {'spacr.deep_spacr': ('train_test_model', True)},
    'embedding_by_controls': {'spacr.core': ('generate_image_umap', True)},
    'epochs': {'spacr.deep_spacr': ('train_test_model', True), 'spacr.model_zoo': ('', False)},
    'eps': {'spacr.core': ('generate_image_umap', True), 'spacr.deep_spacr': ('train_model', True)},
    'evaluation_bins': {'spacr.deep_spacr': ('', False)},
    'evaluation_calibration': {'spacr.deep_spacr': ('', False)},
    'evaluation_fail_on_leakage': {'spacr.deep_spacr': ('train_test_model', True)},
    'examples_to_plot': {'spacr.core': ('preprocess_generate_masks', True)},
    'exclude': {'spacr.core': ('generate_image_umap', True), 'spacr.ml': ('generate_ml_scores', True), 'spacr.submodules': ('interpret_vision_model', False), 'spacr.surrogate': ('run_explain_cv', True)},
    'exclude_conditions': {'spacr.core': ('generate_image_umap', True)},
    'exclude_grnas': {'spacr.ml': ('', False)},
    'exclude_rows': {'spacr.core': ('generate_image_umap', True)},
    'expected_end': {'spacr.sequencing': ('generate_barecode_mapping', True)},
    'experiment': {'spacr.foreign': ('run_import', True), 'spacr.measure': ('', False), 'spacr.spacrops': ('stitch_cycle_wells', True)},
    'extracellular_class': {'spacr.submodules': ('analyze_invasion', True)},
    'fdr_alpha': {'spacr.ml': ('', False), 'spacr.parameter_sweep': ('run_sweep', True)},
    'feature_importance': {'spacr.ml': ('interpret_vision_model', True), 'spacr.submodules': ('interpret_vision_model', True)},
    'fields': {'spacr.illumination': ('IlluminationModel.load', True)},
    'figuresize': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.plot': ('plot_merged', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'fill_in': {'spacr.spacr_cellpose': ('identify_masks_finetune', True)},
    'fill_na': {'spacr.sequencing': ('generate_barecode_mapping', True)},
    'filter_1': {'spacr.submodules': ('analyze_percent_positive', True)},
    'filter_by': {'spacr.core': ('generate_image_umap', True)},
    'filter_column': {'spacr.deep_spacr': ('annotate_filter_vision', True), 'spacr.ml': ('', False), 'spacr.sequencing': ('graph_sequencing_stats', True)},
    'filter_min_max': {'spacr.plot': ('plot_merged', True)},
    'filter_value': {'spacr.ml': ('', False)},
    'flow_threshold': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.spacrops': ('', False), 'spacr.submodules': ('test_cellpose_model', True)},
    'focal_alpha': {'spacr.deep_spacr': ('train_test_model', True)},
    'focal_gamma': {'spacr.deep_spacr': ('train_test_model', True)},
    'folders': {'spacr.submodules': ('generate_score_heatmap', True)},
    'fraction_grna': {'spacr.submodules': ('generate_score_heatmap', True)},
    'fraction_threshold': {'spacr.ml': ('', False)},
    'generate_full_dataset': {'spacr.deep_spacr': ('deep_spacr', True)},
    'generate_training_dataset': {'spacr.deep_spacr': ('deep_spacr', True)},
    'gpu': {'spacr.core': ('generate_image_umap', True), 'spacr.model_compare': ('segment_with_cellpose', True), 'spacr.submodules': ('train_cellpose', True)},
    'gradient_accumulation': {'spacr.deep_spacr': ('train_test_model', True)},
    'gradient_accumulation_steps': {'spacr.deep_spacr': ('train_test_model', True)},
    'grayscale': {'spacr.model_zoo': ('', False), 'spacr.spacr_cellpose': ('identify_masks_finetune', True)},
    'green_channel': {'spacr.core': ('preprocess_generate_masks', True)},
    'grna_csv': {'spacr.sequencing': ('generate_barecode_mapping', True), 'spacr.sequencing_qc': ('barcode_qc_defaults', True)},
    'grna_statistic': {'spacr.ml': ('', False)},
    'group_by_class': {'spacr.submodules': ('analyze_endodyogeny', True)},
    'group_column': {'spacr.submodules': ('analyze_endodyogeny', True)},
    'group_lasso_lambda': {'spacr.ml': ('regression', True)},
    'grouping': {'spacr.ml': ('generate_ml_scores', True), 'spacr.plate_qc': ('row_column_trends', True), 'spacr.plot': ('plot_plates', True), 'spacr.sequencing': ('graph_sequencing_stats', True), 'spacr.submodules': ('analyze_class_proportion', True)},
    'guide_min_wells': {'spacr.ml': ('', False)},
    'guide_nuisance_columns': {'spacr.ml': ('', False)},
    'guide_permutation_batch_size': {'spacr.ml': ('', False)},
    'guide_permutation_block': {'spacr.ml': ('resolve_auto_inference', True)},
    'guide_permutation_seed': {'spacr.ml': ('', False)},
    'guide_permutations': {'spacr.ml': ('', False)},
    'guide_presence_threshold': {'spacr.ml': ('', False)},
    'guide_primary_min_wells': {'spacr.ml': ('', False)},
    'half_widths': {'spacr.cell_montage': ('score_window', True)},
    'heatmap_feature': {'spacr.ml': ('generate_ml_scores', True)},
    'hinge_n_boot': {'spacr.ml': ('regression', True)},
    'hinge_threshold': {'spacr.ml': ('regression', True)},
    'holdout_plate': {'spacr.ml': ('generate_ml_scores', True)},
    'homogeneity': {'spacr.measure': ('', False)},
    'homogeneity_distances': {'spacr.measure': ('', False)},
    'huber_t': {'spacr.ml': ('regression', True)},
    'illumination_correction': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.illumination': ('load_segmentation_illumination_resume', True)},
    'illumination_dark': {'spacr.illumination': ('prepare_illumination_model', True)},
    'illumination_degree': {'spacr.illumination': ('prepare_illumination_model', True)},
    'illumination_estimator': {'spacr.illumination': ('prepare_illumination_model', True)},
    'illumination_max_fields': {'spacr.illumination': ('prepare_illumination_model', True)},
    'illumination_model': {'spacr.illumination': ('load_segmentation_illumination_resume', True)},
    'illumination_on_missing': {'spacr.illumination': ('load_segmentation_illumination_resume', True)},
    'illumination_per_plate': {'spacr.illumination': ('prepare_illumination_model', True)},
    'illumination_qc': {'spacr.illumination': ('prepare_illumination_model', True)},
    'image_nr': {'spacr.core': ('generate_image_umap', True)},
    'image_size': {'spacr.deep_spacr': ('apply_model_to_tar', True), 'spacr.model_zoo': ('', False)},
    'img_zoom': {'spacr.core': ('generate_image_umap', True)},
    'include_all': {'spacr.submodules': ('interpret_vision_model', True)},
    'independent_variable_layout': {'spacr.ml': ('', False)},
    'infection_intensity_mode': {'spacr.timelapse': ('', False)},
    'infection_intensity_n_bins': {'spacr.timelapse': ('', False)},
    'infection_intensity_qc': {'spacr.timelapse': ('automated_motility_assay', True)},
    'infection_intensity_qc_graphs': {'spacr.timelapse': ('', False)},
    'infection_intensity_qc_panel_path': {'spacr.timelapse': ('', False)},
    'infection_intensity_qc_scope': {'spacr.timelapse': ('', False)},
    'infection_intensity_strategy': {'spacr.timelapse': ('automated_motility_assay', True)},
    'infection_pca_log_intensity': {'spacr.timelapse': ('', False)},
    'infection_pca_max_cells': {'spacr.timelapse': ('', False)},
    'infection_pca_method': {'spacr.timelapse': ('', False)},
    'infection_pca_min_gt_separation': {'spacr.timelapse': ('', False)},
    'infection_pca_min_silhouette': {'spacr.timelapse': ('', False)},
    'infection_pca_pathogen_weight': {'spacr.timelapse': ('', False)},
    'infection_pca_random_state': {'spacr.timelapse': ('', False)},
    'infection_xgb_ambiguous_high': {'spacr.timelapse': ('automated_motility_assay', True)},
    'infection_xgb_ambiguous_low': {'spacr.timelapse': ('automated_motility_assay', True)},
    'infection_xgb_colsample_bytree': {'spacr.timelapse': ('', False)},
    'infection_xgb_drop_ambiguous': {'spacr.timelapse': ('automated_motility_assay', True)},
    'infection_xgb_learning_rate': {'spacr.timelapse': ('', False)},
    'infection_xgb_margin': {'spacr.timelapse': ('', False)},
    'infection_xgb_max_depth': {'spacr.timelapse': ('', False)},
    'infection_xgb_min_cells_per_class': {'spacr.timelapse': ('', False)},
    'infection_xgb_n_estimators': {'spacr.timelapse': ('', False)},
    'infection_xgb_n_jobs': {'spacr.timelapse': ('', False)},
    'infection_xgb_proba_column': {'spacr.timelapse': ('automated_motility_assay', True)},
    'infection_xgb_proba_threshold': {'spacr.timelapse': ('', False)},
    'infection_xgb_random_state': {'spacr.timelapse': ('', False)},
    'infection_xgb_reg_lambda': {'spacr.timelapse': ('', False)},
    'infection_xgb_subsample': {'spacr.timelapse': ('', False)},
    'infection_xgb_top_features': {'spacr.timelapse': ('', False)},
    'inference': {'spacr.ml': ('resolve_auto_inference', True)},
    'inflation_warn': {'spacr.submodules': ('', False)},
    'init_weights': {'spacr.deep_spacr': ('train_test_model', True)},
    'input_mean': {'spacr.deep_spacr': ('apply_model_to_tar', True)},
    'input_statistics': {'spacr.deep_spacr': ('apply_model_to_tar', True)},
    'input_std': {'spacr.deep_spacr': ('apply_model_to_tar', True)},
    'intensity_statistic': {'spacr.submodules': ('analyze_invasion', True)},
    'intercept': {'spacr.ml': ('regression', True)},
    'intercept_value': {'spacr.ml': ('', False)},
    'intermedeate_save': {'spacr.deep_spacr': ('train_test_model', True)},
    'invert': {'spacr.spacr_cellpose': ('identify_masks_finetune', True)},
    'invert_dependent_variable': {'spacr.ml': ('', False)},
    'isomap_n_neighbors': {'spacr.core': ('generate_image_umap', True)},
    'isomap_path_method': {'spacr.core': ('generate_image_umap', True)},
    'keep_intermediate': {'spacr.core': ('preprocess_generate_masks', True)},
    'keep_npz': {'spacr.core': ('preprocess_generate_masks', True)},
    'keep_original_images': {'spacr.core': ('preprocess_generate_masks', True)},
    'l1_ratio': {'spacr.ml': ('regression_model', True)},
    'label_smoothing': {'spacr.deep_spacr': ('train_test_model', True)},
    'lasso_n_boot': {'spacr.ml': ('', False)},
    'lasso_selection_threshold': {'spacr.ml': ('', False)},
    'leakage_audit_train_test': {'spacr.deep_spacr': ('train_test_model', True)},
    'leakage_hash_content': {'spacr.deep_spacr': ('train_test_model', True)},
    'leakage_require_identity': {'spacr.deep_spacr': ('train_test_model', True)},
    'learning_rate': {'spacr.deep_spacr': ('train_test_model', True), 'spacr.ml': ('generate_ml_scores', True), 'spacr.submodules': ('train_cellpose', True), 'spacr.timelapse': ('', False)},
    'level': {'spacr.cell_montage': ('select_montage_per_guide', True), 'spacr.ml': ('regression', True), 'spacr.plot': ('plot_proportion_stacked_bars', True), 'spacr.submodules': ('analyze_endodyogeny', True)},
    'location_column': {'spacr.ml': ('generate_ml_scores', True)},
    'log_data': {'spacr.core': ('generate_image_umap', True)},
    'log_x': {'spacr.plot': ('plot_data_from_csv', True), 'spacr.sequencing': ('graph_sequencing_stats', True)},
    'log_y': {'spacr.plot': ('plot_data_from_csv', True), 'spacr.sequencing': ('graph_sequencing_stats', True)},
    'logit_adjust_tau': {'spacr.deep_spacr': ('train_test_model', True)},
    'loss_type': {'spacr.deep_spacr': ('train_test_model', True)},
    'lower_percentile': {'spacr.plot': ('plot_object_outlines', True)},
    'manders_thresholds': {'spacr.deep_spacr': ('generate_activation_map', True)},
    'mask': {'spacr.deep_spacr': ('analyze_activation_maps', True), 'spacr.measure': ('', False), 'spacr.spacrops': ('spacrStitcher.stitch_pair', True)},
    'masks': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.external_masks': ('plan_external_masks', True), 'spacr.foreign': ('ImportPlan.with_column_maps', True), 'spacr.model_zoo': ('benchmark', True), 'spacr.submodules': ('analyze_plaques', True)},
    'max_area': {'spacr.submodules': ('analyze_endodyogeny', True)},
    'max_bins': {'spacr.submodules': ('analyze_endodyogeny', True)},
    'max_displacement': {'spacr.timelapse': ('automated_motility_assay', True)},
    'max_parasite_area': {'spacr.submodules': ('analyze_replication', True)},
    'max_parasites_per_vacuole': {'spacr.submodules': ('analyze_replication', True)},
    'merge_edge_pathogen_cells': {'spacr.measure': ('', False)},
    'metadata_files': {'spacr.ml': ('', False)},
    'metadata_type': {'spacr.core': ('preprocess_generate_masks', True)},
    'metric': {'spacr.core': ('generate_image_umap', True)},
    'min_area_bin': {'spacr.submodules': ('analyze_endodyogeny', True)},
    'min_cell_count': {'spacr.ml': ('minimum_cell_simulation', True)},
    'min_control_objects': {'spacr.submodules': ('analyze_invasion', True)},
    'min_dist': {'spacr.core': ('generate_image_umap', True), 'spacr.timelapse': ('', False)},
    'min_max': {'spacr.ml': ('generate_ml_scores', True), 'spacr.plot': ('plot_plates', True), 'spacr.sequencing': ('graph_sequencing_stats', True), 'spacr.submodules': ('analyze_class_proportion', True)},
    'min_n': {'spacr.ml': ('', False)},
    'min_objects_for_bimodality': {'spacr.submodules': ('', False)},
    'min_objects_for_threshold': {'spacr.submodules': ('', False)},
    'min_parasite_area': {'spacr.submodules': ('analyze_replication', True)},
    'min_parasites_per_well': {'spacr.submodules': ('', False)},
    'min_samples': {'spacr.core': ('generate_image_umap', True)},
    'min_total_intensity': {'spacr.submodules': ('analyze_invasion', True)},
    'mix': {'spacr.core': ('generate_image_umap', True)},
    'mixed_precision': {'spacr.deep_spacr': ('train_model', True)},
    'mode': {'spacr.align': ('write_stack', True), 'spacr.core': ('generate_image_umap', True), 'spacr.deep_spacr': ('apply_model', True), 'spacr.foreign': ('run_import', True), 'spacr.illumination': ('', False), 'spacr.measure': ('', False), 'spacr.ml': ('generate_ml_scores', True), 'spacr.parameter_sweep': ('run_sweep_parallel', True), 'spacr.plot': ('plot_region', True), 'spacr.sequencing': ('generate_barecode_mapping', True), 'spacr.spacrops': ('spacrStitcher.build_multichannel_mosaic_from_manifest', True), 'spacr.timelapse': ('', False)},
    'model_data_layout': {'spacr.ml': ('', False)},
    'model_name': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.deep_spacr': ('model_knowledge_transfer', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.submodules': ('train_cellpose', True)},
    'model_path': {'spacr.deep_spacr': ('apply_model_to_tar', True), 'spacr.illumination': ('load_segmentation_illumination_resume', True), 'spacr.submodules': ('test_cellpose_model', True)},
    'model_plate_position': {'spacr.ml': ('regression', True)},
    'model_type': {'spacr.classify': ('resolve_ml_model_type', True), 'spacr.deep_spacr': ('train_test_model', True), 'spacr.model_zoo': ('', False)},
    'model_type_ml': {'spacr.classify': ('resolve_ml_model_type', True), 'spacr.ml': ('generate_ml_scores', True)},
    'motility_xlim': {'spacr.timelapse': ('', False)},
    'motility_ylim': {'spacr.timelapse': ('', False)},
    'multiple_testing_method': {'spacr.ml': ('', False)},
    'n_epochs': {'spacr.model_zoo': ('', False), 'spacr.submodules': ('train_cellpose', True)},
    'n_estimators': {'spacr.ml': ('generate_ml_scores', True), 'spacr.surrogate': ('fit_surrogate', True)},
    'n_jobs': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.deep_spacr': ('apply_model_to_tar', True), 'spacr.measure': ('measure_crop', True), 'spacr.ml': ('generate_ml_scores', True), 'spacr.sequencing': ('generate_barecode_mapping', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.submodules': ('interpret_vision_model', True), 'spacr.surrogate': ('fit_surrogate', True), 'spacr.timelapse': ('automated_motility_assay', True)},
    'n_neighbors': {'spacr.core': ('generate_image_umap', True), 'spacr.timelapse': ('', False)},
    'n_repeats': {'spacr.ml': ('generate_ml_scores', True), 'spacr.submodules': ('interpret_vision_model', True), 'spacr.surrogate': ('fit_surrogate', True)},
    'n_top_examples': {'spacr.deep_spacr': ('deep_spacr', True)},
    'neg': {'spacr.core': ('generate_image_umap', True)},
    'negative_control': {'spacr.ml': ('generate_ml_scores', True)},
    'nested_cv_inner_folds': {'spacr.deep_spacr': ('', False)},
    'non_power_of_two_warn': {'spacr.submodules': ('analyze_replication', True)},
    'normalise_fraction': {'spacr.ml': ('', False)},
    'normalization': {'spacr.align': ('', False)},
    'normalization_percentiles': {'spacr.plot': ('plot_merged', True)},
    'normalize': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.deep_spacr': ('apply_model_to_tar', True), 'spacr.measure': ('measure_crop', True), 'spacr.ml': ('', False), 'spacr.plot': ('plot_merged', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.submodules': ('test_cellpose_model', True)},
    'normalize_by': {'spacr.measure': ('measure_crop', True)},
    'normalize_input': {'spacr.deep_spacr': ('generate_activation_map', True)},
    'nr': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.plot': ('plot_merged', True)},
    'nuclei_limit': {'spacr.core': ('generate_screen_graphs', True), 'spacr.ml': ('generate_ml_scores', True), 'spacr.plot': ('plot_merged', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'nucleus_chann_dim': {'spacr.foreign': ('', False), 'spacr.submodules': ('analyze_recruitment', True)},
    'nucleus_channel': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.plot': ('plot_region', True), 'spacr.timelapse': ('automated_motility_assay', True)},
    'nucleus_intensity_range': {'spacr.submodules': ('analyze_recruitment', True)},
    'nucleus_mask_dim': {'spacr.measure': ('measure_crop', True), 'spacr.plot': ('plot_merged', True)},
    'nucleus_max_size': {'spacr.measure': ('', False)},
    'nucleus_min_area': {'spacr.measure': ('', False)},
    'nucleus_min_size': {'spacr.measure': ('measure_crop', True)},
    'nucleus_size_range': {'spacr.submodules': ('analyze_recruitment', True)},
    'object_distance_intensity': {'spacr.measure': ('', False)},
    'object_distance_maxima': {'spacr.measure': ('', False)},
    'object_distances': {'spacr.measure': ('', False)},
    'object_type': {'spacr.cell_montage': ('load_montage_objects', True), 'spacr.core': ('preprocess_generate_masks', True), 'spacr.external_masks': ('InputGroup.from_value', True), 'spacr.feature_dict': ('parse_column', True), 'spacr.foreign': ('plan_import', True), 'spacr.measure': ('', False), 'spacr.model_compare': ('compare_models', True), 'spacr.model_zoo': ('benchmark', True), 'spacr.report': ('', False)},
    'offset_start': {'spacr.sequencing': ('generate_barecode_mapping', True)},
    'optimizer_type': {'spacr.deep_spacr': ('train_test_model', True)},
    'organelle_chann_dim': {'spacr.foreign': ('', False)},
    'organelle_channel': {'spacr.core': ('preprocess_generate_masks', True)},
    'organelle_diameter': {'spacr.measure': ('', False)},
    'organelle_mask_dim': {'spacr.measure': ('', False)},
    'organelle_method': {'spacr.plot': ('plot_organelle_output', True)},
    'organelle_min_area': {'spacr.measure': ('', False)},
    'organelle_morphology': {'spacr.plot': ('plot_organelle_output', True)},
    'organelle_type': {'spacr.measure': ('', False)},
    'outlier_detection': {'spacr.ml': ('', False)},
    'outline_color': {'spacr.plot': ('plot_merged', True)},
    'outline_palette': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'outline_thickness': {'spacr.plot': ('plot_merged', True)},
    'outline_width': {'spacr.core': ('generate_image_umap', True)},
    'outside_channel': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.submodules': ('analyze_invasion', True)},
    'outside_threshold': {'spacr.submodules': ('analyze_invasion', True)},
    'outside_threshold_method': {'spacr.submodules': ('', False)},
    'overlay': {'spacr.deep_spacr': ('generate_activation_map', True), 'spacr.plot': ('plot_merged', True)},
    'overlay_chans': {'spacr.plot': ('plot_merged', True)},
    'p_threshold_alpha': {'spacr.ml': ('', False)},
    'p_threshold_kind': {'spacr.ml': ('', False)},
    'paired_data': {'spacr.ml': ('normalize_regression_input_pairs', True)},
    'parasite_count_column': {'spacr.submodules': ('analyze_replication', True)},
    'parasite_table': {'spacr.submodules': ('analyze_replication', True)},
    'path_column': {'spacr.surrogate': ('explain_classifier', True)},
    'pathogen_chann_dim': {'spacr.foreign': ('', False), 'spacr.submodules': ('analyze_recruitment', True)},
    'pathogen_channel': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.plot': ('plot_region', True), 'spacr.timelapse': ('automated_motility_assay', True)},
    'pathogen_intensity_range': {'spacr.submodules': ('analyze_recruitment', True)},
    'pathogen_limit': {'spacr.core': ('generate_screen_graphs', True), 'spacr.ml': ('generate_ml_scores', True), 'spacr.plot': ('plot_merged', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'pathogen_loc': {'spacr.core': ('generate_screen_graphs', True), 'spacr.deep_spacr': ('annotate_filter_vision', True), 'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'pathogen_mask_dim': {'spacr.measure': ('measure_crop', True), 'spacr.plot': ('plot_merged', True)},
    'pathogen_max_size': {'spacr.measure': ('', False)},
    'pathogen_min_area': {'spacr.measure': ('', False)},
    'pathogen_min_size': {'spacr.measure': ('measure_crop', True)},
    'pathogen_plate_metadata': {'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'pathogen_size_range': {'spacr.submodules': ('analyze_recruitment', True)},
    'pathogen_types': {'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'pathogens': {'spacr.core': ('generate_screen_graphs', True), 'spacr.deep_spacr': ('annotate_filter_vision', True), 'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'pca_svd_solver': {'spacr.core': ('generate_image_umap', True)},
    'pca_whiten': {'spacr.core': ('generate_image_umap', True)},
    'percentiles': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.plot': ('plot_region', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'permutation_importance': {'spacr.ml': ('interpret_vision_model', True), 'spacr.submodules': ('interpret_vision_model', True)},
    'pin_memory': {'spacr.deep_spacr': ('train_test_model', True)},
    'pipeline_style': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.illumination': ('load_segmentation_illumination_resume', True)},
    'pixels_per_um': {'spacr.timelapse': ('automated_motility_assay', True)},
    'plaque_model': {'spacr.submodules': ('', False)},
    'plate': {'spacr.align': ('scan_tiles', True), 'spacr.convert': ('scan', True), 'spacr.external_masks': ('run_external_masks', True), 'spacr.foreign': ('plan_import', True), 'spacr.illumination': ('IlluminationModel.load', True), 'spacr.plate_qc': ('row_column_trends', True), 'spacr.spacrops': ('stitch_cycle_wells', True)},
    'plateID': {'spacr.submodules': ('generate_score_heatmap', True), 'spacr.timelapse': ('', False)},
    'plate_format': {'spacr.plate_qc': ('detect_edge_effect', True), 'spacr.submodules': ('', False)},
    'plot': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.deep_spacr': ('train_test_model', True), 'spacr.measure': ('', False), 'spacr.ml': ('regression', True), 'spacr.plot': ('', False), 'spacr.sequencing_qc': ('barcode_qc_defaults', True), 'spacr.spacr_cellpose': ('check_cellpose_models', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'plot_by_cluster': {'spacr.core': ('generate_image_umap', True)},
    'plot_cluster_grids': {'spacr.core': ('generate_image_umap', True)},
    'plot_control': {'spacr.submodules': ('analyze_recruitment', True)},
    'plot_images': {'spacr.core': ('generate_image_umap', True)},
    'plot_nr': {'spacr.submodules': ('analyze_recruitment', True)},
    'plot_outlines': {'spacr.core': ('generate_image_umap', True)},
    'plot_points': {'spacr.core': ('generate_image_umap', True)},
    'png_size': {'spacr.measure': ('', False)},
    'point_alpha': {'spacr.core': ('generate_image_umap', True)},
    'point_color': {'spacr.core': ('generate_image_umap', True)},
    'pos': {'spacr.core': ('generate_image_umap', True)},
    'positive_control': {'spacr.ml': ('generate_ml_scores', True)},
    'preprocess': {'spacr.core': ('preprocess_generate_masks', True)},
    'prune_features': {'spacr.ml': ('generate_ml_scores', True)},
    'qc_plot_max_panels': {'spacr.submodules': ('analyze_invasion', True)},
    'quantile': {'spacr.ml': ('regression', True)},
    'radial_dist': {'spacr.measure': ('', False)},
    'random_row_column_effects': {'spacr.ml': ('regression', True)},
    'random_seed': {'spacr.core': ('generate_image_umap', True), 'spacr.deep_spacr': ('train_test_model', True), 'spacr.surrogate': ('fit_surrogate', True)},
    'randomize': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.plot': ('plot_object_outlines', True), 'spacr.submodules': ('train_cellpose', True)},
    'red_channel': {'spacr.core': ('preprocess_generate_masks', True)},
    'reduction_method': {'spacr.core': ('generate_image_umap', True)},
    'reg_alpha': {'spacr.ml': ('generate_ml_scores', True)},
    'reg_lambda': {'spacr.ml': ('generate_ml_scores', True)},
    'regex': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.ml': ('process_model_coefficients', True), 'spacr.parameter_sweep': ('', False), 'spacr.sequencing': ('generate_barecode_mapping', True)},
    'regression_backend': {'spacr.ml': ('regression_model', True)},
    'regression_panel_manifest': {'spacr.ml': ('', False)},
    'regression_qc': {'spacr.ml': ('', False), 'spacr.parameter_sweep': ('', False)},
    'regression_type': {'spacr.ml': ('results_folder_kind', True)},
    'remove_background': {'spacr.plot': ('plot_merged', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True)},
    'remove_cluster_noise': {'spacr.core': ('generate_image_umap', True)},
    'remove_highly_correlated': {'spacr.core': ('generate_image_umap', True)},
    'remove_highly_correlated_features': {'spacr.ml': ('generate_ml_scores', True)},
    'remove_image_canvas': {'spacr.core': ('generate_image_umap', True)},
    'remove_low_variance_features': {'spacr.ml': ('generate_ml_scores', True)},
    'require_host_cell': {'spacr.submodules': ('analyze_replication', True)},
    'resample': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.submodules': ('test_cellpose_model', True)},
    'rescale': {'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.submodules': ('train_cellpose', True)},
    'resize': {'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.submodules': ('', False)},
    'resnet_features': {'spacr.core': ('generate_image_umap', True)},
    'resume': {'spacr.convert': ('convert', True), 'spacr.core': ('preprocess_generate_masks', True), 'spacr.foreign': ('', False)},
    'resume_checkpoint': {'spacr.deep_spacr': ('train_test_model', True)},
    'reuse_existing_measurements': {'spacr.timelapse': ('automated_motility_assay', True)},
    'row_csv': {'spacr.sequencing': ('generate_barecode_mapping', True), 'spacr.sequencing_qc': ('barcode_qc_defaults', True)},
    'row_limit': {'spacr.core': ('generate_image_umap', True)},
    'rra_alpha': {'spacr.ml': ('regression', True)},
    'rra_permutations': {'spacr.ml': ('regression', True)},
    'save': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.deep_spacr': ('generate_activation_map', True), 'spacr.ml': ('interpret_vision_model', True), 'spacr.plot': ('plot_data_from_db', True), 'spacr.sequencing_qc': ('barcode_qc_defaults', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.submodules': ('test_cellpose_model', True)},
    'save_arrays': {'spacr.measure': ('', False)},
    'save_figure': {'spacr.core': ('generate_image_umap', True)},
    'save_h5': {'spacr.sequencing': ('generate_barecode_mapping', True)},
    'save_measurements': {'spacr.foreign': ('run_import', True), 'spacr.measure': ('', False)},
    'save_png': {'spacr.measure': ('measure_crop', True)},
    'schedule': {'spacr.deep_spacr': ('train_test_model', True)},
    'score_column': {'spacr.cell_montage': ('select_montage', True), 'spacr.ml': ('interpret_vision_model', False), 'spacr.submodules': ('interpret_vision_model', False)},
    'score_data': {'spacr.ml': ('minimum_cell_simulation', True)},
    'score_threshold': {'spacr.deep_spacr': ('apply_model_to_tar', True), 'spacr.spacrops': ('stitch_cycle_wells', True)},
    'scores': {'spacr.ml': ('interpret_vision_model', False), 'spacr.submodules': ('interpret_vision_model', False)},
    'seconds_per_frame': {'spacr.timelapse': ('automated_motility_assay', True)},
    'seed_wells_from_cells': {'spacr.submodules': ('analyze_replication', True)},
    'shap': {'spacr.ml': ('interpret_vision_model', True), 'spacr.submodules': ('interpret_vision_model', True)},
    'shap_sample': {'spacr.ml': ('interpret_vision_model', True), 'spacr.submodules': ('interpret_vision_model', True)},
    'shuffle': {'spacr.classifier_evaluation': ('grouped_split', True), 'spacr.deep_spacr': ('generate_activation_map', True), 'spacr.ml': ('regression_model', False)},
    'single_direction': {'spacr.sequencing': ('generate_barecode_mapping', True)},
    'size': {'spacr.deep_spacr': ('apply_model', True), 'spacr.foreign': ('run_import', True), 'spacr.ml': ('', False), 'spacr.plot': ('plot_arrays', True), 'spacr.timelapse': ('analyze_calcium_oscillations', True), 'spacr.volcano_style': ('', False)},
    'smooth_lines': {'spacr.core': ('generate_image_umap', True)},
    'smoothgrad_samples': {'spacr.deep_spacr': ('generate_activation_map', True)},
    'smoothgrad_sigma': {'spacr.deep_spacr': ('generate_activation_map', True)},
    'spatial_measurements': {'spacr.measure': ('', False)},
    'spatial_neighbor_radius': {'spacr.measure': ('', False)},
    'spectral_affinity': {'spacr.core': ('generate_image_umap', True)},
    'spectral_n_neighbors': {'spacr.core': ('generate_image_umap', True)},
    'spline_degree': {'spacr.ml': ('regression', True)},
    'spline_knots': {'spacr.ml': ('regression', True)},
    'src': {'spacr.batch': ('Job.default_label', True), 'spacr.core': ('preprocess_generate_masks', True), 'spacr.deep_spacr': ('train_test_model', True), 'spacr.foreign': ('run_import', True), 'spacr.illumination': ('validate_measurement_illumination_inputs', True), 'spacr.measure': ('measure_crop', True), 'spacr.ml': ('generate_ml_scores', True), 'spacr.model_zoo': ('', False), 'spacr.parameter_sweep': ('run_trial_contained', True), 'spacr.plot': ('plot_data_from_db', True), 'spacr.report': ('collect_report', True), 'spacr.sequencing': ('generate_barecode_mapping', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.spacrops': ('stitch_cycle_wells', True), 'spacr.submodules': ('train_cellpose', True), 'spacr.timelapse': ('automated_motility_assay', True)},
    'straightness_filter': {'spacr.timelapse': ('', False)},
    'straightness_threshold': {'spacr.timelapse': ('', False)},
    'summarize_organelles_by': {'spacr.measure': ('', False)},
    'tables': {'spacr.core': ('generate_image_umap', True), 'spacr.external_masks': ('run_external_masks', True), 'spacr.ml': ('generate_ml_scores', True), 'spacr.plot': ('jitterplot_by_annotation', True), 'spacr.submodules': ('analyze_percent_positive', True)},
    'tar_path': {'spacr.deep_spacr': ('apply_model_to_tar', True)},
    'target': {'spacr.cell_montage': ('score_window', True), 'spacr.convert': ('plan', True), 'spacr.deep_spacr': ('analyze_activation_maps', True), 'spacr.foreign': ('ColumnMap.from_row', True), 'spacr.ml': ('', False), 'spacr.model_zoo': ('', False), 'spacr.sequencing': ('paired_read_chunked_processing', True), 'spacr.sequencing_qc': ('derive_threshold', False), 'spacr.submodules': ('analyze_recruitment', True)},
    'target_height': {'spacr.spacr_cellpose': ('identify_masks_finetune', True)},
    'target_intensity_min': {'spacr.submodules': ('analyze_recruitment', True)},
    'target_layer': {'spacr.deep_spacr': ('generate_activation_map', True)},
    'target_sequence': {'spacr.sequencing': ('generate_barecode_mapping', True)},
    'target_size': {'spacr.model_zoo': ('', False), 'spacr.submodules': ('train_cellpose', True)},
    'target_unique_count': {'spacr.sequencing': ('graph_sequencing_stats', True)},
    'target_width': {'spacr.spacr_cellpose': ('identify_masks_finetune', True)},
    'tensorboard': {'spacr.deep_spacr': ('train_test_model', True)},
    'test': {'spacr.deep_spacr': ('train_test_model', True), 'spacr.sequencing': ('generate_barecode_mapping', True)},
    'test_mode': {'spacr.core': ('preprocess_generate_masks', True)},
    'test_size': {'spacr.classifier_evaluation': ('grouped_split', True), 'spacr.ml': ('generate_ml_scores', True), 'spacr.surrogate': ('run_explain_cv', True)},
    'threshold': {'spacr.cell_montage': ('select_montage', True), 'spacr.deep_spacr': ('analyze_activation_maps', True), 'spacr.ml': ('', False), 'spacr.plot': ('plot_object_outlines', True), 'spacr.sequencing_qc': ('derive_threshold', False), 'spacr.submodules': ('analyze_percent_positive', True)},
    'threshold_agreement_tolerance': {'spacr.submodules': ('', False)},
    'threshold_method': {'spacr.ml': ('', False)},
    'threshold_multiplier': {'spacr.ml': ('', False)},
    'threshold_sensitivity': {'spacr.submodules': ('', False)},
    'timelapse': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.measure': ('measure_crop', True), 'spacr.ml': ('interpret_vision_model', False), 'spacr.timelapse': ('', False)},
    'timelapse_objects': {'spacr.measure': ('measure_crop', True)},
    'tolerance': {'spacr.ml': ('minimum_cell_simulation', True)},
    'top_features': {'spacr.ml': ('generate_ml_scores', True), 'spacr.submodules': ('interpret_vision_model', True)},
    'total_channel': {'spacr.core': ('preprocess_generate_masks', True), 'spacr.submodules': ('analyze_invasion', True)},
    'tracked_object': {'spacr.timelapse': ('', False)},
    'train': {'spacr.deep_spacr': ('train_test_model', True)},
    'train_channels': {'spacr.deep_spacr': ('train_test_model', True)},
    'transform': {'spacr.deep_spacr': ('apply_model', True), 'spacr.foreign': ('ColumnMap.from_row', True), 'spacr.measure': ('img_list_to_grid', True), 'spacr.ml': ('pick_glm_family_and_link', True), 'spacr.submodules': ('', False), 'spacr.timelapse': ('', False), 'spacr.train_compare': ('plot_curves', True), 'spacr.volcano_style': ('', False)},
    'treatment_loc': {'spacr.core': ('generate_screen_graphs', True), 'spacr.deep_spacr': ('annotate_filter_vision', True), 'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'treatment_plate_metadata': {'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'treatments': {'spacr.core': ('generate_screen_graphs', True), 'spacr.deep_spacr': ('annotate_filter_vision', True), 'spacr.plot': ('plot_data_from_db', True), 'spacr.submodules': ('analyze_recruitment', True)},
    'tsne_early_exaggeration': {'spacr.core': ('generate_image_umap', True)},
    'tsne_learning_rate': {'spacr.core': ('generate_image_umap', True)},
    'tsne_max_iter': {'spacr.core': ('generate_image_umap', True)},
    'tsne_perplexity': {'spacr.core': ('generate_image_umap', True)},
    'um_per_px': {'spacr.foreign': ('ImportPlan.with_column_maps', True), 'spacr.submodules': ('analyze_endodyogeny', True)},
    'umap_canvas_width': {'spacr.core': ('generate_image_umap', True)},
    'umap_sidebar_width': {'spacr.core': ('generate_image_umap', True)},
    'uninfected': {'spacr.measure': ('measure_crop', True)},
    'use_bounding_box': {'spacr.measure': ('', False)},
    'use_checkpoint': {'spacr.deep_spacr': ('train_test_model', True)},
    'vacuole_key': {'spacr.submodules': ('analyze_replication', True)},
    'vacuole_link_distance': {'spacr.submodules': ('analyze_replication', True)},
    'vacuole_link_factor': {'spacr.submodules': ('analyze_replication', True)},
    'val_split': {'spacr.deep_spacr': ('train_test_model', True)},
    'value_col': {'spacr.plate_qc': ('row_column_trends', True), 'spacr.submodules': ('analyze_percent_positive', True), 'spacr.timelapse': ('', False)},
    'verbose': {'spacr.cell_montage': ('load_montage_objects', True), 'spacr.core': ('preprocess_generate_masks', True), 'spacr.deep_spacr': ('apply_model_to_tar', True), 'spacr.illumination': ('load_segmentation_illumination_resume', True), 'spacr.measure': ('', False), 'spacr.ml': ('generate_ml_scores', True), 'spacr.parameter_sweep': ('rerun_trial', True), 'spacr.plot': ('plot_merged', True), 'spacr.sequencing': ('graph_sequencing_stats', True), 'spacr.sequencing_qc': ('barcode_qc_defaults', True), 'spacr.spacr_cellpose': ('identify_masks_finetune', True), 'spacr.spacrops': ('stitch_cycle_wells', True), 'spacr.submodules': ('analyze_endodyogeny', True), 'spacr.surrogate': ('run_explain_cv', True)},
    'visualize': {'spacr.spacr_cellpose': ('identify_masks_finetune', True)},
    'voxel_size_xy_um': {'spacr.measure': ('resolve_measurement_spacing', True)},
    'voxel_size_z_um': {'spacr.measure': ('resolve_measurement_spacing', True)},
    'weight_decay': {'spacr.deep_spacr': ('train_test_model', True), 'spacr.submodules': ('train_cellpose', True)},
    'well_confidence': {'spacr.submodules': ('split_wells', True)},
    'well_detection': {'spacr.submodules': ('analyze_plaques', True)},
    'well_diameter_mm': {'spacr.submodules': ('', False)},
    'well_pad': {'spacr.submodules': ('split_wells', True)},
    'wide_predictor_columns': {'spacr.ml': ('', False)},
    'width_height': {'spacr.model_zoo': ('', False)},
    'x_lim': {'spacr.ml': ('', False)},
    'y_lims': {'spacr.ml': ('', False)},
    'zscore_thresh': {'spacr.timelapse': ('automated_motility_assay', True)},
}
