#!/usr/bin/env python3
"""Validate installer locale JSON and render shell/PowerShell/NSIS resources."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
LOCALE_DIR = ROOT / "packaging" / "i18n"
OUTPUT_DIR = ROOT / "packaging" / "online" / "generated"
LANGUAGES = ("en", "sv", "de", "es", "zh_CN", "pt", "hi", "ko", "is", "fr")
NSIS_LANGUAGE = {
    "en": "English", "sv": "Swedish", "de": "German", "es": "Spanish",
    "zh_CN": "SimpChinese", "pt": "Portuguese", "hi": "Hindi", "ko": "Korean",
    "is": "Icelandic", "fr": "French",
}


def catalogs() -> dict[str, dict[str, str]]:
    """Load locale files and require the exact canonical English key set."""
    values: dict[str, dict[str, str]] = {}
    expected: set[str] | None = None
    for language in LANGUAGES:
        path = LOCALE_DIR / f"{language}.json"
        if not path.is_file():
            raise FileNotFoundError(f"missing installer locale: {path}")
        table = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(table, dict) or any(
            not isinstance(value, str) for value in table.values()
        ):
            raise TypeError(f"{path} must be a string-to-string JSON object")
        if expected is None:
            expected = set(table)
        if set(table) != expected:
            missing = sorted(expected - set(table))
            extra = sorted(set(table) - expected)
            raise ValueError(f"{language}: missing={missing}, extra={extra}")
        values[language] = table
    return values


def _shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def render_shell(values: dict[str, dict[str, str]]) -> str:
    lines = [
        "# Generated by packaging/i18n/render.py; do not hand-edit.",
        "spacr_install_language() {",
        '  spacr_locale="${SPACR_INSTALL_LANGUAGE:-${LC_ALL:-${LC_MESSAGES:-${LANG:-}}}}"',
        '  if [ -z "$spacr_locale" ] && command -v defaults >/dev/null 2>&1; then',
        '    spacr_locale="$(defaults read -g AppleLocale 2>/dev/null || true)"',
        "  fi",
        '  case "${spacr_locale:-en}" in',
        "    [sS][vV]*) echo sv ;; [dD][eE]*) echo de ;; [eE][sS]*) echo es ;; [zZ][hH]*) echo zh_CN ;;",
        "    [pP][tT]*) echo pt ;; [hH][iI]*) echo hi ;; [kK][oO]*) echo ko ;; [iI][sS]*) echo is ;; [fF][rR]*) echo fr ;;",
        "    *) echo en ;;",
        "  esac",
        "}",
        'SPACR_INSTALL_LANGUAGE_RESOLVED="$(spacr_install_language)"',
        "spacr_say() {",
        '  spacr_key=$1; shift',
        '  case "$SPACR_INSTALL_LANGUAGE_RESOLVED:$spacr_key" in',
    ]
    for language in LANGUAGES:
        for key, value in values[language].items():
            if key == "language_name":
                continue
            lines.append(
                f"    {language}:{key}) printf "
                f"{_shell_quote(value + chr(10))} \"$@\" ;;"
            )
    lines.extend([
        "    *) printf '%s\\n' \"$spacr_key\" ;;",
        "  esac",
        "}",
        "",
    ])
    return "\n".join(lines)


def _ps_quote(value: str) -> str:
    # PowerShell accepts the typographic single quotation marks below as
    # string delimiters too.  Each delimiter must therefore be doubled inside
    # a single-quoted literal, just like an ASCII apostrophe.
    for delimiter in ("'", "\u2018", "\u2019", "\u201b"):
        value = value.replace(delimiter, delimiter * 2)
    return "'" + value + "'"


def _ps_format(value: str) -> str:
    import re

    index = 0

    def replace(_match) -> str:
        nonlocal index
        marker = "{" + str(index) + "}"
        index += 1
        return marker

    return re.sub(r"%(?:\d+\$)?[sd]", replace, value)


def render_powershell(values: dict[str, dict[str, str]]) -> str:
    lines = [
        "# Generated by packaging/i18n/render.py; do not hand-edit.",
        "$SpacrInstallerMessages = @{",
    ]
    for language in LANGUAGES:
        lines.append(f"  {_ps_quote(language)} = @{{")
        for key, value in values[language].items():
            lines.append(
                f"    {_ps_quote(key)} = {_ps_quote(_ps_format(value))}"
            )
        lines.append("  }")
    lines.extend([
        "}",
        "$SpacrInstallerLanguage = if ($env:SPACR_INSTALL_LANGUAGE) { $env:SPACR_INSTALL_LANGUAGE } else { [Globalization.CultureInfo]::CurrentUICulture.Name }",
        "$SpacrInstallerLanguage = $SpacrInstallerLanguage.Replace('-', '_').ToLowerInvariant()",
        "if ($SpacrInstallerLanguage.StartsWith('zh')) { $SpacrInstallerLanguage = 'zh_CN' } else { $SpacrInstallerLanguage = $SpacrInstallerLanguage.Split('_')[0] }",
        "if (-not $SpacrInstallerMessages.ContainsKey($SpacrInstallerLanguage)) { $SpacrInstallerLanguage = 'en' }",
        "function Get-SpacrInstallerMessage {",
        "  param([Parameter(Mandatory=$true)][string]$Key, [object[]]$Values = @())",
        "  $Text = $SpacrInstallerMessages[$SpacrInstallerLanguage][$Key]",
        "  if ($Values.Count) { return $Text -f $Values }",
        "  return $Text",
        "}",
        "",
    ])
    return "\n".join(lines)


def _nsis_escape(value: str) -> str:
    escaped = value.replace("$", "$$").replace('"', '$\\\"').replace(
        "\n", "$\\r$\\n"
    )
    return escaped.replace("%s", "$0")


def render_nsis(values: dict[str, dict[str, str]]) -> str:
    keys = (
        "nsis_launch", "nsis_gpu", "nsis_application",
        "nsis_downloading", "nsis_failed", "nsis_uninstall",
    )
    lines = ["; Generated by packaging/i18n/render.py; do not hand-edit."]
    for language, nsis_name in NSIS_LANGUAGE.items():
        lines.append(f'!insertmacro MUI_LANGUAGE "{nsis_name}"')
        for key in keys:
            lines.append(
                f'LangString SPACR_{key.upper()} ${{LANG_{nsis_name.upper()}}} '
                f'"{_nsis_escape(values[language][key])}"'
            )
    return "\n".join(lines) + "\n"


def embed_unix(source: Path, output: Path, version: str) -> None:
    """Embed generated shell messages into a standalone Unix installer."""
    text = source.read_text(encoding="utf-8")
    begin = "# @SPACR_INSTALLER_MESSAGES_BEGIN@"
    end = "# @SPACR_INSTALLER_MESSAGES_END@"
    start = text.find(begin)
    finish = text.find(end)
    if start < 0 or finish < start:
        raise ValueError(f"{source} is missing installer-message markers")
    finish += len(end)
    messages = (OUTPUT_DIR / "installer_messages.sh").read_text(
        encoding="utf-8"
    ).rstrip()
    # Keep the sentinels in standalone installers.  Besides documenting where
    # generated content begins, this makes embedding idempotent and lets tests
    # prove that no source surrounding the catalog was lost.
    embedded = f"{begin}\n{messages}\n{end}"
    rendered = text[:start] + embedded + text[finish:]
    rendered = rendered.replace("@SPACR_VERSION@", version)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--audit", action="store_true")
    parser.add_argument("--embed-unix", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--version", default="@SPACR_VERSION@")
    args = parser.parse_args()
    values = catalogs()
    if args.audit:
        print(
            f"verified installer locales: languages={len(values)} "
            f"strings={len(values['en'])}"
        )
        return 0
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "installer_messages.sh").write_text(
        render_shell(values), encoding="utf-8",
    )
    (OUTPUT_DIR / "installer_messages.ps1").write_text(
        render_powershell(values), encoding="utf-8",
    )
    (OUTPUT_DIR / "installer_messages.nsh").write_text(
        render_nsis(values), encoding="utf-8",
    )
    if args.embed_unix:
        if args.output is None:
            parser.error("--embed-unix requires --output")
        embed_unix(args.embed_unix, args.output, args.version)
    print(
        f"rendered installer locale resources: languages={len(values)} "
        f"strings={len(values['en'])}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
