#!/usr/bin/env python3
"""Write a reproducible coverage report for every shipped localization."""
from __future__ import annotations

import argparse
from importlib import import_module
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
# Resolve the catalogs from this checkout even when another editable spaCR
# installation is active.  This report is a release artifact; silently reading
# a different worktree can make stale catalogs look complete.
if str(ROOT) in sys.path:
    sys.path.remove(str(ROOT))
sys.path.insert(0, str(ROOT))
LANGUAGES = ("sv", "de", "es", "zh_CN", "pt", "hi", "ko", "is", "fr")
DISPLAY = {
    "sv": "Swedish", "de": "German", "es": "Spanish",
    "zh_CN": "Simplified Chinese", "pt": "Portuguese", "hi": "Hindi",
    "ko": "Korean", "is": "Icelandic", "fr": "French",
}


def _runtime_tables(module) -> tuple[dict, ...]:
    return (
        module.SETTING_LABELS,
        module.SETTING_TOOLTIPS,
        module.CATEGORY_HELP,
        module.UI,
        module.MODULE_SUMMARIES,
    )


def build_report() -> str:
    english = import_module("spacr.qt.i18n_catalogs.en")
    english_tables = (
        english.SETTING_LABELS,
        english.SETTING_TOOLTIPS,
        {key: key for key in english.CATEGORY_SOURCES},
        {key: key for key in english.UI_SOURCES},
        english.MODULE_SUMMARIES,
    )
    api_root = ROOT / "docs" / "source" / "_static" / "i18n" / "api"
    english_api = json.loads((api_root / "en.json").read_text(encoding="utf-8"))
    english_installer = json.loads((
        ROOT / "packaging" / "i18n" / "en.json"
    ).read_text(encoding="utf-8"))

    rows = []
    for language in LANGUAGES:
        module = import_module(f"spacr.qt.i18n_catalogs.{language}")
        tables = _runtime_tables(module)
        runtime_total = sum(len(table) for table in english_tables)
        runtime_present = sum(
            len(set(source) & set(target))
            for source, target in zip(english_tables, tables)
        )
        runtime_changed = sum(
            target.get(key) != value
            for source, target in zip(english_tables, tables)
            for key, value in source.items()
        )
        installer = json.loads((
            ROOT / "packaging" / "i18n" / f"{language}.json"
        ).read_text(encoding="utf-8"))
        api = json.loads((
            api_root / f"{language}.json"
        ).read_text(encoding="utf-8"))
        api_fresh = sum(
            api["symbols"].get(key, {}).get("source_sha256")
            == record["source_sha256"]
            and bool(api["symbols"].get(key, {}).get("text", "").strip())
            for key, record in english_api["symbols"].items()
        )
        readme = (
            ROOT / "docs" / "i18n" / "readme" / f"README.{language}.rst"
        )
        rows.append((
            DISPLAY[language], runtime_present, runtime_total, runtime_changed,
            len(installer), len(english_installer), api_fresh,
            len(english_api["symbols"]), readme.stat().st_size,
        ))

    lines = [
        "# spaCR localization coverage",
        "",
        "Generated by `python tools/audit_i18n_coverage.py --write`. Exact "
        "coverage means the key exists and is source-current; an unchanged "
        "count can legitimately include scientific identifiers and product "
        "names.",
        "",
        "| Language | Runtime entries | Non-English runtime values | Installer strings | Fresh API docstrings | README bytes |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for (
        name, present, total, changed, installer_count, installer_total,
        api_fresh, api_total, readme_bytes,
    ) in rows:
        lines.append(
            f"| {name} | {present}/{total} | {changed}/{total} | "
            f"{installer_count}/{installer_total} | {api_fresh}/{api_total} | "
            f"{readme_bytes:,} |"
        )
    lines.extend([
        "",
        "Runtime entries comprise setting labels, authored setting tooltips, "
        "category explanations, static Qt text, and all registered module "
        "summaries. English source text remains the safe fallback.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    report = build_report()
    if args.write:
        path = ROOT / "docs" / "i18n" / "COVERAGE.md"
        path.write_text(report, encoding="utf-8")
        print(path)
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
