#!/usr/bin/env python
"""Regenerate the settings reference in every shipped notebook.

Each generated section has a readable Markdown reference, one or more
categorized settings cells, and the function call that consumes those
settings. Descriptions come from the live spaCR tooltip table or the
function's scientific-Python docstring; they are never copied into executable
code. Organelle configuration is isolated in its own cell because that surface
is substantially larger than the other segmentation groups. A regeneration
test keeps notebooks synchronized with API changes.

Usage::

    python tools/build_notebook_settings.py           # rewrite
    python tools/build_notebook_settings.py --check    # exit 1 if stale

The generator supports three API shapes:

``factory``
    The function takes a settings dict and a ``spacr.settings`` helper
    declares its keys. Keys and defaults come from calling that helper on an
    empty dict; descriptions come from :data:`spacr.settings.tooltips`.

``signature``
    The function takes ordinary keyword arguments -- ``custom_volcano_plot``
    has nine, ``ml_analysis`` twenty-eight. Names and defaults come from
    :func:`inspect.signature`. Descriptions come from the function's own
    ``Parameters`` section or ``:param`` field, with the registered tooltip
    table as a fallback when the docstring omits a parameter.

``source``
    The function takes a settings dict and NOTHING DECLARES ITS KEYS: it
    reads ``settings.get('x', default)`` inline. The keys are recovered by
    walking the function's AST. The Markdown reference identifies this weaker
    source so readers know that branch-specific keys may be absent.
"""
from __future__ import annotations

import argparse
import ast
import importlib
import inspect
import json
import re
import sys
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

REPO = Path(__file__).resolve().parent.parent
NOTEBOOKS = REPO / "Notebooks"

# Running ``python tools/build_notebook_settings.py`` otherwise puts only the
# tools directory at the front of sys.path.  In an editable installation that
# can import a different spaCR checkout than the notebooks being regenerated.
# The drift guard imports from this checkout, so the command must do the same.
repo_text = str(REPO)
if sys.path[0] != repo_text:
    sys.path.insert(0, repo_text)

# Freeze the core tooltip table before importing any pipeline. Optional
# dependency availability changes which pipeline modules can register, but it
# must never change the wording of a shared setting in a committed notebook.
# Module-owned keys absent from this snapshot still fall back to the complete
# post-registration table in ``tooltip_for`` below.
from spacr.settings import tooltips as _CORE_TOOLTIP_TABLE  # noqa: E402

CORE_TOOLTIPS = dict(_CORE_TOOLTIP_TABLE)

#: Legacy source marker retained so existing notebooks can be migrated.
MARKER = "# Generated by tools/build_notebook_settings.py — do not edit by hand."

#: Heading of the generated Markdown reference.
SECTION_TITLE = "## 3. Settings and API reference"

#: Metadata values used to find generated cells without putting prose in code.
HELP_CELL_KIND = "settings-help"
SETTINGS_CELL_KIND = "settings"
ORGANELLE_CELL_KIND = "settings-organelle"

#: Root of the published sphinx-autoapi tree.
API_BASE = "https://einarolafsson.github.io/spacr/api"

# Purpose, recommended use, and primary outputs for each maintained notebook.
# Keeping this prose beside the generator prevents structural regeneration
# from restoring informal or scientifically imprecise hand-written text.
NOTEBOOK_OVERVIEWS = {
    "01_generate_masks.ipynb": (
        "Generate masks",
        "Generate per-object masks for cells, nuclei, pathogens, and "
        "organelles from microscopy images.",
        "Use for static microscopy acquisitions before object measurement, "
        "cropping, annotation, or classification.",
        "Per-object label images under `masks/` and merged image-mask arrays "
        "under `merged/`.",
    ),
    "01b_generate_timelapse_masks.ipynb": (
        "Generate and track timelapse masks",
        "Generate masks from time-series microscopy images and link selected "
        "objects across consecutive frames.",
        "Use when the acquisition contains a time axis and object identity "
        "must be preserved across frames.",
        "Per-frame masks, merged image-mask arrays, tracking tables, and "
        "time-series movies.",
    ),
    "02_measure_and_crop.ipynb": (
        "Measure objects and crop images",
        "Compute per-object morphology, intensity, and spatial measurements "
        "from merged image-mask arrays, with optional object-centred crops.",
        "Use after segmentation when quantitative features or classifier "
        "training images are required.",
        "`measurements/measurements.db` and, when enabled, object crops under "
        "`data/`.",
    ),
    "03_classify_computer_vision.ipynb": (
        "Classify images with a neural network",
        "Train a convolutional image classifier from labelled object crops "
        "and apply it to the experimental dataset.",
        "Use when phenotype classes are visually distinguishable but are not "
        "adequately represented by predefined measurements.",
        "A trained model, held-out performance metrics, and per-object class "
        "probabilities or scores.",
    ),
    "04_classify_machine_learning.ipynb": (
        "Classify objects from measured features",
        "Fit a supervised tabular classifier to per-object measurements and "
        "apply it to the full dataset.",
        "Use when morphology, intensity, or spatial measurements provide an "
        "interpretable representation of the phenotype.",
        "Per-object predictions, validation metrics, feature importance, and "
        "SHAP summaries when supported.",
    ),
    "05_map_barcodes.ipynb": (
        "Map sequencing reads to microplate wells",
        "Process amplicon sequencing reads and quantify guide-RNA assignments "
        "for each microplate well.",
        "Use after pooled-screen sequencing to construct the guide-count "
        "matrix required for genotype-phenotype analysis.",
        "Per-well guide counts and sequencing quality-control summaries.",
    ),
    "06_regression.ipynb": (
        "Estimate genotype-phenotype associations",
        "Estimate guide- or gene-level effects by modelling phenotype scores "
        "as a function of guide abundance.",
        "Use after phenotype scores and matched guide-count tables have been "
        "generated for the same experimental wells.",
        "Effect estimates, uncertainty or resampling support, adjusted "
        "significance values, diagnostic plots, and ranked findings.",
    ),
    "07_image_umap.ipynb": (
        "Embed object images",
        "Compute a two-dimensional embedding of single-object images or "
        "features and display representative objects in embedding space.",
        "Use for exploratory assessment of phenotypic structure, batch "
        "effects, and outlying experimental groups.",
        "Embedding coordinates and an image-annotated embedding figure.",
    ),
    "08_train_cellpose.ipynb": (
        "Train a Cellpose model",
        "Fine-tune a Cellpose segmentation model using annotated microscopy "
        "images and corresponding reference masks.",
        "Use when available pretrained models do not adequately segment the "
        "object type or imaging condition.",
        "A trained Cellpose checkpoint and training diagnostics.",
    ),
    "09_apply_cellpose.ipynb": (
        "Apply a Cellpose model",
        "Apply a pretrained or custom Cellpose model to a microscopy image "
        "collection.",
        "Use for direct segmentation outside the complete mask-generation "
        "pipeline or for evaluating a newly trained model on unlabeled data.",
        "A label image for each processed input image and associated object "
        "measurements when enabled.",
    ),
    "10_test_cellpose.ipynb": (
        "Evaluate a Cellpose model",
        "Compare predicted masks with reference masks using per-image "
        "segmentation metrics.",
        "Use to compare candidate models on a common held-out dataset before "
        "large-scale application.",
        "Per-image evaluation metrics and aggregate performance summaries.",
    ),
    "11_activation_maps.ipynb": (
        "Generate activation maps",
        "Estimate the image regions contributing to a trained classifier's "
        "predictions using saliency or activation-mapping methods.",
        "Use after model validation to examine whether predictive evidence is "
        "spatially consistent with the intended biological phenotype.",
        "Per-image activation overlays and class-level aggregate maps.",
    ),
    "12_recruitment.ipynb": (
        "Quantify molecular recruitment",
        "Quantify fluorescent-marker enrichment at a pathogen or vacuole "
        "relative to the surrounding cellular compartment.",
        "Use for host-pathogen experiments in which spatial redistribution of "
        "a marker is the principal phenotype.",
        "Per-object recruitment measurements and condition-level summaries.",
    ),
    "13_plaque_assay.ipynb": (
        "Analyze a plaque assay",
        "Segment plaques and quantify plaque number and area for each image "
        "or well.",
        "Use for lytic-cycle assays that quantify disruption of a host-cell "
        "monolayer.",
        "Per-plaque measurements and per-well count and area summaries.",
    ),
    "14_motility_assay.ipynb": (
        "Analyze object motility",
        "Generate and track time-series masks, then quantify trajectory, "
        "velocity, displacement, and infection-related quality control.",
        "Use for time-series acquisitions in which movement is the primary "
        "phenotype and tracked merged arrays have not yet been generated.",
        "Tracked masks, per-track measurements, well-level motility summaries, "
        "and quality-control figures.",
    ),
    "15_replication.ipynb": (
        "Quantify intracellular replication",
        "Estimate intracellular parasite number per vacuole and compare count "
        "distributions across experimental groups.",
        "Use after parasite and parent-compartment objects have been measured.",
        "Per-vacuole parasite counts and group-level replication summaries.",
    ),
    "16_invasion.ipynb": (
        "Quantify invasion",
        "Classify pathogens as intracellular or extracellular using "
        "differential-staining measurements and summarize invasion efficiency.",
        "Use for invasion or attachment assays with an extracellular marker.",
        "Per-object invasion labels and per-well or per-condition invasion "
        "estimates.",
    ),
    "17_endodyogeny.ipynb": (
        "Quantify endodyogeny",
        "Classify intracellular replication states from pathogen size and "
        "summarize their frequencies across experimental groups.",
        "Use when parasite division states are represented by approximately "
        "log2-scaled object-size classes.",
        "Per-object replication-state assignments and group-level "
        "proportions.",
    ),
    "18_percent_positive.ipynb": (
        "Estimate percent positive",
        "Classify objects relative to an intensity threshold and estimate the "
        "positive fraction for each experimental unit.",
        "Use for binary marker-expression phenotypes with an interpretable "
        "measurement threshold.",
        "Per-object threshold assignments and per-well positive fractions.",
    ),
    "19_count_phenotypes.ipynb": (
        "Count annotated phenotypes",
        "Count objects assigned to each annotation or predicted phenotype "
        "class within experimental groups.",
        "Use after manual annotation or classification when class abundance "
        "is the required outcome.",
        "A tidy table of phenotype counts by experimental group.",
    ),
    "20_activation_analysis.ipynb": (
        "Analyze activation maps",
        "Aggregate image-attribution maps and compare attribution summaries "
        "across model classes.",
        "Use after activation-map generation to quantify class-specific "
        "patterns of predictive evidence.",
        "Class-level attribution statistics and comparison figures.",
    ),
    "21_model_knowledge_transfer.ipynb": (
        "Transfer knowledge between models",
        "Train a student image classifier using predictions from one or more "
        "teacher models.",
        "Use when adapting validated predictive information to a related "
        "dataset or consolidating teacher models into a student architecture.",
        "A trained student model and recorded training provenance.",
    ),
    "22_model_fusion.ipynb": (
        "Fuse compatible models",
        "Combine parameters from compatible trained image-classifier "
        "checkpoints using a specified aggregation method.",
        "Use when models share an architecture and parameterization and their "
        "combined weights are scientifically justified.",
        "A fused model checkpoint.",
    ),
    "23_compare_reads_to_scores.ipynb": (
        "Compare sequencing reads with phenotype scores",
        "Join per-well guide abundance with imaging-derived phenotype scores "
        "and quantify their association.",
        "Use as a plate-registration and data-consistency check before "
        "regression analysis.",
        "Joined per-well data and correlation figures.",
    ),
    "24_interpret_vision_model.ipynb": (
        "Interpret a vision-model score",
        "Model vision-classifier outputs using measured morphology and "
        "intensity features to identify associated quantitative attributes.",
        "Use to relate image-model predictions to interpretable cellular "
        "measurements while retaining grouped validation.",
        "Surrogate-model fidelity metrics and ranked feature explanations.",
    ),
    "25_score_heatmap.ipynb": (
        "Generate score heatmaps",
        "Arrange per-well phenotype scores in microplate coordinates and "
        "compare score tables when multiple inputs are supplied.",
        "Use to assess spatial artifacts, gradients, and plate-position "
        "effects.",
        "Microplate heatmaps and score-comparison summaries.",
    ),
    "26_sequencing_stats.ipynb": (
        "Evaluate sequencing quality",
        "Summarize sequencing depth, read quality, consensus, and guide-count "
        "distributions.",
        "Use after barcode mapping and before downstream association analysis.",
        "Sequencing quality-control figures and threshold summaries.",
    ),
    "27_post_regression_analysis.ipynb": (
        "Analyze regression results",
        "Derive downstream guide correlations, ranked findings, and figures "
        "from a completed regression analysis.",
        "Use after model fitting when additional result summaries are required.",
        "Ranked result tables and gene- or guide-level diagnostic figures.",
    ),
    "28_go_term_enrichment.ipynb": (
        "Analyze gene-ontology enrichment",
        "Test whether a selected gene set is enriched for annotated gene "
        "ontology categories.",
        "Use after defining a statistically supported gene set and an "
        "appropriate background population.",
        "Enrichment statistics and category-level visualizations.",
    ),
    "29_gene_phenotype_plots.ipynb": (
        "Plot gene phenotypes",
        "Display selected gene-level phenotype estimates relative to the "
        "screen-wide distribution.",
        "Use to contextualize specific genes after association analysis.",
        "Gene-level phenotype figures with uncertainty when available.",
    ),
    "30_volcano_plot.ipynb": (
        "Generate a volcano plot",
        "Display effect estimates against negative log10-transformed "
        "p-values and annotate selected findings.",
        "Use as a compact summary of a completed differential or regression "
        "analysis.",
        "A volcano plot saved with the configured dimensions and file format.",
    ),
}

# Current desktop routes for API notebooks whose workflows were consolidated
# into a host module.  These are navigation aids only: the notebooks continue
# to call the stable public Python functions documented below.
NOTEBOOK_DESKTOP_ROUTES = {
    "01b_generate_timelapse_masks.ipynb": "Mask → Timelapse",
    "03_classify_computer_vision.ipynb": "Classify → Computer Vision",
    "04_classify_machine_learning.ipynb": "Classify → Machine Learning",
    "08_train_cellpose.ipynb": "Make Masks → Cellpose Workbench → Train",
    "09_apply_cellpose.ipynb": "Make Masks → Cellpose Workbench → Apply",
    "14_motility_assay.ipynb": (
        "Mask → Timelapse, followed by Measure → Motility Assay"
    ),
    "24_interpret_vision_model.ipynb": "Classify → Explain CV Model",
    "30_volcano_plot.ipynb": "Regression → Volcano Explorer",
}


# ---------------------------------------------------------------------------
# Which function a notebook drives
# ---------------------------------------------------------------------------

def declared_functions(notebook: dict) -> List[str]:
    """Return the callables named in the notebook's function section.

    Most notebooks call one public entry point. The motility notebook is an
    intentional two-stage workflow: it first generates and tracks masks, then
    computes motility measurements from the resulting arrays. Only paths in
    the dedicated function cell are considered; links in later guidance do
    not create unused settings dictionaries.
    """
    for cell in notebook.get("cells", []):
        if cell.get("cell_type") != "markdown":
            continue
        text = "".join(cell.get("source", []))
        if (("function" in text and "this notebook runs" in text)
                or text.startswith("## 2. API entry point")):
            explicit = cell.get("metadata", {}).get("spacr", {}).get(
                "functions")
            if isinstance(explicit, list) and all(
                    isinstance(item, str) for item in explicit):
                return list(dict.fromkeys(explicit))
            matches = re.findall(r"`(spacr\.[A-Za-z_0-9.]+)`", text)
            # Legacy function cells occasionally mention a related API in the
            # summary. Only the first path is the entry point unless explicit
            # metadata declares a multi-stage workflow.
            return matches[:1]
    return []


def resolve(dotted: str):
    """Import ``spacr.module.function`` and return the callable, or None."""
    module_name, _, attr = dotted.rpartition(".")
    try:
        return getattr(importlib.import_module(module_name), attr)
    except (ImportError, AttributeError):
        return None


# ---------------------------------------------------------------------------
# The three shapes
# ---------------------------------------------------------------------------

def _module_from_registry(dotted: str) -> Optional[Any]:
    """Return the CLI module registered for ``dotted``, when available."""
    from spacr.cli import MODULES

    module_name, _, attr = dotted.rpartition(".")
    return next((module for module in MODULES.values()
                 if module.module_name == module_name
                 and module.func_name == attr), None)


def _factory_from_registry(dotted: str) -> Optional[Any]:
    """Return the defaults helper registered for an entry point.

    The CLI registry is shared with the GUI and includes helpers that live
    outside :mod:`spacr.settings`. Reusing it keeps built-in and plugin apps
    consistent without maintaining another entry-point mapping.
    """
    module = _module_from_registry(dotted)
    if module is not None:
        if module.defaults_entry:
            return resolve(module.defaults_entry.replace(":", "."))
        if module.defaults:
            import spacr.settings as settings_module
            return getattr(settings_module, module.defaults, None)
    return None


def _settings_factory(func) -> Optional[Any]:
    """The ``spacr.settings`` helper this function canonicalizes through.

    The fallback for a function the CLI does not register: look for a
    settings helper NAMED IN ITS OWN SOURCE, which is the only definition
    that cannot go out of step with what actually runs. A name-convention
    guess would happily pair a function with a helper it never calls.
    """
    import spacr.settings as settings_module

    candidates = [
        name for name in dir(settings_module)
        if "settings" in name and callable(getattr(settings_module, name, None))
    ]
    try:
        source = inspect.getsource(func)
    except (OSError, TypeError):
        return None
    named = [name for name in candidates if re.search(rf"\b{name}\b", source)]
    if not named:
        return None
    # Longest name wins: `set_default_settings_preprocess_generate_masks`
    # contains no other candidate, but a short generic helper might appear
    # inside a longer one's name.
    named.sort(key=len, reverse=True)
    return getattr(settings_module, named[0])


def _takes_settings_dict(func) -> bool:
    try:
        return "settings" in inspect.signature(func).parameters
    except (TypeError, ValueError):
        return False


def keys_from_factory(factory) -> Dict[str, Any]:
    """Every key the helper declares, by calling it on an empty dict."""
    try:
        result = factory({})
    except Exception:
        return {}
    return dict(result) if isinstance(result, dict) else {}


def keys_from_signature(func) -> Dict[str, Any]:
    """Keyword parameters and their defaults."""
    out: Dict[str, Any] = {}
    try:
        params = inspect.signature(func).parameters
    except (TypeError, ValueError):
        return out
    for name, param in params.items():
        if param.kind in (param.VAR_POSITIONAL, param.VAR_KEYWORD):
            continue
        out[name] = None if param.default is param.empty else param.default
    return out


def keys_from_source(func) -> Dict[str, Any]:
    """Keys the function reads off its ``settings`` argument.

    Walks the AST rather than the text, so a key inside a comment or a
    string is not mistaken for one that is read.
    """
    try:
        source = textwrap.dedent(inspect.getsource(func))
        tree = ast.parse(source)
    except (OSError, TypeError, SyntaxError):
        return {}
    found: Dict[str, Any] = {}
    for node in ast.walk(tree):
        if (isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr in ("get", "setdefault")
                and isinstance(node.func.value, ast.Name)
                and node.func.value.id == "settings"
                and node.args
                and isinstance(node.args[0], ast.Constant)
                and isinstance(node.args[0].value, str)):
            default: Any = None
            if len(node.args) > 1:
                try:
                    default = ast.literal_eval(node.args[1])
                except (ValueError, SyntaxError):
                    default = None
            found.setdefault(node.args[0].value, default)
        elif (isinstance(node, ast.Subscript)
                and isinstance(node.value, ast.Name)
                and node.value.id == "settings"
                and isinstance(node.slice, ast.Constant)
                and isinstance(node.slice.value, str)):
            found.setdefault(node.slice.value, None)
    return found


def surface(func, dotted: str = "") -> Tuple[str, Dict[str, Any]]:
    """``(shape, {key: default})`` for one function.

    :param dotted: the ``spacr.module.function`` path, so the CLI registry
        can be consulted before anything is inferred.
    """
    if _takes_settings_dict(func):
        for factory in (_factory_from_registry(dotted) if dotted else None,
                        _settings_factory(func)):
            if factory is None:
                continue
            keys = keys_from_factory(factory)
            if keys:
                return "factory", keys
        return "source", keys_from_source(func)
    return "signature", keys_from_signature(func)


def notebook_surface(
    func,
    dotted: str,
    *,
    notebook_name: str = "",
) -> Tuple[str, Dict[str, Any]]:
    """Return the editable settings exposed by the corresponding module.

    The mask implementation retains timelapse and motility defaults for old
    settings files, but those controls now belong to dedicated modules. The
    notebooks mirror the current module boundaries rather than exposing
    compatibility-only keys.  The motility notebook deliberately uses the
    timelapse preprocessing function as its first stage, but presents only
    the shared mask settings there; its second stage owns the motility
    controls.  ``notebook_name`` distinguishes that workflow from the
    dedicated Timelapse notebook without changing either public API.
    """
    shape, keys = surface(func, dotted)
    module = _module_from_registry(dotted)
    app_key = getattr(module, "key", "")
    if app_key not in {"mask", "timelapse", "motility"}:
        return shape, keys

    from spacr.settings import (
        categories,
        motility_advanced_settings,
        motility_settings,
        timelapse_settings,
    )

    timelapse_keys = (
        set(timelapse_settings)
        | set(categories["4D Settings (Beta)"])
        | {"timelapse"}
    )
    motility_keys = (set(motility_settings)
                     | set(motility_advanced_settings)
                     | {"motility_analysis"})

    profile = {
        "01_generate_masks.ipynb": "general",
        "01b_generate_timelapse_masks.ipynb": "timelapse",
        "14_motility_assay.ipynb": "motility",
    }.get(notebook_name, app_key)

    if profile == "general" or (profile == "motility" and app_key == "timelapse"):
        hidden = motility_keys | timelapse_keys
        keys = {key: value for key, value in keys.items()
                if key not in hidden}
    elif profile == "timelapse":
        keys = {key: value for key, value in keys.items()
                if key not in motility_keys}
    elif profile == "motility":
        keys = {key: value for key, value in keys.items()
                if key not in timelapse_keys and key != "motility_analysis"}
    return shape, keys


# ---------------------------------------------------------------------------
# Tooltips, always read now and never pasted
# ---------------------------------------------------------------------------

def param_docs(func) -> Dict[str, str]:
    """Return parameter descriptions from RST or numpydoc docstrings."""
    doc = inspect.getdoc(func) or ""
    out: Dict[str, str] = {}
    for match in re.finditer(
            r"^:param\s+(\w+):\s*(.+?)(?=^\s*:(?:param|returns|raises|rtype)\b|\Z)",
            doc, re.S | re.M):
        out[match.group(1)] = " ".join(match.group(2).split())

    # Scientific-Python APIs use a ``Parameters`` section rather than RST
    # fields.  Stop at the next underlined section heading so Returns/Raises
    # entries cannot be mistaken for parameters.
    lines = doc.splitlines()
    section = next((
        index for index in range(len(lines) - 1)
        if lines[index].strip() == "Parameters"
        and set(lines[index + 1].strip()) == {"-"}
    ), None)
    if section is None:
        return out

    parameter = re.compile(
        r"^([A-Za-z_]\w*(?:\s*,\s*[A-Za-z_]\w*)*)\s*:\s*.+$"
    )
    index = section + 2
    while index < len(lines):
        if (index + 1 < len(lines) and lines[index].strip()
                and set(lines[index + 1].strip()) == {"-"}):
            break
        match = parameter.match(lines[index].strip())
        if match is None:
            index += 1
            continue
        names = [name.strip() for name in match.group(1).split(",")]
        index += 1
        description = []
        while index < len(lines):
            if (index + 1 < len(lines) and lines[index].strip()
                    and set(lines[index + 1].strip()) == {"-"}):
                break
            if parameter.match(lines[index].strip()):
                break
            if lines[index].strip():
                description.append(lines[index].strip())
            index += 1
        rendered = " ".join(description)
        for name in names:
            out.setdefault(name, rendered)
    return out


_REGISTERED = False


def _load_registrations() -> None:
    """Import every pipeline module, so its registered tooltips exist.

    ``spacr.settings.tooltips`` is not complete on import. Six pipelines --
    ``barcode_qc``, ``illumination``, ``convert`` and the rest -- own their
    keys and merge them in from their own module via
    :func:`spacr.settings.register_defaults`, which only runs when that
    module is imported. Read the dict cold and ``dst`` and ``cmap`` look
    undocumented; they are documented by whoever owns them.

    Getting this wrong is not a missing sentence, it is a WRONG one: the
    generator would have written "no description" into a notebook for a key
    that has a perfectly good one.
    """
    global _REGISTERED
    if _REGISTERED:
        return
    from spacr.cli import MODULES
    for module in MODULES.values():
        try:
            importlib.import_module(module.module_name)
        except Exception:
            # A pipeline whose optional dependency is absent still leaves
            # every other pipeline's tooltips loaded.
            pass
    _REGISTERED = True


def tooltip_for(key: str, shape: str, docs: Dict[str, str]) -> str:
    """One sentence describing ``key``, from whichever source declares it."""
    if shape == "signature" and docs.get(key):
        return docs[key]
    if key in CORE_TOOLTIPS:
        return str(CORE_TOOLTIPS[key] or docs.get(key, ""))
    _load_registrations()
    from spacr.settings import tooltips
    return str(tooltips.get(key, "") or docs.get(key, ""))


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

_DYNAMIC_LITERALS = {
    # These factories deliberately size their worker pool from the current
    # machine.  Committing the evaluated integer makes notebooks alternate
    # between a workstation's 28/30 workers and a hosted runner's 1/2.  Keep
    # the executable expression so the documented default remains truthful
    # and regeneration is independent of the machine doing the check.
    ("spacr.core.preprocess_generate_masks", "n_jobs"):
        "max(1, (__import__('os').cpu_count() or 1) - 4)",
    ("spacr.core.preprocess_generate_masks_timelapse", "n_jobs"):
        "max(1, (__import__('os').cpu_count() or 1) - 4)",
    ("spacr.measure.measure_crop", "n_jobs"):
        "max(1, (__import__('os').cpu_count() or 1) - 2)",
    ("spacr.deep_spacr.deep_spacr", "n_jobs"):
        "max(1, (__import__('os').cpu_count() or 1) - 4)",
}


def _literal(value: Any, *, dotted: str = "", key: str = "") -> str:
    """Repr that round-trips, or a portable executable default expression."""
    dynamic = _DYNAMIC_LITERALS.get((dotted, key))
    if dynamic is not None:
        return dynamic
    if isinstance(value, str):
        resource_root = REPO / "spacr" / "resources"
        try:
            relative = Path(value).resolve().relative_to(resource_root.resolve())
        except (OSError, ValueError):
            pass
        else:
            # ``spacr/resources`` intentionally contains data directories,
            # not import packages.  Python 3.9's ``importlib.resources``
            # fallback can also see ``spec.origin is None`` for an editable
            # installation of the parent package.  Anchor at the package's
            # concrete search path instead; wheels are installed as ordinary
            # directories, so this works in source and installed checkouts on
            # every supported Python.
            resource_parts = ("resources", *relative.parts)
            joined = ", ".join(repr(part) for part in resource_parts)
            # Keep package data portable across source checkouts, wheels and
            # hosted CI instead of baking the developer's absolute path into
            # a committed notebook.
            return (
                "str(__import__('pathlib').Path(next(iter("
                "__import__('spacr').__path__))).joinpath("
                f"{joined}))"
            )
    try:
        if ast.literal_eval(repr(value)) == value:
            return repr(value)
    except (ValueError, SyntaxError, TypeError):
        pass
    return f"None  # {type(value).__name__}, set this yourself"


def setting_name(dotted: str, entries: list) -> str:
    """Return the settings-variable name for one notebook entry."""
    if len(entries) == 1:
        return "settings"
    return f"{dotted.rsplit('.', 1)[1]}_settings"


def api_url(dotted: str) -> str:
    """Return the published API URL for a dotted spaCR callable."""
    module_name = dotted.rpartition(".")[0]
    module_path = module_name.replace(".", "/")
    return f"{API_BASE}/{module_path}/index.html#{dotted}"


def _markdown_text(text: str) -> str:
    """Normalize tooltip prose for a Markdown bullet."""
    return (" ".join(str(text).split())
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;"))


def _is_organelle_key(key: str) -> bool:
    """Return True for settings that configure an organelle mask role."""
    from spacr.object_roles import ORGANELLE_ROLES

    return (key in {"number_of_organelles", "summarize_organelles_by"}
            or any(key.startswith(f"{role}_")
                   for role in ORGANELLE_ROLES))


def _category_groups(keys: Dict[str, Any], *, organelle: bool
                     ) -> List[Tuple[str, List[str]]]:
    """Group one settings surface using spaCR's reviewed category registry."""
    from spacr.settings import categories

    wanted = {
        key for key in keys
        if _is_organelle_key(key) is organelle
    }
    groups: List[Tuple[str, List[str]]] = []
    for title, members in categories.items():
        selected = [key for key in members if key in wanted]
        if not selected:
            continue
        wanted.difference_update(selected)
        if organelle and title == "General":
            title = "Organelle input"
        elif organelle and title == "Object filtration":
            title = "Organelle object filtration"
        elif organelle and title == "Intensity handling":
            title = "Organelle intensity handling"
        groups.append((title, selected))
    if wanted:
        groups.append(("Additional settings", sorted(wanted)))
    return groups


_REQUIRED_SETTINGS = {
    "spacr.deep_spacr.generate_activation_map": {"dataset"},
    "spacr.sequencing.graph_sequencing_stats": {"count_data"},
    "spacr.submodules.analyze_percent_positive": {"value_col"},
}

_CONDITIONAL_SETTINGS = {
    "spacr.deep_spacr.generate_activation_map": {"target_layer"},
}


def _setting_status(dotted: str, shape: str, key: str) -> str:
    """Return ``required``, ``conditional`` or ``optional`` for ``key``."""
    if key in _REQUIRED_SETTINGS.get(dotted, set()):
        return "required"
    if key in _CONDITIONAL_SETTINGS.get(dotted, set()):
        return "conditional"
    if shape == "signature":
        func = resolve(dotted)
        try:
            param = inspect.signature(func).parameters[key]
        except (AttributeError, KeyError, TypeError, ValueError):
            pass
        else:
            if param.default is param.empty:
                return "required"
    if key == "src":
        return "required"
    if (dotted in {
            "spacr.core.preprocess_generate_masks",
            "spacr.core.preprocess_generate_masks_timelapse",
        } and key in {
            "cell_channel", "nucleus_channel", "pathogen_channel",
            "organelle_channel",
        }):
        return "conditional"
    return "optional"


def _status_label(status: str) -> str:
    return {
        "required": "Required",
        "conditional": "Conditionally required",
        "optional": "Optional",
    }[status]


def render_help(entries: List[Tuple[str, str, Dict[str, Any], Dict[str, str]]]
                ) -> str:
    """Build the Markdown reference shown above the settings cell."""
    lines = [
        SECTION_TITLE,
        "",
        "Review the parameter definitions here, then edit the values in the "
        "categorized code cells below. Required settings must be supplied. "
        "Optional settings retain the displayed default when unchanged. "
        "Conditionally required settings are necessary only for the indicated "
        "analysis branch. Defaults and descriptions are generated from the "
        "installed spaCR version so that the notebook remains aligned with "
        "the public API.",
    ]
    for dotted, shape, keys, docs in entries:
        lines.extend([
            "",
            f"### [`{dotted}`]({api_url(dotted)})",
            "",
        ])
        if shape == "source":
            lines.extend([
                "> This function does not yet expose a settings factory. The "
                "list below is recovered from direct settings access in its "
                "source, so a key used only on a dynamic branch may be absent.",
                "",
            ])
        if any(_is_organelle_key(key) for key in keys):
            lines.extend([
                "> Organelle parameters are placed in a separate code cell "
                "to keep the primary segmentation configuration readable.",
                "",
            ])
        if len(entries) > 1 and dotted != entries[0][0] and "src" in keys:
            lines.extend([
                "> This stage inherits `src` from the first stage so that "
                "both functions operate on the same dataset.",
                "",
            ])
        for organelle in (False, True):
            for category, members in _category_groups(
                    keys, organelle=organelle):
                lines.extend(["", f"#### {category}", ""])
                for key in members:
                    description = _markdown_text(
                        tooltip_for(key, shape, docs))
                    if not description:
                        description = (
                            "No description is available in this version.")
                    status = _status_label(
                        _setting_status(dotted, shape, key))
                    lines.append(
                        f"- **`{key}`** *({status.lower()})* — {description}")
    lines.extend([
        "",
        "## 4. Run",
        "",
        "After editing the settings cell, run the function cell immediately "
        "below it. Long operations report progress through spaCR's logging "
        "system; set `SPACR_LOG_LEVEL=DEBUG` before starting Jupyter for more "
        "detail.",
    ])
    return "\n".join(lines)


def render_cell(
    entries: List[Tuple[str, str, Dict[str, Any], Dict[str, str]]],
    *,
    organelle: bool = False,
) -> str:
    """Build one categorized settings cell.

    The primary cell creates each dictionary. The organelle cell updates the
    same dictionary, keeping the eventual function call unchanged.
    """
    lines: List[str] = []
    for index, (dotted, shape, keys, _docs) in enumerate(entries):
        groups = _category_groups(keys, organelle=organelle)
        if organelle and not groups:
            continue
        name = setting_name(dotted, entries)
        lines.append(f"{name}.update({{" if organelle else f"{name} = {{")
        for group_index, (category, members) in enumerate(groups):
            if group_index:
                lines.append("")
            lines.append(f"    # {category}")
            for status in ("required", "conditional", "optional"):
                selected = [
                    key for key in members
                    if _setting_status(dotted, shape, key) == status
                ]
                if not selected:
                    continue
                lines.append(f"    # {_status_label(status)} settings")
                for key in selected:
                    value = _literal(keys[key], dotted=dotted, key=key)
                    if (len(entries) > 1 and index > 0 and key == "src"
                            and "src" in entries[0][2]):
                        first_name = setting_name(entries[0][0], entries)
                        value = f"{first_name}['src']"
                    lines.append(
                        f"    {key!r}: {value},")
        lines.append("})" if organelle else "}")
        if index != len(entries) - 1:
            lines.append("")
    return "\n".join(lines)


def render_settings_cells(
    entries: List[Tuple[str, str, Dict[str, Any], Dict[str, str]]],
) -> List[Tuple[str, str]]:
    """Return ``[(generated_kind, source), ...]`` for editable settings."""
    rendered = [(SETTINGS_CELL_KIND, render_cell(entries))]
    if any(_is_organelle_key(key)
           for _dotted, _shape, keys, _docs in entries for key in keys):
        rendered.append((ORGANELLE_CELL_KIND,
                         render_cell(entries, organelle=True)))
    return rendered


def _as_source(text: str) -> List[str]:
    """Notebook JSON stores a cell as a list of lines, newlines included."""
    lines = text.split("\n")
    return [line + "\n" for line in lines[:-1]] + [lines[-1]]


def _render_overview(path: Path) -> Optional[str]:
    """Return the reviewed scientific overview for ``path``."""
    overview = NOTEBOOK_OVERVIEWS.get(path.name)
    if overview is None:
        return None
    title, purpose, use, outputs = overview
    lines = [
        f"# {title}",
        "",
        f"**Purpose.** {purpose}",
        "",
        f"**Recommended use.** {use}",
        "",
        f"**Primary outputs.** {outputs}",
    ]
    desktop_route = NOTEBOOK_DESKTOP_ROUTES.get(path.name)
    if desktop_route:
        lines.extend(["", f"**Desktop route.** {desktop_route}"])
    lines.extend([
        "",
        "---",
        "",
        "> Paths in this notebook are placeholders. Set `src` and any other "
        "required path to the experimental data before execution.",
        "> spaCR writes outputs within, or immediately adjacent to, the "
        "configured source directory unless an explicit output path is set.",
    ])
    return "\n".join(lines)


def _render_function_section(entries) -> str:
    """Return a concise, linked description of the notebook entry points."""
    plural = len(entries) != 1
    lines = [
        f"## 2. API entry point{'s' if plural else ''}",
        "",
        ("This workflow calls the following public functions in sequence:"
         if plural else "This workflow calls the following public function:"),
        "",
    ]
    for dotted, shape, _keys, _docs in entries:
        name = setting_name(dotted, entries)
        func_name = dotted.rsplit(".", 1)[1]
        call = (f"{func_name}(**{name})" if shape == "signature"
                else f"{func_name}({name})")
        lines.extend([
            f"- [`{dotted}`]({api_url(dotted)})",
            "",
            "```python",
            call,
            "```",
            "",
        ])
    lines.append(
        "Parameter definitions and defaults are generated from the same "
        "public API and are listed in the settings reference below.")
    return "\n".join(lines)


def _refresh_notebook_prose(path: Path, notebook: dict, entries) -> None:
    """Replace informal notebook framing with reviewed scientific prose."""
    cells = notebook.get("cells", [])
    overview = _render_overview(path)
    if overview is not None and cells:
        cells[0]["source"] = _as_source(overview)

    for cell in cells:
        if cell.get("cell_type") != "markdown":
            continue
        source = "".join(cell.get("source", []))
        if source.startswith("## 1. Check the install") or source.startswith(
                "## 1. Verify the environment"):
            cell["source"] = _as_source("\n".join([
                "## 1. Verify the environment",
                "",
                "The following cell reports the installed spaCR version. "
                "Import errors must be resolved before the analysis cells "
                "are executed. GPU acceleration is optional and depends on "
                "the selected workflow and installed computational backend.",
            ]))
        elif (("function" in source and "this notebook runs" in source)
              or source.startswith("## 2. API entry point")):
            cell["source"] = _as_source(_render_function_section(entries))
            cell.setdefault("metadata", {}).setdefault("spacr", {})[
                "functions"] = [dotted for dotted, *_rest in entries]
        elif source.startswith("## Where the output went") or source.startswith(
                "## Outputs and next steps"):
            outputs = NOTEBOOK_OVERVIEWS.get(path.name, ("", "", "", ""))[3]
            cell["source"] = _as_source("\n".join([
                "## Outputs and next steps",
                "",
                outputs,
                "",
                "Output directories remain associated with the source dataset, "
                "which preserves plate-level provenance across subsequent "
                "spaCR workflows.",
                "",
                "### Related documentation",
                "",
                "- [Graphical workflow tutorials]"
                "(https://einarolafsson.github.io/spacr/tutorials/)",
                "- [Python API quickstart]"
                "(https://einarolafsson.github.io/spacr/python_api.html)",
            ]))


# ---------------------------------------------------------------------------
# Rewriting one notebook
# ---------------------------------------------------------------------------

def rebuild(path: Path) -> Optional[str]:
    """Return the notebook's new JSON text, or None when it needs no cell."""
    # Factories are extended by module-level registrations.  Load every
    # registered pipeline before asking any factory for its keys; otherwise
    # the first notebook in a process sees a smaller surface than later ones
    # and pytest's prior imports change the generated result.
    _load_registrations()
    notebook = json.loads(path.read_text())
    entries = []
    for dotted in declared_functions(notebook):
        func = resolve(dotted)
        if func is None:
            continue
        shape, keys = notebook_surface(
            func, dotted, notebook_name=path.name
        )
        if keys:
            entries.append((dotted, shape, keys, param_docs(func)))
    if not entries:
        return None

    _refresh_notebook_prose(path, notebook, entries)

    help_source = _as_source(render_help(entries))
    rendered_settings = [
        (kind, _as_source(source))
        for kind, source in render_settings_cells(entries)
    ]
    cells = notebook["cells"]
    retarget_call(cells, entries)

    help_cell = next((cell for cell in cells
                      if _cell_kind(cell) == HELP_CELL_KIND), None)
    if help_cell is None:
        help_cell = next((cell for cell in cells
                          if cell.get("cell_type") == "markdown"
                          and "Every setting this function accepts" in
                          "".join(cell.get("source", []))), None)

    settings_cells = {
        kind: next((cell for cell in cells if _cell_kind(cell) == kind), None)
        for kind, _source in rendered_settings
    }
    if settings_cells[SETTINGS_CELL_KIND] is None:
        settings_cells[SETTINGS_CELL_KIND] = next((
            cell for cell in cells
            if cell.get("cell_type") == "code"
            and "".join(cell.get("source", [])).startswith(MARKER)
        ), None)

    if settings_cells[SETTINGS_CELL_KIND] is None:
        at = _insertion_point(cells)
        help_cell = _markdown_cell(help_source, HELP_CELL_KIND)
        cells.insert(at, help_cell)
        for offset, (kind, source) in enumerate(rendered_settings, 1):
            settings_cells[kind] = _code_cell(source, kind)
            cells.insert(at + offset, settings_cells[kind])
    else:
        for kind, source in rendered_settings:
            settings_cell = settings_cells.get(kind)
            if settings_cell is None:
                settings_cell = _code_cell(source, kind)
                settings_cells[kind] = settings_cell
                cells.insert(cells.index(settings_cells[SETTINGS_CELL_KIND]) + 1,
                             settings_cell)
            else:
                settings_cell["source"] = source
                settings_cell["outputs"] = []
                settings_cell["execution_count"] = None
                _mark_generated(settings_cell, kind)
        if help_cell is None:
            at = cells.index(settings_cells[SETTINGS_CELL_KIND])
            help_cell = _markdown_cell(help_source, HELP_CELL_KIND)
            cells.insert(at, help_cell)
        else:
            help_cell["source"] = help_source
            _mark_generated(help_cell, HELP_CELL_KIND)

    # Remove a formerly generated organelle cell when a function no longer
    # exposes organelle settings.
    live_kinds = {kind for kind, _source in rendered_settings}
    for cell in list(cells):
        if (_cell_kind(cell) == ORGANELLE_CELL_KIND
                and ORGANELLE_CELL_KIND not in live_kinds):
            cells.remove(cell)

    _remove_legacy_setup(cells, help_cell)
    ordered_settings = [settings_cells[kind]
                        for kind, _source in rendered_settings]
    _place_generated_cells(cells, help_cell, ordered_settings)
    _place_run_cell(cells, ordered_settings[-1], entries)
    return json.dumps(notebook, indent=1, ensure_ascii=False) + "\n"


def retarget_call(cells: List[dict], entries) -> None:
    """Make a commented example call consume the generated dictionary.

    Some notebooks formerly carried a call such as::

        # custom_volcano_plot(data_path, metadata_path,
        #                     metadata_column='tagm_location', ...)

    which restated the signature separately from the settings cell. Replacing
    it with ``func(**settings)`` ensures renamed parameters fail visibly.

    Only a cell that is ENTIRELY commented-out calls of this function is
    rewritten. A cell with real code in it is somebody's example and is left
    exactly as it is.
    """
    if len(entries) != 1:
        # A notebook running two pipelines names its dicts per function, so
        # there is no single `settings` to hand anything.
        return
    dotted, shape, _keys, _docs = entries[0]
    name = dotted.rsplit(".", 1)[1]
    # A keyword function is spread; a settings-dict function takes the dict.
    call = f"{name}(**settings)" if shape == "signature" else f"{name}(settings)"
    for cell in cells:
        if cell.get("cell_type") != "code":
            continue
        lines = [line.strip() for line in
                 "".join(cell.get("source", [])).split("\n") if line.strip()]
        if not lines:
            continue
        if all(line.startswith(f"# {name}(") for line in lines):
            cell["source"] = _as_source(call)
            cell["outputs"] = []
            cell["execution_count"] = None
            return


def _cell_kind(cell: dict) -> str:
    """Return the spaCR generator kind stored in cell metadata."""
    metadata = cell.get("metadata", {}).get("spacr", {})
    return str(metadata.get("generated", "")) if isinstance(metadata, dict) else ""


def _mark_generated(cell: dict, kind: str) -> None:
    """Mark a cell as generator-owned without adding prose to executable code."""
    cell.setdefault("id", f"spacr-{kind}")
    metadata = cell.setdefault("metadata", {})
    spacr_metadata = metadata.setdefault("spacr", {})
    spacr_metadata.update({
        "generated": kind,
        "tool": "tools/build_notebook_settings.py",
    })


def _code_cell(source: List[str], kind: str = "") -> dict:
    cell = {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": source}
    if kind:
        _mark_generated(cell, kind)
    return cell


def _markdown_cell(source: List[str], kind: str = "") -> dict:
    cell = {"cell_type": "markdown", "metadata": {}, "source": source}
    if kind:
        _mark_generated(cell, kind)
    return cell


def _remove_legacy_setup(cells: List[dict], help_cell: dict) -> None:
    """Remove the redundant defaults preview that preceded old references."""
    index = next(i for i, cell in enumerate(cells) if cell is help_cell)
    if index and cells[index - 1].get("cell_type") == "code":
        source = "".join(cells[index - 1].get("source", []))
        if "defaults =" in source and "for key in sorted(defaults)" in source:
            cells.pop(index - 1)
            index -= 1
    if index and cells[index - 1].get("cell_type") == "markdown":
        source = "".join(cells[index - 1].get("source", [])).lstrip()
        if source.startswith("## 3. Settings") or source.startswith("## 3. Call it"):
            cells.pop(index - 1)


def _place_generated_cells(cells: List[dict], help_cell: dict,
                           settings_cells: List[dict]) -> None:
    """Place the Markdown reference immediately before editable settings."""
    cells.remove(help_cell)
    for settings_cell in settings_cells:
        cells.remove(settings_cell)
    at = _insertion_point(cells)
    cells.insert(at, help_cell)
    for offset, settings_cell in enumerate(settings_cells, 1):
        cells.insert(at + offset, settings_cell)


def _place_run_cell(cells: List[dict], settings_cell: dict, entries) -> None:
    """Place the function call immediately after the settings dictionary."""
    names = {dotted.rsplit(".", 1)[1] for dotted, *_rest in entries}
    run_cell = None
    for cell in cells:
        if cell is settings_cell or cell.get("cell_type") != "code":
            continue
        source = "".join(cell.get("source", []))
        if any(re.search(rf"\b{re.escape(name)}\s*\(", source)
               for name in names):
            run_cell = cell
            break
    if run_cell is None:
        return

    # The old standalone Run heading separated settings from the call. Its
    # useful logging guidance now lives at the end of the reference cell.
    for cell in list(cells):
        if cell.get("cell_type") != "markdown":
            continue
        source = "".join(cell.get("source", [])).lstrip()
        if source.startswith("## 4. Run it"):
            cells.remove(cell)

    cells.remove(run_cell)
    at = next(i for i, cell in enumerate(cells) if cell is settings_cell)
    cells.insert(at + 1, run_cell)


def _insertion_point(cells: List[dict]) -> int:
    """Return the position before the run heading or final code cell.

    The settings have to be readable BEFORE the cell that consumes them, or
    a reader who runs the notebook top to bottom meets the run first.
    """
    for index, cell in enumerate(cells):
        source = "".join(cell.get("source", [])).lstrip()
        if cell.get("cell_type") == "markdown" and \
                source.startswith("## 4. Run it"):
            return index
    for index in range(len(cells) - 1, -1, -1):
        if cells[index].get("cell_type") == "code":
            return index
    return len(cells)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if any notebook is stale")
    parser.add_argument("--notebooks", default=str(NOTEBOOKS))
    args = parser.parse_args(argv)

    root = Path(args.notebooks)
    stale, written, skipped = [], [], []
    for path in sorted(root.glob("*.ipynb")):
        try:
            new_text = rebuild(path)
        except Exception as exc:
            print(f"  !! {path.name}: {type(exc).__name__}: {exc}")
            stale.append(path.name)
            continue
        if new_text is None:
            skipped.append(path.name)
            continue
        if new_text == path.read_text():
            continue
        if args.check:
            stale.append(path.name)
        else:
            path.write_text(new_text)
            written.append(path.name)

    if skipped:
        print(f"no settings surface, left alone: {len(skipped)}")
    if args.check:
        if stale:
            print("STALE — re-run tools/build_notebook_settings.py:")
            for name in stale:
                print(f"  {name}")
            return 1
        print("every notebook is current")
        return 0
    print(f"rewrote {len(written)} notebook(s)")
    for name in written:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
