"""Keep the Make Masks parameter reference tied to the engine's documented fields.

Read source with AST; do not import Qt, load models or create preferences.
Run with --check to verify the committed include without rewriting it.
"""
from __future__ import annotations

import argparse
import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/source/_generated/make_masks_parameters.rst"
SPECS = (
    ("CPU detectors", "spacr.qt.cpu_modes", "CpuParams"),
    ("Organelle detectors", "spacr.qt.organelle_modes", "MethodParams"),
    ("Image enhancement", "spacr.qt.detect_chain", "Chain"),
)


def render() -> str:
    """Render every NamedTuple field, rejecting undocumented or stale fields."""
    lines = [".. Generated by tools/build_make_masks_reference.py; do not edit.", ""]
    for title, module, class_name in SPECS:
        tree = ast.parse((ROOT / (module.replace(".", "/") + ".py")).read_text())
        cls = next(node for node in tree.body
                   if isinstance(node, ast.ClassDef) and node.name == class_name)
        fields = {node.target.id: ast.unparse(node.value)
                  for node in cls.body if isinstance(node, ast.AnnAssign)
                  and isinstance(node.target, ast.Name) and node.value is not None}
        doc = ast.get_docstring(cls) or ""
        descriptions = {}
        for match in re.finditer(r"^:param (\w+): (.*?)(?=\n:\w|\Z)", doc,
                                 re.MULTILINE | re.DOTALL):
            descriptions[match[1]] = " ".join(match[2].split())
        if fields.keys() != descriptions.keys():
            raise ValueError(f"{module}.{class_name}: fields and parameter prose differ")
        lines += [title, "~" * len(title), "",
                  f"Engine settings: :class:`{module}.{class_name}`. These are",
                  "programmatic defaults; the screen can use mode-specific defaults",
                  "or restore values from the current session.", ""]
        for name, default in fields.items():
            lines += [f"``{name}`` — default ``{default}``",
                      f"    {descriptions[name]}", ""]
    return "\n".join(lines)


def main() -> int:
    """Write the include, or return a failure when --check finds it stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print(f"Stale reference: {OUTPUT.relative_to(ROOT)}")
            return 1
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected)
    print(f"Current: {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
