#!/usr/bin/env python
"""Regenerate the "every setting" cell in every shipped notebook.

Instruction 88. A notebook is the only route into spaCR that does not go
through a settings panel, so it is the one place where a setting can be
INVISIBLE rather than merely badly explained: a reader sees the six keys the
example happened to set and has no way to learn the function reads ninety.

WHY A GENERATOR AND NOT THIRTY EDITED NOTEBOOKS. Fourteen of the thirty
already carried a settings block, hand-made, against a settings dict that
moves every week -- and instruction 61 has already rewritten 454 tooltips
once. A pasted tooltip is a copy that goes stale in silence. Everything here
is read from the installed package AT GENERATION TIME, and
``tests/test_notebook_settings.py`` regenerates and compares, so a new
setting cannot be added without the notebooks gaining it.

Usage::

    python tools/build_notebook_settings.py           # rewrite
    python tools/build_notebook_settings.py --check    # exit 1 if stale

THREE SHAPES, BECAUSE spaCR HAS THREE. Which one applies is decided per
function, not per notebook:

``factory``
    The function takes a settings dict and a ``spacr.settings`` helper
    declares its keys. Keys and defaults come from calling that helper on an
    empty dict; the tooltip comes from :data:`spacr.settings.tooltips`. This
    is the shape the GUI and the CLI already use, and it covers 16 of the 30.

``signature``
    The function takes ordinary keyword arguments -- ``custom_volcano_plot``
    has nine, ``ml_analysis`` twenty-eight. Names and defaults come from
    :func:`inspect.signature` and the tooltip is the function's own
    ``:param`` line. Nine notebooks.

``source``
    The function takes a settings dict and NOTHING DECLARES ITS KEYS: it
    reads ``settings.get('x', default)`` inline. The keys are recovered by
    walking the AST of the function itself. Four notebooks, and the cell
    says where the list came from -- a list read out of a function body is a
    weaker claim than one read off a declaration, and hiding that difference
    would be the dishonest part. Those four should grow real factories; see
    instruction 88.
"""
from __future__ import annotations

import argparse
import ast
import importlib
import inspect
import json
import re
import sys
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

REPO = Path(__file__).resolve().parent.parent
NOTEBOOKS = REPO / "Notebooks"

# Running ``python tools/build_notebook_settings.py`` otherwise puts only the
# tools directory at the front of sys.path.  In an editable installation that
# can import a different spaCR checkout than the notebooks being regenerated.
# The drift guard imports from this checkout, so the command must do the same.
repo_text = str(REPO)
if sys.path[0] != repo_text:
    sys.path.insert(0, repo_text)

#: Marks the generated cell. Its presence is what lets the tool rewrite in
#: place instead of appending a second block on every run.
MARKER = "# Generated by tools/build_notebook_settings.py — do not edit by hand."

#: Heading of the markdown cell that introduces the generated code cell.
SECTION_TITLE = "### Every setting this function accepts"

#: Width the tooltip comments wrap to. Narrow on purpose: a notebook is read
#: in a cell about half a screen wide, and a 200-character trailing comment
#: is one nobody reads.
WRAP = 68


# ---------------------------------------------------------------------------
# Which function a notebook drives
# ---------------------------------------------------------------------------

def declared_functions(notebook: dict) -> List[str]:
    """Dotted paths the notebook itself names as what it runs.

    Read from the "The function this notebook runs" markdown cell rather
    than guessed from the imports: a notebook imports several helpers and
    runs one thing, and the author already wrote down which.
    """
    for cell in notebook.get("cells", []):
        if cell.get("cell_type") != "markdown":
            continue
        text = "".join(cell.get("source", []))
        if "function" in text and "this notebook runs" in text:
            return re.findall(r"`(spacr\.[A-Za-z_0-9.]+)`", text)
    return []


def resolve(dotted: str):
    """Import ``spacr.module.function`` and return the callable, or None."""
    module_name, _, attr = dotted.rpartition(".")
    try:
        return getattr(importlib.import_module(module_name), attr)
    except (ImportError, AttributeError):
        return None


# ---------------------------------------------------------------------------
# The three shapes
# ---------------------------------------------------------------------------

def _factory_from_registry(dotted: str) -> Optional[Any]:
    """The defaults helper ``spacr.cli`` already pairs with this entry point.

    THE REGISTRY IS THE AUTHORITY, and instruction 88 says so: the mapping
    exists for the GUI and the CLI, and a third one written here would be a
    third thing to keep in step. Six pipelines keep their helper outside
    :mod:`spacr.settings` -- ``defaults_entry`` -- and this follows that too,
    so a plugin app's keys resolve the same way a built-in's do.
    """
    from spacr.cli import MODULES

    module_name, _, attr = dotted.rpartition(".")
    for module in MODULES.values():
        if module.module_name != module_name or module.func_name != attr:
            continue
        if module.defaults_entry:
            return resolve(module.defaults_entry.replace(":", "."))
        if module.defaults:
            import spacr.settings as settings_module
            return getattr(settings_module, module.defaults, None)
    return None


def _settings_factory(func) -> Optional[Any]:
    """The ``spacr.settings`` helper this function canonicalizes through.

    The fallback for a function the CLI does not register: look for a
    settings helper NAMED IN ITS OWN SOURCE, which is the only definition
    that cannot go out of step with what actually runs. A name-convention
    guess would happily pair a function with a helper it never calls.
    """
    import spacr.settings as settings_module

    candidates = [
        name for name in dir(settings_module)
        if "settings" in name and callable(getattr(settings_module, name, None))
    ]
    try:
        source = inspect.getsource(func)
    except (OSError, TypeError):
        return None
    named = [name for name in candidates if re.search(rf"\b{name}\b", source)]
    if not named:
        return None
    # Longest name wins: `set_default_settings_preprocess_generate_masks`
    # contains no other candidate, but a short generic helper might appear
    # inside a longer one's name.
    named.sort(key=len, reverse=True)
    return getattr(settings_module, named[0])


def _takes_settings_dict(func) -> bool:
    try:
        return "settings" in inspect.signature(func).parameters
    except (TypeError, ValueError):
        return False


def keys_from_factory(factory) -> Dict[str, Any]:
    """Every key the helper declares, by calling it on an empty dict."""
    try:
        result = factory({})
    except Exception:
        return {}
    return dict(result) if isinstance(result, dict) else {}


def keys_from_signature(func) -> Dict[str, Any]:
    """Keyword parameters and their defaults."""
    out: Dict[str, Any] = {}
    try:
        params = inspect.signature(func).parameters
    except (TypeError, ValueError):
        return out
    for name, param in params.items():
        if param.kind in (param.VAR_POSITIONAL, param.VAR_KEYWORD):
            continue
        out[name] = None if param.default is param.empty else param.default
    return out


def keys_from_source(func) -> Dict[str, Any]:
    """Keys the function reads off its ``settings`` argument.

    Walks the AST rather than the text, so a key inside a comment or a
    string is not mistaken for one that is read.
    """
    try:
        source = textwrap.dedent(inspect.getsource(func))
        tree = ast.parse(source)
    except (OSError, TypeError, SyntaxError):
        return {}
    found: Dict[str, Any] = {}
    for node in ast.walk(tree):
        if (isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr in ("get", "setdefault")
                and isinstance(node.func.value, ast.Name)
                and node.func.value.id == "settings"
                and node.args
                and isinstance(node.args[0], ast.Constant)
                and isinstance(node.args[0].value, str)):
            default: Any = None
            if len(node.args) > 1:
                try:
                    default = ast.literal_eval(node.args[1])
                except (ValueError, SyntaxError):
                    default = None
            found.setdefault(node.args[0].value, default)
        elif (isinstance(node, ast.Subscript)
                and isinstance(node.value, ast.Name)
                and node.value.id == "settings"
                and isinstance(node.slice, ast.Constant)
                and isinstance(node.slice.value, str)):
            found.setdefault(node.slice.value, None)
    return found


def surface(func, dotted: str = "") -> Tuple[str, Dict[str, Any]]:
    """``(shape, {key: default})`` for one function.

    :param dotted: the ``spacr.module.function`` path, so the CLI registry
        can be consulted before anything is inferred.
    """
    if _takes_settings_dict(func):
        for factory in (_factory_from_registry(dotted) if dotted else None,
                        _settings_factory(func)):
            if factory is None:
                continue
            keys = keys_from_factory(factory)
            if keys:
                return "factory", keys
        return "source", keys_from_source(func)
    return "signature", keys_from_signature(func)


# ---------------------------------------------------------------------------
# Tooltips, always read now and never pasted
# ---------------------------------------------------------------------------

def param_docs(func) -> Dict[str, str]:
    """``:param name:`` lines from the function's own docstring."""
    doc = inspect.getdoc(func) or ""
    out: Dict[str, str] = {}
    for match in re.finditer(
            r"^:param\s+(\w+):\s*(.+?)(?=^\s*:(?:param|returns|raises|rtype)\b|\Z)",
            doc, re.S | re.M):
        out[match.group(1)] = " ".join(match.group(2).split())
    return out


_REGISTERED = False


def _load_registrations() -> None:
    """Import every pipeline module, so its registered tooltips exist.

    ``spacr.settings.tooltips`` is not complete on import. Six pipelines --
    ``barcode_qc``, ``illumination``, ``convert`` and the rest -- own their
    keys and merge them in from their own module via
    :func:`spacr.settings.register_defaults`, which only runs when that
    module is imported. Read the dict cold and ``dst`` and ``cmap`` look
    undocumented; they are documented by whoever owns them.

    Getting this wrong is not a missing sentence, it is a WRONG one: the
    generator would have written "no description" into a notebook for a key
    that has a perfectly good one.
    """
    global _REGISTERED
    if _REGISTERED:
        return
    from spacr.cli import MODULES
    for module in MODULES.values():
        try:
            importlib.import_module(module.module_name)
        except Exception:
            # A pipeline whose optional dependency is absent still leaves
            # every other pipeline's tooltips loaded.
            pass
    _REGISTERED = True


def tooltip_for(key: str, shape: str, docs: Dict[str, str]) -> str:
    """One sentence describing ``key``, from whichever source declares it."""
    if shape == "signature":
        return docs.get(key, "")
    _load_registrations()
    from spacr.settings import tooltips
    return str(tooltips.get(key, "") or docs.get(key, ""))


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

_DYNAMIC_LITERALS = {
    # These factories deliberately size their worker pool from the current
    # machine.  Committing the evaluated integer makes notebooks alternate
    # between a workstation's 28/30 workers and a hosted runner's 1/2.  Keep
    # the executable expression so the documented default remains truthful
    # and regeneration is independent of the machine doing the check.
    ("spacr.core.preprocess_generate_masks", "n_jobs"):
        "max(1, (__import__('os').cpu_count() or 1) - 4)",
    ("spacr.measure.measure_crop", "n_jobs"):
        "max(1, (__import__('os').cpu_count() or 1) - 2)",
    ("spacr.deep_spacr.deep_spacr", "n_jobs"):
        "max(1, (__import__('os').cpu_count() or 1) - 4)",
}


def _literal(value: Any, *, dotted: str = "", key: str = "") -> str:
    """Repr that round-trips, or a portable executable default expression."""
    dynamic = _DYNAMIC_LITERALS.get((dotted, key))
    if dynamic is not None:
        return dynamic
    if isinstance(value, str):
        resource_root = REPO / "spacr" / "resources"
        try:
            relative = Path(value).resolve().relative_to(resource_root.resolve())
        except (OSError, ValueError):
            pass
        else:
            # ``spacr/resources`` intentionally contains data directories,
            # not import packages.  Python 3.9's ``importlib.resources``
            # fallback can also see ``spec.origin is None`` for an editable
            # installation of the parent package.  Anchor at the package's
            # concrete search path instead; wheels are installed as ordinary
            # directories, so this works in source and installed checkouts on
            # every supported Python.
            resource_parts = ("resources", *relative.parts)
            joined = ", ".join(repr(part) for part in resource_parts)
            # Keep package data portable across source checkouts, wheels and
            # hosted CI instead of baking the developer's absolute path into
            # a committed notebook.
            return (
                "str(__import__('pathlib').Path(next(iter("
                "__import__('spacr').__path__))).joinpath("
                f"{joined}))"
            )
    try:
        if ast.literal_eval(repr(value)) == value:
            return repr(value)
    except (ValueError, SyntaxError, TypeError):
        pass
    return f"None  # {type(value).__name__}, set this yourself"


def render_cell(entries: List[Tuple[str, str, Dict[str, Any], Dict[str, str]]]
                ) -> str:
    """Build the whole generated code cell.

    :param entries: one ``(dotted_name, shape, keys, docs)`` per function the
        notebook runs. A notebook that runs two pipelines gets two dicts,
        named for the function, because merging them would produce a dict
        that is right for neither.
    """
    lines: List[str] = [MARKER,
                        "# Values are this installed version's defaults; the "
                        "text above each key is",
                        "# its live description. Edit values in place -- a key "
                        "left at its default",
                        "# behaves exactly as if it were absent.", ""]
    for index, (dotted, shape, keys, docs) in enumerate(entries):
        name = "settings" if len(entries) == 1 else \
            f"{dotted.rsplit('.', 1)[1]}_settings"
        lines.append(f"# {dotted}  ({len(keys)} settings)")
        if shape == "source":
            lines.append(
                "# NOTE: this function has no settings helper declaring its "
                "keys -- the list")
            lines.append(
                "# below was read from its source, so a key it reads only on "
                "one branch may")
            lines.append("# be missing. See instruction 88.")
        lines.append(f"{name} = {{")
        for key in sorted(keys):
            tip = tooltip_for(key, shape, docs)
            if tip:
                for wrapped in textwrap.wrap(tip, WRAP):
                    lines.append(f"    # {wrapped}")
            lines.append(
                f"    {key!r}: {_literal(keys[key], dotted=dotted, key=key)},")
            lines.append("")
        if lines[-1] == "":
            lines.pop()
        lines.append("}")
        if index != len(entries) - 1:
            lines.append("")
    return "\n".join(lines)


def _as_source(text: str) -> List[str]:
    """Notebook JSON stores a cell as a list of lines, newlines included."""
    lines = text.split("\n")
    return [line + "\n" for line in lines[:-1]] + [lines[-1]]


# ---------------------------------------------------------------------------
# Rewriting one notebook
# ---------------------------------------------------------------------------

INTRO = (
    SECTION_TITLE + "\n\n"
    "Every key, with its default and what it controls. Edit values in "
    "place; delete nothing — a key left at its default behaves exactly as "
    "if it were absent.\n\n"
    "Generated from this installed version by "
    "`tools/build_notebook_settings.py`, so these are the real keys, the "
    "real defaults and the real descriptions. Re-run that tool after "
    "upgrading spaCR."
)


def rebuild(path: Path) -> Optional[str]:
    """Return the notebook's new JSON text, or None when it needs no cell."""
    # Factories are extended by module-level registrations.  Load every
    # registered pipeline before asking any factory for its keys; otherwise
    # the first notebook in a process sees a smaller surface than later ones
    # and pytest's prior imports change the generated result.
    _load_registrations()
    notebook = json.loads(path.read_text())
    entries = []
    for dotted in declared_functions(notebook):
        func = resolve(dotted)
        if func is None:
            continue
        shape, keys = surface(func, dotted)
        if keys:
            entries.append((dotted, shape, keys, param_docs(func)))
    if not entries:
        return None

    cell_source = _as_source(render_cell(entries))
    cells = notebook["cells"]
    retarget_call(cells, entries)

    # Replace in place when a generated cell is already there.
    for cell in cells:
        if cell.get("cell_type") == "code" and \
                "".join(cell.get("source", [])).startswith(MARKER):
            cell["source"] = cell_source
            cell["outputs"] = []
            cell["execution_count"] = None
            return json.dumps(notebook, indent=1, ensure_ascii=False) + "\n"

    # Otherwise replace the hand-made block under the existing heading...
    for index, cell in enumerate(cells):
        if cell.get("cell_type") == "markdown" and \
                SECTION_TITLE.lstrip("# ").split("\n")[0] in \
                "".join(cell.get("source", [])):
            cells[index]["source"] = _as_source(INTRO)
            if index + 1 < len(cells) and cells[index + 1]["cell_type"] == "code":
                cells[index + 1]["source"] = cell_source
                cells[index + 1]["outputs"] = []
                cells[index + 1]["execution_count"] = None
            else:
                cells.insert(index + 1, _code_cell(cell_source))
            return json.dumps(notebook, indent=1, ensure_ascii=False) + "\n"

    # ...or add both, immediately before the cell that runs the pipeline.
    at = _insertion_point(cells)
    cells.insert(at, {"cell_type": "markdown", "metadata": {},
                      "source": _as_source(INTRO)})
    cells.insert(at + 1, _code_cell(cell_source))
    return json.dumps(notebook, indent=1, ensure_ascii=False) + "\n"


def retarget_call(cells: List[dict], entries) -> None:
    """Make the run cell consume the generated dict.

    THE COMMENTED-OUT CALL WAS A SECOND PASTE. Eight notebooks carried a
    line like::

        # custom_volcano_plot(data_path, metadata_path,
        #                     metadata_column='tagm_location', ...)

    which restates the signature by hand -- exactly the copy that goes stale
    in silence that instruction 88 rule 3 is about. A renamed parameter
    would leave it wrong and nothing would say so.

    ``func(**settings)`` says the same thing without repeating anything, and
    it is what the other twenty-two notebooks already do: the settings dict
    directly above IS the call's arguments, so editing a value there changes
    the run rather than decorating it.

    Only a cell that is ENTIRELY commented-out calls of this function is
    rewritten. A cell with real code in it is somebody's example and is left
    exactly as it is.
    """
    if len(entries) != 1:
        # A notebook running two pipelines names its dicts per function, so
        # there is no single `settings` to hand anything.
        return
    dotted, shape, _keys, _docs = entries[0]
    name = dotted.rsplit(".", 1)[1]
    # A keyword function is spread; a settings-dict function takes the dict.
    call = f"{name}(**settings)" if shape == "signature" else f"{name}(settings)"
    for cell in cells:
        if cell.get("cell_type") != "code":
            continue
        lines = [line.strip() for line in
                 "".join(cell.get("source", [])).split("\n") if line.strip()]
        if not lines:
            continue
        if all(line.startswith(f"# {name}(") for line in lines):
            cell["source"] = _as_source(call)
            cell["outputs"] = []
            cell["execution_count"] = None
            return


def _code_cell(source: List[str]) -> dict:
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": source}


def _insertion_point(cells: List[dict]) -> int:
    """Before the "Run it" heading, or before the last code cell.

    The settings have to be readable BEFORE the cell that consumes them, or
    a reader who runs the notebook top to bottom meets the run first.
    """
    for index, cell in enumerate(cells):
        if cell.get("cell_type") == "markdown" and \
                "Run it" in "".join(cell.get("source", [])):
            return index
    for index in range(len(cells) - 1, -1, -1):
        if cells[index].get("cell_type") == "code":
            return index
    return len(cells)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if any notebook is stale")
    parser.add_argument("--notebooks", default=str(NOTEBOOKS))
    args = parser.parse_args(argv)

    root = Path(args.notebooks)
    stale, written, skipped = [], [], []
    for path in sorted(root.glob("*.ipynb")):
        try:
            new_text = rebuild(path)
        except Exception as exc:
            print(f"  !! {path.name}: {type(exc).__name__}: {exc}")
            stale.append(path.name)
            continue
        if new_text is None:
            skipped.append(path.name)
            continue
        if new_text == path.read_text():
            continue
        if args.check:
            stale.append(path.name)
        else:
            path.write_text(new_text)
            written.append(path.name)

    if skipped:
        print(f"no settings surface, left alone: {len(skipped)}")
    if args.check:
        if stale:
            print("STALE — re-run tools/build_notebook_settings.py:")
            for name in stale:
                print(f"  {name}")
            return 1
        print("every notebook is current")
        return 0
    print(f"rewrote {len(written)} notebook(s)")
    for name in written:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
