#!/usr/bin/env python
"""Regenerate the settings reference in every shipped notebook.

Each generated section has three consecutive cells: a readable Markdown
reference, an editable settings dictionary, and the function call that uses
that dictionary. Descriptions come from the live spaCR tooltip table or the
function's scientific-Python docstring; they are never copied into the code
cell. A regeneration test keeps notebooks synchronized with API changes.

Usage::

    python tools/build_notebook_settings.py           # rewrite
    python tools/build_notebook_settings.py --check    # exit 1 if stale

The generator supports three API shapes:

``factory``
    The function takes a settings dict and a ``spacr.settings`` helper
    declares its keys. Keys and defaults come from calling that helper on an
    empty dict; descriptions come from :data:`spacr.settings.tooltips`.

``signature``
    The function takes ordinary keyword arguments -- ``custom_volcano_plot``
    has nine, ``ml_analysis`` twenty-eight. Names and defaults come from
    :func:`inspect.signature` and the tooltip is the function's own
    ``Parameters`` section or ``:param`` field.

``source``
    The function takes a settings dict and NOTHING DECLARES ITS KEYS: it
    reads ``settings.get('x', default)`` inline. The keys are recovered by
    walking the function's AST. The Markdown reference identifies this weaker
    source so readers know that branch-specific keys may be absent.
"""
from __future__ import annotations

import argparse
import ast
import importlib
import inspect
import json
import re
import sys
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

REPO = Path(__file__).resolve().parent.parent
NOTEBOOKS = REPO / "Notebooks"

# Running ``python tools/build_notebook_settings.py`` otherwise puts only the
# tools directory at the front of sys.path.  In an editable installation that
# can import a different spaCR checkout than the notebooks being regenerated.
# The drift guard imports from this checkout, so the command must do the same.
repo_text = str(REPO)
if sys.path[0] != repo_text:
    sys.path.insert(0, repo_text)

# Freeze the core tooltip table before importing any pipeline. Optional
# dependency availability changes which pipeline modules can register, but it
# must never change the wording of a shared setting in a committed notebook.
# Module-owned keys absent from this snapshot still fall back to the complete
# post-registration table in ``tooltip_for`` below.
from spacr.settings import tooltips as _CORE_TOOLTIP_TABLE  # noqa: E402
CORE_TOOLTIPS = dict(_CORE_TOOLTIP_TABLE)

#: Legacy source marker retained so existing notebooks can be migrated.
MARKER = "# Generated by tools/build_notebook_settings.py — do not edit by hand."

#: Heading of the generated Markdown reference.
SECTION_TITLE = "## 3. Settings and API reference"

#: Metadata values used to find generated cells without putting prose in code.
HELP_CELL_KIND = "settings-help"
SETTINGS_CELL_KIND = "settings"

#: Root of the published sphinx-autoapi tree.
API_BASE = "https://einarolafsson.github.io/spacr/api"


# ---------------------------------------------------------------------------
# Which function a notebook drives
# ---------------------------------------------------------------------------

def declared_functions(notebook: dict) -> List[str]:
    """Return the callable named first in the notebook's function section.

    Related next-step links can name other spaCR callables later in the same
    Markdown cell. The first dotted path is the declared function; treating
    every later link as another pipeline produces unused settings dictionaries.
    """
    for cell in notebook.get("cells", []):
        if cell.get("cell_type") != "markdown":
            continue
        text = "".join(cell.get("source", []))
        if "function" in text and "this notebook runs" in text:
            matches = re.findall(r"`(spacr\.[A-Za-z_0-9.]+)`", text)
            return matches[:1]
    return []


def resolve(dotted: str):
    """Import ``spacr.module.function`` and return the callable, or None."""
    module_name, _, attr = dotted.rpartition(".")
    try:
        return getattr(importlib.import_module(module_name), attr)
    except (ImportError, AttributeError):
        return None


# ---------------------------------------------------------------------------
# The three shapes
# ---------------------------------------------------------------------------

def _factory_from_registry(dotted: str) -> Optional[Any]:
    """Return the defaults helper registered for an entry point.

    The CLI registry is shared with the GUI and includes helpers that live
    outside :mod:`spacr.settings`. Reusing it keeps built-in and plugin apps
    consistent without maintaining another entry-point mapping.
    """
    from spacr.cli import MODULES

    module_name, _, attr = dotted.rpartition(".")
    for module in MODULES.values():
        if module.module_name != module_name or module.func_name != attr:
            continue
        if module.defaults_entry:
            return resolve(module.defaults_entry.replace(":", "."))
        if module.defaults:
            import spacr.settings as settings_module
            return getattr(settings_module, module.defaults, None)
    return None


def _settings_factory(func) -> Optional[Any]:
    """The ``spacr.settings`` helper this function canonicalizes through.

    The fallback for a function the CLI does not register: look for a
    settings helper NAMED IN ITS OWN SOURCE, which is the only definition
    that cannot go out of step with what actually runs. A name-convention
    guess would happily pair a function with a helper it never calls.
    """
    import spacr.settings as settings_module

    candidates = [
        name for name in dir(settings_module)
        if "settings" in name and callable(getattr(settings_module, name, None))
    ]
    try:
        source = inspect.getsource(func)
    except (OSError, TypeError):
        return None
    named = [name for name in candidates if re.search(rf"\b{name}\b", source)]
    if not named:
        return None
    # Longest name wins: `set_default_settings_preprocess_generate_masks`
    # contains no other candidate, but a short generic helper might appear
    # inside a longer one's name.
    named.sort(key=len, reverse=True)
    return getattr(settings_module, named[0])


def _takes_settings_dict(func) -> bool:
    try:
        return "settings" in inspect.signature(func).parameters
    except (TypeError, ValueError):
        return False


def keys_from_factory(factory) -> Dict[str, Any]:
    """Every key the helper declares, by calling it on an empty dict."""
    try:
        result = factory({})
    except Exception:
        return {}
    return dict(result) if isinstance(result, dict) else {}


def keys_from_signature(func) -> Dict[str, Any]:
    """Keyword parameters and their defaults."""
    out: Dict[str, Any] = {}
    try:
        params = inspect.signature(func).parameters
    except (TypeError, ValueError):
        return out
    for name, param in params.items():
        if param.kind in (param.VAR_POSITIONAL, param.VAR_KEYWORD):
            continue
        out[name] = None if param.default is param.empty else param.default
    return out


def keys_from_source(func) -> Dict[str, Any]:
    """Keys the function reads off its ``settings`` argument.

    Walks the AST rather than the text, so a key inside a comment or a
    string is not mistaken for one that is read.
    """
    try:
        source = textwrap.dedent(inspect.getsource(func))
        tree = ast.parse(source)
    except (OSError, TypeError, SyntaxError):
        return {}
    found: Dict[str, Any] = {}
    for node in ast.walk(tree):
        if (isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr in ("get", "setdefault")
                and isinstance(node.func.value, ast.Name)
                and node.func.value.id == "settings"
                and node.args
                and isinstance(node.args[0], ast.Constant)
                and isinstance(node.args[0].value, str)):
            default: Any = None
            if len(node.args) > 1:
                try:
                    default = ast.literal_eval(node.args[1])
                except (ValueError, SyntaxError):
                    default = None
            found.setdefault(node.args[0].value, default)
        elif (isinstance(node, ast.Subscript)
                and isinstance(node.value, ast.Name)
                and node.value.id == "settings"
                and isinstance(node.slice, ast.Constant)
                and isinstance(node.slice.value, str)):
            found.setdefault(node.slice.value, None)
    return found


def surface(func, dotted: str = "") -> Tuple[str, Dict[str, Any]]:
    """``(shape, {key: default})`` for one function.

    :param dotted: the ``spacr.module.function`` path, so the CLI registry
        can be consulted before anything is inferred.
    """
    if _takes_settings_dict(func):
        for factory in (_factory_from_registry(dotted) if dotted else None,
                        _settings_factory(func)):
            if factory is None:
                continue
            keys = keys_from_factory(factory)
            if keys:
                return "factory", keys
        return "source", keys_from_source(func)
    return "signature", keys_from_signature(func)


# ---------------------------------------------------------------------------
# Tooltips, always read now and never pasted
# ---------------------------------------------------------------------------

def param_docs(func) -> Dict[str, str]:
    """Return parameter descriptions from RST or numpydoc docstrings."""
    doc = inspect.getdoc(func) or ""
    out: Dict[str, str] = {}
    for match in re.finditer(
            r"^:param\s+(\w+):\s*(.+?)(?=^\s*:(?:param|returns|raises|rtype)\b|\Z)",
            doc, re.S | re.M):
        out[match.group(1)] = " ".join(match.group(2).split())

    # Scientific-Python APIs use a ``Parameters`` section rather than RST
    # fields.  Stop at the next underlined section heading so Returns/Raises
    # entries cannot be mistaken for parameters.
    lines = doc.splitlines()
    section = next((
        index for index in range(len(lines) - 1)
        if lines[index].strip() == "Parameters"
        and set(lines[index + 1].strip()) == {"-"}
    ), None)
    if section is None:
        return out

    parameter = re.compile(
        r"^([A-Za-z_]\w*(?:\s*,\s*[A-Za-z_]\w*)*)\s*:\s*.+$"
    )
    index = section + 2
    while index < len(lines):
        if (index + 1 < len(lines) and lines[index].strip()
                and set(lines[index + 1].strip()) == {"-"}):
            break
        match = parameter.match(lines[index].strip())
        if match is None:
            index += 1
            continue
        names = [name.strip() for name in match.group(1).split(",")]
        index += 1
        description = []
        while index < len(lines):
            if (index + 1 < len(lines) and lines[index].strip()
                    and set(lines[index + 1].strip()) == {"-"}):
                break
            if parameter.match(lines[index].strip()):
                break
            if lines[index].strip():
                description.append(lines[index].strip())
            index += 1
        rendered = " ".join(description)
        for name in names:
            out.setdefault(name, rendered)
    return out


_REGISTERED = False


def _load_registrations() -> None:
    """Import every pipeline module, so its registered tooltips exist.

    ``spacr.settings.tooltips`` is not complete on import. Six pipelines --
    ``barcode_qc``, ``illumination``, ``convert`` and the rest -- own their
    keys and merge them in from their own module via
    :func:`spacr.settings.register_defaults`, which only runs when that
    module is imported. Read the dict cold and ``dst`` and ``cmap`` look
    undocumented; they are documented by whoever owns them.

    Getting this wrong is not a missing sentence, it is a WRONG one: the
    generator would have written "no description" into a notebook for a key
    that has a perfectly good one.
    """
    global _REGISTERED
    if _REGISTERED:
        return
    from spacr.cli import MODULES
    for module in MODULES.values():
        try:
            importlib.import_module(module.module_name)
        except Exception:
            # A pipeline whose optional dependency is absent still leaves
            # every other pipeline's tooltips loaded.
            pass
    _REGISTERED = True


def tooltip_for(key: str, shape: str, docs: Dict[str, str]) -> str:
    """One sentence describing ``key``, from whichever source declares it."""
    if shape == "signature":
        return docs.get(key, "")
    if key in CORE_TOOLTIPS:
        return str(CORE_TOOLTIPS[key] or docs.get(key, ""))
    _load_registrations()
    from spacr.settings import tooltips
    return str(tooltips.get(key, "") or docs.get(key, ""))


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

_DYNAMIC_LITERALS = {
    # These factories deliberately size their worker pool from the current
    # machine.  Committing the evaluated integer makes notebooks alternate
    # between a workstation's 28/30 workers and a hosted runner's 1/2.  Keep
    # the executable expression so the documented default remains truthful
    # and regeneration is independent of the machine doing the check.
    ("spacr.core.preprocess_generate_masks", "n_jobs"):
        "max(1, (__import__('os').cpu_count() or 1) - 4)",
    ("spacr.measure.measure_crop", "n_jobs"):
        "max(1, (__import__('os').cpu_count() or 1) - 2)",
    ("spacr.deep_spacr.deep_spacr", "n_jobs"):
        "max(1, (__import__('os').cpu_count() or 1) - 4)",
}


def _literal(value: Any, *, dotted: str = "", key: str = "") -> str:
    """Repr that round-trips, or a portable executable default expression."""
    dynamic = _DYNAMIC_LITERALS.get((dotted, key))
    if dynamic is not None:
        return dynamic
    if isinstance(value, str):
        resource_root = REPO / "spacr" / "resources"
        try:
            relative = Path(value).resolve().relative_to(resource_root.resolve())
        except (OSError, ValueError):
            pass
        else:
            # ``spacr/resources`` intentionally contains data directories,
            # not import packages.  Python 3.9's ``importlib.resources``
            # fallback can also see ``spec.origin is None`` for an editable
            # installation of the parent package.  Anchor at the package's
            # concrete search path instead; wheels are installed as ordinary
            # directories, so this works in source and installed checkouts on
            # every supported Python.
            resource_parts = ("resources", *relative.parts)
            joined = ", ".join(repr(part) for part in resource_parts)
            # Keep package data portable across source checkouts, wheels and
            # hosted CI instead of baking the developer's absolute path into
            # a committed notebook.
            return (
                "str(__import__('pathlib').Path(next(iter("
                "__import__('spacr').__path__))).joinpath("
                f"{joined}))"
            )
    try:
        if ast.literal_eval(repr(value)) == value:
            return repr(value)
    except (ValueError, SyntaxError, TypeError):
        pass
    return f"None  # {type(value).__name__}, set this yourself"


def setting_name(dotted: str, entries: list) -> str:
    """Return the settings-variable name for one notebook entry."""
    if len(entries) == 1:
        return "settings"
    return f"{dotted.rsplit('.', 1)[1]}_settings"


def api_url(dotted: str) -> str:
    """Return the published API URL for a dotted spaCR callable."""
    module_name = dotted.rpartition(".")[0]
    module_path = module_name.replace(".", "/")
    return f"{API_BASE}/{module_path}/index.html#{dotted}"


def _markdown_text(text: str) -> str:
    """Normalize tooltip prose for a Markdown bullet."""
    return (" ".join(str(text).split())
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;"))


def render_help(entries: List[Tuple[str, str, Dict[str, Any], Dict[str, str]]]
                ) -> str:
    """Build the Markdown reference shown above the settings cell."""
    lines = [
        SECTION_TITLE,
        "",
        "Read the descriptions here, then edit only the values in the next "
        "cell. Defaults and descriptions are generated from the installed "
        "spaCR version, so the notebook stays aligned with the API.",
    ]
    for dotted, shape, keys, docs in entries:
        lines.extend([
            "",
            f"### [`{dotted}`]({api_url(dotted)})",
            "",
        ])
        if shape == "source":
            lines.extend([
                "> This function does not yet expose a settings factory. The "
                "list below is recovered from direct settings access in its "
                "source, so a key used only on a dynamic branch may be absent.",
                "",
            ])
        for key in sorted(keys):
            description = _markdown_text(tooltip_for(key, shape, docs))
            if not description:
                description = "No description is available in this version."
            lines.append(f"- **`{key}`** — {description}")
    lines.extend([
        "",
        "## 4. Run",
        "",
        "After editing the settings cell, run the function cell immediately "
        "below it. Long operations report progress through spaCR's logging "
        "system; set `SPACR_LOG_LEVEL=DEBUG` before starting Jupyter for more "
        "detail.",
    ])
    return "\n".join(lines)


def render_cell(entries: List[Tuple[str, str, Dict[str, Any], Dict[str, str]]]
                ) -> str:
    """Build the editable settings-only code cell."""
    lines: List[str] = []
    for index, (dotted, shape, keys, docs) in enumerate(entries):
        name = setting_name(dotted, entries)
        lines.append(f"{name} = {{")
        for key in sorted(keys):
            lines.append(
                f"    {key!r}: {_literal(keys[key], dotted=dotted, key=key)},")
        lines.append("}")
        if index != len(entries) - 1:
            lines.append("")
    return "\n".join(lines)


def _as_source(text: str) -> List[str]:
    """Notebook JSON stores a cell as a list of lines, newlines included."""
    lines = text.split("\n")
    return [line + "\n" for line in lines[:-1]] + [lines[-1]]


# ---------------------------------------------------------------------------
# Rewriting one notebook
# ---------------------------------------------------------------------------

def rebuild(path: Path) -> Optional[str]:
    """Return the notebook's new JSON text, or None when it needs no cell."""
    # Factories are extended by module-level registrations.  Load every
    # registered pipeline before asking any factory for its keys; otherwise
    # the first notebook in a process sees a smaller surface than later ones
    # and pytest's prior imports change the generated result.
    _load_registrations()
    notebook = json.loads(path.read_text())
    entries = []
    for dotted in declared_functions(notebook):
        func = resolve(dotted)
        if func is None:
            continue
        shape, keys = surface(func, dotted)
        if keys:
            entries.append((dotted, shape, keys, param_docs(func)))
    if not entries:
        return None

    help_source = _as_source(render_help(entries))
    cell_source = _as_source(render_cell(entries))
    cells = notebook["cells"]
    retarget_call(cells, entries)

    help_cell = next((cell for cell in cells
                      if _cell_kind(cell) == HELP_CELL_KIND), None)
    if help_cell is None:
        help_cell = next((cell for cell in cells
                          if cell.get("cell_type") == "markdown"
                          and "Every setting this function accepts" in
                          "".join(cell.get("source", []))), None)

    settings_cell = next((cell for cell in cells
                          if _cell_kind(cell) == SETTINGS_CELL_KIND), None)
    if settings_cell is None:
        settings_cell = next((cell for cell in cells
                              if cell.get("cell_type") == "code" and
                              "".join(cell.get("source", [])).startswith(
                                  MARKER)), None)

    if settings_cell is None:
        at = _insertion_point(cells)
        help_cell = _markdown_cell(help_source, HELP_CELL_KIND)
        settings_cell = _code_cell(cell_source, SETTINGS_CELL_KIND)
        cells.insert(at, help_cell)
        cells.insert(at + 1, settings_cell)
    else:
        settings_cell["source"] = cell_source
        settings_cell["outputs"] = []
        settings_cell["execution_count"] = None
        _mark_generated(settings_cell, SETTINGS_CELL_KIND)
        if help_cell is None:
            at = cells.index(settings_cell)
            help_cell = _markdown_cell(help_source, HELP_CELL_KIND)
            cells.insert(at, help_cell)
        else:
            help_cell["source"] = help_source
            _mark_generated(help_cell, HELP_CELL_KIND)

    _remove_legacy_setup(cells, help_cell)
    _place_generated_cells(cells, help_cell, settings_cell)
    _place_run_cell(cells, settings_cell, entries)
    return json.dumps(notebook, indent=1, ensure_ascii=False) + "\n"


def retarget_call(cells: List[dict], entries) -> None:
    """Make a commented example call consume the generated dictionary.

    Some notebooks formerly carried a call such as::

        # custom_volcano_plot(data_path, metadata_path,
        #                     metadata_column='tagm_location', ...)

    which restated the signature separately from the settings cell. Replacing
    it with ``func(**settings)`` ensures renamed parameters fail visibly.

    Only a cell that is ENTIRELY commented-out calls of this function is
    rewritten. A cell with real code in it is somebody's example and is left
    exactly as it is.
    """
    if len(entries) != 1:
        # A notebook running two pipelines names its dicts per function, so
        # there is no single `settings` to hand anything.
        return
    dotted, shape, _keys, _docs = entries[0]
    name = dotted.rsplit(".", 1)[1]
    # A keyword function is spread; a settings-dict function takes the dict.
    call = f"{name}(**settings)" if shape == "signature" else f"{name}(settings)"
    for cell in cells:
        if cell.get("cell_type") != "code":
            continue
        lines = [line.strip() for line in
                 "".join(cell.get("source", [])).split("\n") if line.strip()]
        if not lines:
            continue
        if all(line.startswith(f"# {name}(") for line in lines):
            cell["source"] = _as_source(call)
            cell["outputs"] = []
            cell["execution_count"] = None
            return


def _cell_kind(cell: dict) -> str:
    """Return the spaCR generator kind stored in cell metadata."""
    metadata = cell.get("metadata", {}).get("spacr", {})
    return str(metadata.get("generated", "")) if isinstance(metadata, dict) else ""


def _mark_generated(cell: dict, kind: str) -> None:
    """Mark a cell as generator-owned without adding prose to executable code."""
    cell.setdefault("id", f"spacr-{kind}")
    metadata = cell.setdefault("metadata", {})
    spacr_metadata = metadata.setdefault("spacr", {})
    spacr_metadata.update({
        "generated": kind,
        "tool": "tools/build_notebook_settings.py",
    })


def _code_cell(source: List[str], kind: str = "") -> dict:
    cell = {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": source}
    if kind:
        _mark_generated(cell, kind)
    return cell


def _markdown_cell(source: List[str], kind: str = "") -> dict:
    cell = {"cell_type": "markdown", "metadata": {}, "source": source}
    if kind:
        _mark_generated(cell, kind)
    return cell


def _remove_legacy_setup(cells: List[dict], help_cell: dict) -> None:
    """Remove the redundant defaults preview that preceded old references."""
    index = next(i for i, cell in enumerate(cells) if cell is help_cell)
    if index and cells[index - 1].get("cell_type") == "code":
        source = "".join(cells[index - 1].get("source", []))
        if "defaults =" in source and "for key in sorted(defaults)" in source:
            cells.pop(index - 1)
            index -= 1
    if index and cells[index - 1].get("cell_type") == "markdown":
        source = "".join(cells[index - 1].get("source", [])).lstrip()
        if source.startswith("## 3. Settings") or source.startswith("## 3. Call it"):
            cells.pop(index - 1)


def _place_generated_cells(cells: List[dict], help_cell: dict,
                           settings_cell: dict) -> None:
    """Place the Markdown reference immediately before editable settings."""
    cells.remove(help_cell)
    cells.remove(settings_cell)
    at = _insertion_point(cells)
    cells.insert(at, help_cell)
    cells.insert(at + 1, settings_cell)


def _place_run_cell(cells: List[dict], settings_cell: dict, entries) -> None:
    """Place the function call immediately after the settings dictionary."""
    names = {dotted.rsplit(".", 1)[1] for dotted, *_rest in entries}
    run_cell = None
    for cell in cells:
        if cell is settings_cell or cell.get("cell_type") != "code":
            continue
        source = "".join(cell.get("source", []))
        if any(re.search(rf"\b{re.escape(name)}\s*\(", source)
               for name in names):
            run_cell = cell
            break
    if run_cell is None:
        return

    # The old standalone Run heading separated settings from the call. Its
    # useful logging guidance now lives at the end of the reference cell.
    for cell in list(cells):
        if cell.get("cell_type") != "markdown":
            continue
        source = "".join(cell.get("source", [])).lstrip()
        if source.startswith("## 4. Run it"):
            cells.remove(cell)

    cells.remove(run_cell)
    at = next(i for i, cell in enumerate(cells) if cell is settings_cell)
    cells.insert(at + 1, run_cell)


def _insertion_point(cells: List[dict]) -> int:
    """Return the position before the run heading or final code cell.

    The settings have to be readable BEFORE the cell that consumes them, or
    a reader who runs the notebook top to bottom meets the run first.
    """
    for index, cell in enumerate(cells):
        source = "".join(cell.get("source", [])).lstrip()
        if cell.get("cell_type") == "markdown" and \
                source.startswith("## 4. Run it"):
            return index
    for index in range(len(cells) - 1, -1, -1):
        if cells[index].get("cell_type") == "code":
            return index
    return len(cells)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if any notebook is stale")
    parser.add_argument("--notebooks", default=str(NOTEBOOKS))
    args = parser.parse_args(argv)

    root = Path(args.notebooks)
    stale, written, skipped = [], [], []
    for path in sorted(root.glob("*.ipynb")):
        try:
            new_text = rebuild(path)
        except Exception as exc:
            print(f"  !! {path.name}: {type(exc).__name__}: {exc}")
            stale.append(path.name)
            continue
        if new_text is None:
            skipped.append(path.name)
            continue
        if new_text == path.read_text():
            continue
        if args.check:
            stale.append(path.name)
        else:
            path.write_text(new_text)
            written.append(path.name)

    if skipped:
        print(f"no settings surface, left alone: {len(skipped)}")
    if args.check:
        if stale:
            print("STALE — re-run tools/build_notebook_settings.py:")
            for name in stale:
                print(f"  {name}")
            return 1
        print("every notebook is current")
        return 0
    print(f"rewrote {len(written)} notebook(s)")
    for name in written:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
