name: spacr-docs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - sphinx
  - tables
  - h5py
  - numpy
  - matplotlib
  - pip:
      - huggingface-hub>=0.24,<0.25
      - wandb>=0.16.2
      - openai>=1.50.2,<2.0
      - tqdm>=4.65.0
      - ipywidgets
      - ipykernel
      - screeninfo
      - brokenaxes
      - gdown
      - rapidfuzz>=3.9,<4.0
      - sphinx_rtd_theme
