name: Build & Publish Docs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install docs builder
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install . --no-deps
          python -m pip install sphinx sphinx_rtd_theme sphinx-autoapi

      - name: Build with Sphinx
        run: |
          # Build the docs into docs/build/html
          sphinx-build -b html docs/source docs/build/html

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Publish the built docs in docs/build/html
          publish_dir: docs/build/html
