# .github/workflows/docs.yml
name: Build & Publish Sphinx Docs to main/docs

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repo, with full history so we can push back
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2) Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 3) Install your package and Sphinx
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install sphinx sphinx_rtd_theme

      # 4) Build the HTML into docs/ (overwriting index.html, _static/, etc.)
      - name: Build Sphinx HTML
        run: |
          sphinx-build -b html docs/source docs

      # 5) Commit the generated HTML back to main/docs
      - name: Commit and push docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📚 Auto‑build docs"
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
          file_pattern: docs/


