name: 📚 Build & Deploy pdoc Docs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pdoc
        run: python -m pip install --upgrade pip pdoc

      - name: Generate docs with pdoc
        run: |
          rm -rf docs
          pdoc -o docs spacr

      - name: Commit & push docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📚 Auto‑generate docs via pdoc"
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
          file_pattern: docs/**
